import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.90.1";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const allowedRoles=new Set(["platform_founder","school_owner","principal","administrator"]);
Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"POST required"},405);
 const url=Deno.env.get("SUPABASE_URL")??"",anon=Deno.env.get("SUPABASE_ANON_KEY")??"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
 if(!url||!serviceKey)return json({error:"Server configuration unavailable"},503);
 const auth=req.headers.get("authorization")??"",token=auth.replace(/^Bearer\s+/i,"");if(!token)return json({error:"Authentication required"},401);
 let input:{schoolId?:string;limit?:number}={};try{input=await req.json();}catch{}if(!input.schoolId)return json({error:"schoolId is required"},400);
 const admin=createClient(url,serviceKey,{auth:{persistSession:false}});
 if(token!==serviceKey){const userClient=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}),{data:userData,error:userError}=await userClient.auth.getUser();if(userError||!userData.user)return json({error:"Invalid session"},401);const{data:membership}=await admin.from("dreem_school_memberships").select("role,status").eq("school_id",input.schoolId).eq("profile_id",userData.user.id).eq("status","approved").maybeSingle();if(!membership||!allowedRoles.has(String(membership.role)))return json({error:"School communications authority required"},403);}
 const limit=Math.max(1,Math.min(Number(input.limit??50),200));const{data:deliveries,error:deliveryError}=await admin.from("dreem_notification_deliveries").select("id,school_id,announcement_id,recipient_user_id,channel,status,attempts").eq("school_id",input.schoolId).in("status",["queued","retrying"]).neq("channel","in_app").order("queued_at").limit(limit);if(deliveryError)return json({error:deliveryError.message},500);
 let sent=0,failed=0,skipped=0;
 for(const delivery of deliveries??[]){const[{data:announcement},{data:endpoint}]=await Promise.all([admin.from("dreem_announcements").select("title,body,priority,category").eq("id",delivery.announcement_id).maybeSingle(),admin.from("dreem_notification_endpoints").select("endpoint").eq("school_id",delivery.school_id).eq("user_id",delivery.recipient_user_id).eq("channel",delivery.channel).eq("enabled",true).eq("verified",true).limit(1).maybeSingle()]);if(!announcement||!endpoint){await admin.from("dreem_notification_deliveries").update({status:"failed",last_error:"Verified endpoint or announcement unavailable",attempts:Number(delivery.attempts??0)+1,updated_at:new Date().toISOString()}).eq("id",delivery.id);failed++;continue;}
   try{let providerMessageId="";if(delivery.channel==="email"){const key=Deno.env.get("RESEND_API_KEY"),from=Deno.env.get("DREEM_FROM_EMAIL");if(!key||!from)throw new Error("Email provider is not configured");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({from,to:[endpoint.endpoint],subject:announcement.title,text:announcement.body})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String((result as {message?:string})?.message??`Email provider returned ${response.status}`));providerMessageId=String((result as {id?:string})?.id??"");}
   else{const prefix=String(delivery.channel).toUpperCase(),webhook=Deno.env.get(`${prefix}_WEBHOOK_URL`),providerToken=Deno.env.get(`${prefix}_WEBHOOK_TOKEN`);if(!webhook)throw new Error(`${delivery.channel} provider is not configured`);const response=await fetch(webhook,{method:"POST",headers:{"content-type":"application/json",...(providerToken?{Authorization:`Bearer ${providerToken}`}:{})},body:JSON.stringify({to:endpoint.endpoint,title:announcement.title,message:announcement.body,priority:announcement.priority,category:announcement.category,deliveryId:delivery.id})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String((result as {message?:string})?.message??`${delivery.channel} provider returned ${response.status}`));providerMessageId=String((result as {id?:string;messageId?:string})?.id??(result as {messageId?:string})?.messageId??"");}
   await admin.from("dreem_notification_deliveries").update({status:"sent",provider_message_id:providerMessageId||null,sent_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq("id",delivery.id);sent++;}
   catch(reason){const message=reason instanceof Error?reason.message:"Provider delivery failed";await admin.from("dreem_notification_deliveries").update({status:"retrying",last_error:message,attempts:Number(delivery.attempts??0)+1,updated_at:new Date().toISOString()}).eq("id",delivery.id);if(message.includes("not configured"))skipped++;else failed++;}}
 return json({processed:(deliveries??[]).length,sent,failed,waitingForProvider:skipped});
});
