import { BookCheck, CalendarClock, ClipboardCheck, FileBadge2, ShieldCheck, UserRoundCheck } from "lucide-react";
import { useState, type FormEvent, type ReactNode } from "react";
import { assignTeacher, generateReportCard, publishAssessment, publishReportCard, reviewAssessment, reviewLessonPlan, saveCurriculumOutcome, scheduleTimetableEntry, type WorkspaceData } from "../lib/repository";

const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const key=(scope:string)=>`${scope}:${crypto.randomUUID()}`;
function readableError(reason:unknown){return reason instanceof Error?reason.message:reason&&typeof reason==="object"&&"message" in reason&&typeof reason.message==="string"?reason.message:"Academic action could not be completed.";}

export default function AcademicJourneyWorkspace({workspace,onRefresh,onOpenStudio}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>;onOpenStudio:()=>void}){
  const {setup,academics}=workspace;
  const teachers=workspace.operations.memberships.filter(x=>x.status==="approved"&&["teacher","academic_head","principal","school_owner"].includes(x.role));
  const submittedPlans=academics.lessonPlans.filter(x=>x.status==="submitted"),submittedAssessments=academics.assessments.filter(x=>x.status==="submitted"),approvedAssessments=academics.assessments.filter(x=>x.status==="approved"),draftReports=academics.reportCards.filter(x=>x.status==="draft");
  const missing=[setup.academicYears.length?"":"academic year",setup.terms.length?"":"term",setup.classes.length?"":"class",setup.subjects.length?"":"subject",teachers.length?"":"approved teacher"].filter(Boolean);
  const activeYear=setup.academicYears.find(x=>x.status==="active")?.id??setup.academicYears[0]?.id??"",term=setup.terms[0]?.id??"",classId=setup.classes[0]?.id??"",subjectId=setup.subjects[0]?.id??"";
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [outcome,setOutcome]=useState({academicYearId:activeYear,classId,subjectId,code:"",titleEn:"",titleFr:"",description:"",source:"school" as const});
  const [ownership,setOwnership]=useState({academicYearId:activeYear,termId:term,classId,subjectId,teacherUserId:teachers[0]?.profileId??"",weeklyPeriods:5});
  const [period,setPeriod]=useState({assignmentId:academics.assignments.find(x=>x.status==="active")?.id??"",weekday:1,startsAt:"08:00",endsAt:"08:50",room:"",effectiveFrom:setup.terms[0]?.startsOn??"",effectiveTo:setup.terms[0]?.endsOn??""});
  const [plan,setPlan]=useState({lessonPlanId:submittedPlans[0]?.id??"",decision:"reviewed" as "reviewed"|"returned",note:""});
  const [assessment,setAssessment]=useState({id:submittedAssessments[0]?.id??"",decision:"approved" as "approved"|"rejected",note:"",publishId:approvedAssessments[0]?.id??""});
  const [report,setReport]=useState({studentId:workspace.learners[0]?.id??"",termId:term,comment:"",publishId:draftReports[0]?.id??""});
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await onRefresh();setMessage(success);}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
  function curriculum(e:FormEvent){e.preventDefault();void run(async()=>{await saveCurriculumOutcome(outcome);setOutcome(current=>({...current,code:"",titleEn:"",titleFr:"",description:""}));},"Curriculum outcome saved.");}
  function assign(e:FormEvent){e.preventDefault();void run(()=>assignTeacher({...ownership,idempotencyKey:key("teaching")}),"Teaching ownership recorded.");}
  function schedule(e:FormEvent){e.preventDefault();void run(()=>scheduleTimetableEntry({...period,idempotencyKey:key("period")}),"Timetable period scheduled.");}
  function reviewPlan(e:FormEvent){e.preventDefault();void run(()=>reviewLessonPlan({...plan,idempotencyKey:key("lesson-review")}),`Lesson plan ${plan.decision}.`);}
  function reviewAssessmentForm(e:FormEvent){e.preventDefault();void run(()=>reviewAssessment({assessmentId:assessment.id,decision:assessment.decision,note:assessment.note,idempotencyKey:key("assessment-review")}),`Assessment ${assessment.decision}.`);}
  function generate(e:FormEvent){e.preventDefault();void run(()=>generateReportCard(report.studentId,report.termId,report.comment,key("report")),"Report draft generated from published evidence.");}
  return <div className="content role-workspace academic-journey-workspace">
    <section className="page-intro"><div><span>ACADEMIC CONTROL</span><h2>Build the structure, enable teaching, then verify the evidence.</h2><p>This workspace is for academic leadership and review. Teachers create classroom evidence in DREEM Teacher; this side controls ownership, scheduling, moderation and publication.</p></div><div className="care-assurance"><ShieldCheck/><span><strong>Separation of duties</strong><small>Creation, review and publication remain distinguishable.</small></span></div></section>
    <div className="metrics"><Metric label="Curriculum outcomes" value={academics.curriculumOutcomes.length} note="Standards registered"/><Metric label="Teaching owners" value={academics.assignments.filter(x=>x.status==="active").length} note="Active assignments"/><Metric label="Review queue" value={submittedPlans.length+submittedAssessments.length} note="Plans + assessments" tone="amber"/><Metric label="Published reports" value={academics.reportCards.filter(x=>x.status==="published").length} note="Official learner evidence" tone="violet"/></div>
    {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
    {missing.length?<div className="form-status error">Academic setup is incomplete: add {missing.join(", ")} first.<button type="button" onClick={onOpenStudio}>Open School settings</button></div>:null}
    <section className="panel lifecycle-panel"><div className="panel-title"><BookCheck/><div><span>ACADEMIC LIFECYCLE</span><h3>Curriculum → owner → timetable → lesson evidence → assessment review → report</h3></div></div><div className="lifecycle-rail"><span><b>1</b>Define outcomes</span><span><b>2</b>Assign teaching</span><span><b>3</b>Schedule periods</span><span><b>4</b>Review lesson plans</span><span><b>5</b>Moderate assessments</span><span><b>6</b>Publish reports</span></div></section>

    <div className="academic-flow-grid">
      <Stage n="1" icon={<BookCheck/>} title="Curriculum outcomes" owner="Academic leadership" note="Define what must be learned before assigning delivery."><form className="settings-form" onSubmit={curriculum}><div className="form-grid"><Pick label="Academic year" value={outcome.academicYearId} set={v=>setOutcome({...outcome,academicYearId:v})} rows={setup.academicYears}/><Pick label="Class" value={outcome.classId} set={v=>setOutcome({...outcome,classId:v})} rows={setup.classes}/><Pick label="Subject" value={outcome.subjectId} set={v=>setOutcome({...outcome,subjectId:v})} rows={setup.subjects}/><label>Outcome code<input required value={outcome.code} onChange={e=>setOutcome({...outcome,code:e.target.value})} placeholder="ENG-READ-01"/></label><label>English objective<input required value={outcome.titleEn} onChange={e=>setOutcome({...outcome,titleEn:e.target.value})}/></label><label>Objectif français<input value={outcome.titleFr} onChange={e=>setOutcome({...outcome,titleFr:e.target.value})}/></label></div><label>Competency / local adaptation<textarea rows={3} value={outcome.description} onChange={e=>setOutcome({...outcome,description:e.target.value})}/></label><button className="primary" disabled={busy||missing.length>0}>Save curriculum outcome</button></form><div className="stage-register"><strong>{academics.curriculumOutcomes.length}</strong><span>curriculum outcome(s) registered</span></div></Stage>

      <Stage n="2" icon={<UserRoundCheck/>} title="Teaching ownership" owner="Academic leadership" note="Attach a named teacher to the class, subject and term."><form className="settings-form" onSubmit={assign}><div className="form-grid"><Pick label="Academic year" value={ownership.academicYearId} set={v=>setOwnership({...ownership,academicYearId:v})} rows={setup.academicYears}/><Pick label="Term" value={ownership.termId} set={v=>setOwnership({...ownership,termId:v})} rows={setup.terms}/><Pick label="Class" value={ownership.classId} set={v=>setOwnership({...ownership,classId:v})} rows={setup.classes}/><Pick label="Subject" value={ownership.subjectId} set={v=>setOwnership({...ownership,subjectId:v})} rows={setup.subjects}/><label>Teacher<select value={ownership.teacherUserId} onChange={e=>setOwnership({...ownership,teacherUserId:e.target.value})}><option value="">Choose teacher</option>{teachers.map(x=><option key={x.id} value={x.profileId}>{x.name}</option>)}</select></label><label>Weekly periods<input type="number" min="1" max="30" value={ownership.weeklyPeriods} onChange={e=>setOwnership({...ownership,weeklyPeriods:Number(e.target.value)})}/></label></div><button className="primary" disabled={busy||missing.length>0}>Record teaching assignment</button></form></Stage>

      <Stage n="3" icon={<CalendarClock/>} title="Timetable" owner="Academic leadership" note="Schedule only after teaching ownership exists."><form className="settings-form" onSubmit={schedule}><label>Teaching assignment<select value={period.assignmentId} onChange={e=>setPeriod({...period,assignmentId:e.target.value})}><option value="">Choose assignment</option>{academics.assignments.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.className} · {x.subjectName} · {x.teacherName}</option>)}</select></label><div className="form-grid"><label>Weekday<select value={period.weekday} onChange={e=>setPeriod({...period,weekday:Number(e.target.value)})}>{days.map((day,i)=><option value={i+1} key={day}>{day}</option>)}</select></label><label>Room<input value={period.room} onChange={e=>setPeriod({...period,room:e.target.value})}/></label><label>Starts<input type="time" value={period.startsAt} onChange={e=>setPeriod({...period,startsAt:e.target.value})}/></label><label>Ends<input type="time" value={period.endsAt} onChange={e=>setPeriod({...period,endsAt:e.target.value})}/></label><label>Effective from<input type="date" value={period.effectiveFrom} onChange={e=>setPeriod({...period,effectiveFrom:e.target.value})}/></label><label>Effective to<input type="date" value={period.effectiveTo} onChange={e=>setPeriod({...period,effectiveTo:e.target.value})}/></label></div><button className="primary" disabled={busy||!academics.assignments.some(x=>x.status==="active")}>Schedule period</button></form><div className="compact-register">{academics.timetable.slice(0,6).map(x=><span key={x.id}><strong>{days[x.weekday-1]} {x.startsAt}</strong>{x.className} · {x.subjectName}</span>)}</div></Stage>

      <Stage n="4" icon={<ClipboardCheck/>} title="Lesson-plan review" owner="Academic reviewer" note="Teachers submit plans from their app; reviewers verify objectives before delivery evidence is accepted."><form className="settings-form" onSubmit={reviewPlan}><label>Submitted lesson plan<select value={plan.lessonPlanId} onChange={e=>setPlan({...plan,lessonPlanId:e.target.value})}><option value="">Choose submitted plan</option>{submittedPlans.map(x=><option key={x.id} value={x.id}>{x.lessonDate} · {x.className} · {x.subjectName} · {x.title}</option>)}</select></label><div className="form-grid"><label>Decision<select value={plan.decision} onChange={e=>setPlan({...plan,decision:e.target.value as typeof plan.decision})}><option value="reviewed">Reviewed and ready</option><option value="returned">Return for correction</option></select></label><label>Review evidence<input value={plan.note} onChange={e=>setPlan({...plan,note:e.target.value})}/></label></div><button className="primary" disabled={busy||!submittedPlans.length}>Record review</button></form></Stage>

      <Stage n="5" icon={<ClipboardCheck/>} title="Assessment moderation" owner="Independent reviewer" note="Review submitted evidence, then publish only approved assessment evidence."><form className="settings-form" onSubmit={reviewAssessmentForm}><label>Submitted assessment<select value={assessment.id} onChange={e=>setAssessment({...assessment,id:e.target.value})}><option value="">Choose submitted assessment</option>{submittedAssessments.map(x=><option key={x.id} value={x.id}>{x.title} · {x.className} · {x.marksCount} marks</option>)}</select></label><div className="form-grid"><label>Decision<select value={assessment.decision} onChange={e=>setAssessment({...assessment,decision:e.target.value as typeof assessment.decision})}><option value="approved">Approve evidence</option><option value="rejected">Return for correction</option></select></label><label>Review evidence<input value={assessment.note} onChange={e=>setAssessment({...assessment,note:e.target.value})}/></label></div><button className="primary" disabled={busy||!submittedAssessments.length}>Record independent review</button></form><div className="publish-line"><select aria-label="Approved assessment" value={assessment.publishId} onChange={e=>setAssessment({...assessment,publishId:e.target.value})}><option value="">Approved assessment</option>{approvedAssessments.map(x=><option key={x.id} value={x.id}>{x.title} · {x.className}</option>)}</select><button disabled={!assessment.publishId} onClick={()=>void run(()=>publishAssessment(assessment.publishId,key("assessment-publish")),"Assessment published.")}>Publish approved assessment</button></div></Stage>

      <Stage n="6" icon={<FileBadge2/>} title="Reports" owner="Authorized publisher" note="Generate from published evidence, then publish the verified learner snapshot."><form className="settings-form" onSubmit={generate}><div className="form-grid"><Pick label="Learner" value={report.studentId} set={v=>setReport({...report,studentId:v})} rows={workspace.learners.map(x=>({id:x.id,name:`${x.name} · ${x.className}`}))}/><Pick label="Term" value={report.termId} set={v=>setReport({...report,termId:v})} rows={setup.terms}/></div><label>Report comment<input value={report.comment} onChange={e=>setReport({...report,comment:e.target.value})}/></label><button className="primary" disabled={busy||!workspace.learners.length||!setup.terms.length}>Generate report draft</button></form><div className="publish-line"><select aria-label="Draft report card" value={report.publishId} onChange={e=>setReport({...report,publishId:e.target.value})}><option value="">Draft report card</option>{draftReports.map(x=><option key={x.id} value={x.id}>{x.studentName} · {x.termName} · revision {x.revision}</option>)}</select><button disabled={!report.publishId} onClick={()=>void run(()=>publishReportCard(report.publishId,key("report-publish")),"Report card published.")}>Publish verified report</button></div></Stage>
    </div>
  </div>;
}

function Stage({n,icon,title,owner,note,children}:{n:string;icon:ReactNode;title:string;owner:string;note:string;children:ReactNode}){return <section className="panel academic-stage"><div className="academic-stage-head"><b>{n}</b>{icon}<div><span>{owner}</span><h3>{title}</h3><p>{note}</p></div></div>{children}</section>;}
function Pick({label,value,set,rows}:{label:string;value:string;set:(value:string)=>void;rows:{id:string;name:string}[]}){return <label>{label}<select value={value} onChange={e=>set(e.target.value)} disabled={!rows.length}><option value="">{rows.length?`Choose ${label.toLowerCase()}`:`No ${label.toLowerCase()} configured`}</option>{rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;}
function Metric({label,value,note,tone=""}:{label:string;value:number;note:string;tone?:string}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
