import { AlertTriangle, Banknote, CircleDollarSign, QrCode, ReceiptText, ShieldCheck, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { FinanceSummary, LearnerSummary, PaymentCommand } from "../domain/types";
import { createIdempotencyKey, paymentMethodForRail } from "../domain/rules";
import { createPaymentIntent, openCashierSession, recordPayment } from "../lib/repository";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";
export default function BursarCollectionWorkspace({finance,learners,onRecorded}:{finance:FinanceSummary;learners:LearnerSummary[];onRecorded:()=>Promise<void>}){
  const [open,setOpen]=useState(false);
  return <div className="content role-workspace bursar-collection">
    <section className="page-intro"><div><span>COLLECTION DESK</span><h2>Collect against a learner account, then hand cash into the control cycle.</h2><p>Every payment begins with a unique learner payment identity. Cash is not considered settled until the till is closed, independently reviewed, deposited and confirmed.</p></div><button className="primary" onClick={()=>setOpen(true)}><CircleDollarSign/>Collect payment</button></section>
    <div className="metrics"><Metric label="Open fee balance" value={money(finance.expectedToday)} detail="Across learner accounts"/><Metric label="Cash in custody" value={money(finance.cashAwaitingDeposit)} detail="Must pass closure and deposit" tone="amber"/><Metric label="Digital confirmed" value={money(finance.digitalConfirmed)} detail="Provider references captured"/><Metric label="Open exceptions" value={String(finance.openExceptions)} detail={money(finance.openExceptionValue)} tone={finance.openExceptions?"red":"green"}/></div>
    <section className="panel lifecycle-panel"><div className="panel-title"><ShieldCheck/><div><span>BURSAR MONEY CYCLE</span><h3>Identify account → collect → receipt → close till → deposit</h3></div></div><div className="lifecycle-rail"><span><b>1</b>Select learner account</span><span><b>2</b>Create payment reference</span><span><b>3</b>Record verified payment</span><span><b>4</b>Submit physical cash count</span><span><b>5</b>Deposit approved cash</span></div><p className="lifecycle-note">Independent closure review and final settlement confirmation belong to the Accountant / authorized reviewer. Those controls appear in the Finance control desk below.</p></section>
    {finance.openExceptions>0?<section className="panel"><div className="panel-title"><AlertTriangle/><div><span>EXCEPTIONS</span><h3>{finance.openExceptions} item(s) need independent review</h3></div></div><p>Do not erase or overwrite the payment trail. The reviewer resolves evidence and settlement differences through the controlled finance workflow.</p></section>:null}
    {open?<CashierDialog learners={learners} onRecorded={async()=>{await onRecorded();setOpen(false);}} onClose={()=>setOpen(false)}/>:null}
  </div>;
}
function Metric({label,value,detail,tone=""}:{label:string;value:string;detail:string;tone?:string}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;}
function CashierDialog({learners,onRecorded,onClose}:{learners:LearnerSummary[];onRecorded:()=>Promise<void>;onClose:()=>void}){
  const [status,setStatus]=useState(""),[failed,setFailed]=useState(false),[sessionId,setSessionId]=useState(""),[intent,setIntent]=useState<{id:string;reference:string;rail:PaymentCommand["railCode"]}|null>(null),[busy,setBusy]=useState(false);
  const eligible=learners.filter(item=>item.feeAccountId&&Number(item.feeBalance)>0);
  async function openSession(){const session=await openCashierSession(0);setSessionId(session.id);}
  async function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setStatus("Creating payment reference…");setFailed(false);try{const values=new FormData(event.currentTarget),learner=eligible.find(item=>item.id===String(values.get("studentId")));if(!learner?.feeAccountId)throw new Error("Choose a learner with an open fee account.");const rail=String(values.get("railCode")) as PaymentCommand["railCode"];const created=await createPaymentIntent({studentId:learner.id,feeAccountId:learner.feeAccountId,amountExpected:Number(values.get("amount")),payerName:String(values.get("payerName")||""),payerPhone:String(values.get("payerPhone")||""),allowedRails:[rail],idempotencyKey:createIdempotencyKey("payment-intent")});setIntent({id:created.intentId,reference:created.paymentReference,rail});if(rail==="cash"&&!sessionId)await openSession();setStatus(`Reference ${created.paymentReference} is ready. Confirm the actual payment below.`);}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"Payment reference could not be created.");}finally{setBusy(false);}}
  async function submitPayment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!intent)return;setBusy(true);setStatus("Recording verified payment…");setFailed(false);try{const values=new FormData(event.currentTarget),method=paymentMethodForRail(intent.rail);const receipt=await recordPayment({paymentIntentId:intent.id,cashierSessionId:method==="cash"?sessionId||undefined:undefined,method,railCode:intent.rail,amount:Number(values.get("amount")),externalReference:String(values.get("externalReference")||""),idempotencyKey:createIdempotencyKey("verified-payment")});setStatus(`Receipt ${receipt.receiptNumber} recorded and the learner account was updated.`);await onRecorded();}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"Payment could not be recorded.");}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={onClose} aria-label="Close"><X/></button><span className="kicker">VERIFIED COLLECTION</span><h2>Collect against a learner account</h2><p>Create the payment identity first, then record the money actually received. Cash stays in institutional custody until the later control stages are completed.</p>{eligible.length===0?<div className="form-status error"><AlertTriangle/>No learner currently has an open fee account.</div>:<form onSubmit={prepare}><div className="form-grid"><label>Learner<select name="studentId" required>{eligible.map(item=><option key={item.id} value={item.id}>{item.name} · balance {money(item.feeBalance??0)}</option>)}</select></label><label>Payer name<input name="payerName" required placeholder="Parent, guardian or sponsor"/></label><label>Payer phone<input name="payerPhone" inputMode="tel"/></label><label>Expected amount<input name="amount" type="number" min="1" step="1" required/></label><label>Payment method<select name="railCode" defaultValue="cash"><option value="cash">Cash desk</option><option value="wave">Wave</option><option value="mtn_momo">MTN MoMo</option><option value="orange_money">Orange Money</option><option value="bank">Bank / merchant account</option><option value="card">Card</option><option value="cheque">Cheque</option></select></label></div><button className="primary" type="submit" disabled={busy}><QrCode/>{busy?"Preparing…":"Create payment reference"}</button></form>}{status?<div className={`form-status ${failed?"error":"success"}`}>{failed?<AlertTriangle/>:<ReceiptText/>}{status}</div>:null}{intent?<form onSubmit={submitPayment}><div className="form-grid"><label>Payment reference<input value={intent.reference} readOnly/></label><label>Amount actually received<input name="amount" type="number" min="1" step="1" required/></label><label>Provider / bank reference<input name="externalReference" placeholder={intent.rail==="cash"?"Optional for cash":"Required provider reference"} required={intent.rail!=="cash"}/></label></div><button className="primary" disabled={busy}><Banknote/>{busy?"Recording…":"Record payment and issue receipt"}</button></form>:null}</section></div>;
}
