import { Megaphone, MessageSquareMore, ShieldCheck } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import type { CommunitySignal, Role } from "../domain/types";
import type { AuthorityScope } from "../lib/authority";
import { canAuthority } from "../lib/access";
import { loadAnnouncementReviewQueue, loadAnnouncements, publishAnnouncement, reviewAnnouncement, type AnnouncementAudience, type AnnouncementCategory, type AnnouncementPriority, type AnnouncementReviewItem, type SchoolAnnouncement } from "../lib/announcements";
import NotificationDeliveryPanel from "./NotificationDeliveryPanel";
import { SignalsView } from "./Views";

function errorText(reason:unknown){return reason instanceof Error?reason.message:"This message could not be completed.";}
type CommsViewer={role:Role;authorityScopes?:AuthorityScope[]};
function categoriesFor(viewer:CommsViewer):AnnouncementCategory[]{if(canAuthority(viewer,"institutional_leadership"))return["general","administrative","academic","event","transport","finance","emergency"];const categories:AnnouncementCategory[]=["general"];if(canAuthority(viewer,"admissions_decision")||canAuthority(viewer,"staff_management"))categories.push("administrative","event");if(canAuthority(viewer,"academics_approval"))categories.push("academic","event");if(canAuthority(viewer,"transport_management"))categories.push("transport");if(canAuthority(viewer,"finance_approval"))categories.push("finance");return Array.from(new Set(categories));}
function audiencesFor(viewer:CommsViewer):AnnouncementAudience[]{if(canAuthority(viewer,"institutional_leadership")||canAuthority(viewer,"academics_approval")||canAuthority(viewer,"admissions_decision"))return["all","staff","families","students"];if(canAuthority(viewer,"transport_management")||canAuthority(viewer,"communications_publish"))return["staff","families","students"];return[];}

export default function CommunicationsWorkspace({role,authorityScopes,signals,onFeedback,onStatus}:{role:Role;authorityScopes?:AuthorityScope[];signals:CommunitySignal[];onFeedback:()=>void;onStatus:(id:string,status:CommunitySignal["status"])=>Promise<void>}){
 const viewer={role,authorityScopes};
 const[announcements,setAnnouncements]=useState<SchoolAnnouncement[]|null>(null),[reviewQueue,setReviewQueue]=useState<AnnouncementReviewItem[]>([]),[announcementError,setAnnouncementError]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const canPublish=canAuthority(viewer,"communications_publish")||canAuthority(viewer,"communications_approve"),canApprove=canAuthority(viewer,"communications_approve")||canAuthority(viewer,"institutional_leadership"),allowedCategories=categoriesFor(viewer),allowedAudiences=audiencesFor(viewer);
 async function refresh(){try{setAnnouncements(await loadAnnouncements());setAnnouncementError("");if(canApprove)setReviewQueue(await loadAnnouncementReviewQueue());}catch(reason){setAnnouncements([]);setAnnouncementError(errorText(reason));}}
 useEffect(()=>{let active=true;Promise.all([loadAnnouncements(),canApprove?loadAnnouncementReviewQueue():Promise.resolve([])]).then(([items,pending])=>{if(active){setAnnouncements(items);setReviewQueue(pending);}}).catch(reason=>{if(active){setAnnouncements([]);setAnnouncementError(errorText(reason));}});return()=>{active=false;};},[canApprove]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),expires=String(data.get("expiresAt")||"");setBusy(true);setAnnouncementError("");setMessage("");try{const result=await publishAnnouncement({title:String(data.get("title")||""),body:String(data.get("body")||""),audience:String(data.get("audience")||allowedAudiences[0]||"staff") as AnnouncementAudience,priority:String(data.get("priority")||"normal") as AnnouncementPriority,category:String(data.get("category")||allowedCategories[0]||"general") as AnnouncementCategory,expiresAt:expires?new Date(`${expires}T23:59:59`).toISOString():undefined});form.reset();setMessage(result.status==="pending_approval"?"Message sent for approval.":"Message published.");await refresh();}catch(reason){setAnnouncementError(errorText(reason));}finally{setBusy(false);}}
 async function decide(id:string,decision:"approve"|"reject"){setBusy(true);setAnnouncementError("");setMessage("");try{await reviewAnnouncement(id,decision);setMessage(decision==="approve"?"Message approved and published.":"Message rejected.");await refresh();}catch(reason){setAnnouncementError(errorText(reason));}finally{setBusy(false);}}
 return <div className="communications-workspace"><div className="content role-workspace">
  <section className="role-hero"><div><span className="eyebrow">MESSAGES · TODAY</span><h2>{reviewQueue.length?`${reviewQueue.length} message${reviewQueue.length===1?"":"s"} waiting for approval`:"School communication"}</h2><p>Announcements, updates and feedback in one place. DREEM keeps the right audience and review rules behind the scenes.</p></div><div className="role-hero-status"><span className="status-pill info"><ShieldCheck size={14}/>School messaging</span></div></section>
  {announcementError?<div className="form-status error" role="alert">{announcementError}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
  <div className="communications-layout"><main className="message-feed"><header className="object-header"><div><span>ANNOUNCEMENTS</span><h3>{announcements===null?"Loading messages…":`${announcements.length} current message${announcements.length===1?"":"s"}`}</h3></div><Megaphone/></header>{announcements?.map(item=><article className={`message-card priority-${item.priority}`} key={item.id}><header><div><strong>{item.title}</strong><small>{item.audience==="all"?"Whole school":item.audience} · {item.category}</small></div><span className="status-pill">{item.priority}</span></header><p>{item.body}</p><footer>{item.publishedAt?new Date(item.publishedAt).toLocaleString():"Not yet published"}{item.expiresAt?` · until ${new Date(item.expiresAt).toLocaleDateString()}`:""}</footer></article>)}{announcements!==null&&announcements.length===0?<p className="empty-copy">No current school message.</p>:null}</main>
  <aside className="message-compose-column">{canApprove&&reviewQueue.length>0?<section className="review-stack"><span>WAITING FOR APPROVAL</span>{reviewQueue.map(item=><article key={item.id}><strong>{item.title}</strong><small>{item.audience} · {item.priority}</small><p>{item.body}</p><div className="row-actions"><button className="primary" disabled={busy} onClick={()=>void decide(item.id,"approve")}>Approve</button><button disabled={busy} onClick={()=>void decide(item.id,"reject")}>Reject</button></div></article>)}</section>:null}
  {canPublish?<section className="message-composer"><header><span>NEW MESSAGE</span><h3>Write once, send to the right people</h3></header><form className="settings-form" onSubmit={submit}><label>Title<input name="title" required minLength={3} maxLength={160}/></label><label>Message<textarea name="body" rows={6} required minLength={3} maxLength={4000}/></label><div className="form-grid"><label>Audience<select name="audience" defaultValue={allowedAudiences[0]}>{allowedAudiences.map(item=><option key={item} value={item}>{item==="all"?"Whole school":item}</option>)}</select></label><label>Category<select name="category" defaultValue={allowedCategories[0]}>{allowedCategories.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label><label>Priority<select name="priority" defaultValue="normal"><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label><label>End date (optional)<input name="expiresAt" type="date"/></label></div><button className="primary" disabled={busy} type="submit"><Megaphone/>{busy?"Sending…":"Send message"}</button></form></section>:null}</aside></div>
  <NotificationDeliveryPanel role={role} authorityScopes={authorityScopes}/><section className="feedback-strip"><div><MessageSquareMore/><span><strong>Community feedback</strong><small>Questions and concerns stay separate from school announcements.</small></span></div><button className="primary" onClick={onFeedback}>Give feedback</button></section>
 </div><SignalsView signals={signals} onFeedback={onFeedback} onStatus={onStatus}/></div>;
}
