import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, IdCard, Printer, RefreshCw, ShieldX } from "lucide-react";
import { createIdempotencyKey } from "../domain/rules";
import { loadLearnerIdentity, revokeLearnerCredential, type LearnerIdentityProfile } from "../lib/identity";
import { issueStudentCredential, type WorkspaceData } from "../lib/repository";
import { canAuthority } from "../lib/access";
import { makeQrMatrix } from "../lib/qr";
import PickupAuthorizationStudio from "./PickupAuthorizationStudio";
import "./CredentialCardStudio.css";

function nextYear(){const value=new Date();value.setFullYear(value.getFullYear()+1);return value.toISOString().slice(0,10);}
function readableError(reason:unknown){if(reason instanceof Error&&reason.message)return reason.message;return "The learner card could not be updated.";}
function QrCode({value}:{value:string}){const matrix=useMemo(()=>makeQrMatrix(value),[value]),quiet=4,size=matrix.length+quiet*2;return <svg className="credential-qr" viewBox={`0 0 ${size} ${size}`} role="img" aria-label="Learner card QR code" shapeRendering="crispEdges"><rect width={size} height={size} fill="white"/>{matrix.flatMap((row,y)=>row.map((dark,x)=>dark?<rect key={`${x}-${y}`} x={x+quiet} y={y+quiet} width="1" height="1" fill="black"/>:null))}</svg>;}

export default function CredentialCardStudio({workspace,onRefresh}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>}){
 const allowed=canAuthority(workspace.viewer,"admissions_intake")||canAuthority(workspace.viewer,"admissions_decision")||canAuthority(workspace.viewer,"school_configuration");
 const[studentId,setStudentId]=useState(workspace.learners[0]?.id??""),[validUntil,setValidUntil]=useState(nextYear()),[identity,setIdentity]=useState<LearnerIdentityProfile|null>(null),[verificationToken,setVerificationToken]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[revokeReason,setRevokeReason]=useState("Lost or replaced card");
 const load=useCallback(async()=>{if(!studentId){setIdentity(null);return;}setError("");try{setIdentity(await loadLearnerIdentity(studentId));}catch(reason){setError(readableError(reason));}},[studentId]);
 useEffect(()=>{setVerificationToken("");void load();},[load]);
 async function issue(){if(!studentId)return;const hadCredential=identity?.credential?.status==="active";setBusy(true);setError("");setMessage("");try{const result=await issueStudentCredential(studentId,validUntil,createIdempotencyKey("credential-card"));setVerificationToken(result.verificationToken);await load();await onRefresh();setMessage(hadCredential?"New card issued. The previous card no longer works.":"Learner card issued.");}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 async function revoke(){if(!studentId)return;setBusy(true);setError("");setMessage("");try{const changed=await revokeLearnerCredential(studentId,revokeReason);setVerificationToken("");await load();await onRefresh();setMessage(changed?"Card cancelled.":"There is no active card to cancel.");}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 if(!allowed)return <div className="content"><div className="form-status error">You do not have access to manage learner cards.</div></div>;
 if(!workspace.learners.length)return <div className="content"><section className="role-hero"><div><span className="eyebrow">LEARNER CARDS</span><h2>Create a learner first</h2><p>Once a learner is enrolled, their school card can be issued here.</p></div></section></div>;
 const primaryGuardian=identity?.guardians.find(guardian=>guardian.isPrimary)??identity?.guardians[0],isActive=identity?.credential?.status==="active";
 return <div className="content credential-studio role-workspace">
  <section className="role-hero credential-card-controls"><div><span className="eyebrow">LEARNER CARDS</span><h2>Issue, print and replace school cards</h2><p>Choose a learner and manage the card without exposing the technical security details behind it.</p></div></section>
  {error&&<div className="form-status error credential-card-controls">{error}</div>}{message&&<div className="form-status success credential-card-controls"><BadgeCheck/>{message}</div>}
  <section className="credential-control-bar"><label>Learner<select value={studentId} onChange={event=>setStudentId(event.target.value)}>{workspace.learners.map(learner=><option value={learner.id} key={learner.id}>{learner.name} · {learner.matricule}</option>)}</select></label><label>Valid until<input type="date" value={validUntil} min={new Date().toISOString().slice(0,10)} onChange={event=>setValidUntil(event.target.value)}/></label><button className="primary" type="button" disabled={busy} onClick={()=>void issue()}><RefreshCw/>{isActive?"Replace card":"Issue card"}</button>{isActive?<details className="card-danger-menu"><summary>Card options</summary><label>Why are you cancelling it?<input value={revokeReason} onChange={event=>setRevokeReason(event.target.value)}/></label><button className="danger" type="button" disabled={busy} onClick={()=>void revoke()}><ShieldX/>Cancel card</button></details>:null}</section>
  {identity?<section className="credential-card-sheet"><article className="credential-card" aria-label={`${identity.name} school identity card`}><header><div className="credential-school-mark">{workspace.brand.logoUrl?<img src={workspace.brand.logoUrl} alt=""/>:workspace.brand.shortName}</div><div><strong>{workspace.brand.name}</strong><small>{workspace.brand.motto}</small></div><IdCard/></header><div className="credential-card-body"><div className="credential-photo">{identity.photoUrl?<img src={identity.photoUrl} alt={`${identity.name} identity`}/>:<span>{identity.name.split(" ").filter(Boolean).map(part=>part[0]).join("").slice(0,3)}</span>}</div><div className="credential-person"><small>STUDENT / ÉLÈVE</small><h3>{identity.name}</h3><p>{identity.matricule}</p><dl><div><dt>Class</dt><dd>{identity.className}</dd></div><div><dt>Card</dt><dd>{identity.credential?.cardNumber??"Not issued"}</dd></div><div><dt>Valid until</dt><dd>{identity.credential?.validUntil??"—"}</dd></div></dl></div><div className="credential-verification">{verificationToken?<QrCode value={verificationToken}/>:<div className="credential-qr-placeholder"><IdCard/><small>{isActive?"Replace the card to print a new QR":"Issue the card to create its QR"}</small></div>}<strong>{identity.credential?.status??"not issued"}</strong></div></div><footer><span>{primaryGuardian?`Guardian: ${primaryGuardian.name} · ${primaryGuardian.relationship}`:"Guardian details are on the learner record"}</span><small>Use this card only for school identification and approved pickup checks.</small></footer></article><div className="credential-card-controls credential-print-actions"><button type="button" disabled={!verificationToken} onClick={()=>window.print()}><Printer/>Print card</button></div></section>:null}
  <PickupAuthorizationStudio workspace={workspace}/>
 </div>;
}
