import { BusFront, Clock3, MapPinned, UsersRound, Wifi, WifiOff } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { type WorkspaceData } from "../lib/repository";
import { prepareDriverOfflineContext, progressTransportTripResilient, replayDriverOffline } from "../lib/driverOffline";

function errorText(reason:unknown){return reason instanceof Error?reason.message:reason&&typeof reason==="object"&&"message" in reason&&typeof reason.message==="string"?reason.message:"The journey update could not be recorded.";}

export default function DriverWorkspace({workspace,onRefresh}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>}){
 const driver=workspace.transport.drivers.find(item=>item.userId===workspace.viewer.id);
 const trips=driver?workspace.transport.trips.filter(item=>item.driverId===driver.id).sort((a,b)=>b.serviceDate.localeCompare(a.serviceDate)):[];
 const activeTrips=trips.filter(item=>!["completed","cancelled"].includes(item.status));
 const [tripId,setTripId]=useState(activeTrips[0]?.id??trips[0]?.id??"");
 const [online,setOnline]=useState(typeof navigator==="undefined"?true:navigator.onLine),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const trip=trips.find(item=>item.id===tripId),route=workspace.transport.routes.find(item=>item.id===trip?.routeId);
 const assignments=useMemo(()=>trip?workspace.transport.assignments.filter(item=>item.routeId===trip.routeId&&item.status==="active"):[],[workspace.transport.assignments,trip]);
 const stops=route?.stops??[];
 async function record(eventType:string,studentId?:string,stopId?:string,note?:string){if(!trip)return;setBusy(true);setError("");setMessage("");try{const result=await progressTransportTripResilient({tripId:trip.id,eventType,studentId,stopId,note,idempotencyKey:`driver-trip:${crypto.randomUUID()}`},workspace.viewer);if(result.queued)setMessage("Saved on this phone. DREEM will sync it automatically when connection returns.");else{setMessage("Recorded. Transport control now has this update.");await onRefresh();}}catch(reason){setError(errorText(reason));}finally{setBusy(false);}}
 useEffect(()=>{let active=true;const connect=async()=>{setOnline(true);try{const result=await replayDriverOffline(workspace.viewer);if(active&&result.synced){setMessage(`${result.synced} saved update${result.synced===1?"":"s"} synced automatically.`);await onRefresh();}if(active&&result.tampered)setError(`${result.tampered} saved update failed its safety check and was not sent.`);}catch(reason){if(active)setError(errorText(reason));}};const disconnect=()=>setOnline(false);if(navigator.onLine)prepareDriverOfflineContext().catch(()=>{});window.addEventListener("online",connect);window.addEventListener("offline",disconnect);return()=>{active=false;window.removeEventListener("online",connect);window.removeEventListener("offline",disconnect);};},[workspace.viewer,onRefresh]);
 if(!driver)return <div className="content role-workspace"><section className="page-intro"><div><span>DREEM DRIVER</span><h2>No journey is available yet.</h2><p>Ask Transport Control to activate your driver profile and assign today’s vehicle and route.</p></div></section></div>;
 return <div className="content role-workspace driver-workspace">
  <section className="page-intro"><div><span>DRIVER · TODAY</span><h2>{activeTrips[0]?`${activeTrips[0].routeName} · ${activeTrips[0].direction}`:"Waiting for today’s trip"}</h2><p>{trip?`${trip.vehicleCode} · ${trip.assignedStudents} learner${trip.assignedStudents===1?"":"s"} expected${trip.scheduledDeparture?` · depart ${trip.scheduledDeparture}`:""}`:"Transport Control will send your assigned trip here."}</p></div><div className="care-assurance">{online?<Wifi/>:<WifiOff/>}<span><strong>{online?"Connected":"Offline · still usable"}</strong><small>{online?"Updates reach school automatically":"Your updates are saved and sync automatically"}</small></span></div></section>
  {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
  {trips.length>1?<section className="panel"><label>Journey<select value={tripId} onChange={event=>setTripId(event.target.value)}>{trips.map(item=><option key={item.id} value={item.id}>{item.serviceDate} · {item.routeName} · {item.direction}</option>)}</select></label></section>:null}
  <div className="teacher-action-grid"><article className="role-action primary-action"><BusFront/><span>TRIP</span><h3>{trip?.status.replaceAll("_"," ")??"Not dispatched"}</h3><p>{trip?.routeName??"No route assigned"}</p></article><article className="role-action"><UsersRound/><span>LEARNERS</span><h3>{assignments.length} on this route</h3><p>Tap a learner below when they board or leave the vehicle.</p></article><article className="role-action"><Clock3/><span>SYNC</span><h3>{online?"Up to date":"Saving locally"}</h3><p>No manual synchronization is required.</p></article></div>
  {trip?<><section className="panel"><div className="panel-title"><BusFront/><div><span>NEXT ACTION</span><h3>Run the journey without forms</h3></div></div><div className="gate-scan-actions"><button className="primary" disabled={busy} onClick={()=>void record("departed")}>Start / depart</button><button disabled={busy} onClick={()=>void record("delay_reported",undefined,undefined,"Driver reported delay")}>Report delay</button><button disabled={busy} onClick={()=>void record("completed")}>Finish journey</button></div></section>
  <section className="panel"><div className="panel-title"><MapPinned/><div><span>STOPS</span><h3>Where are you now?</h3></div></div><div className="command-queue-grid">{stops.map(stop=><article className="command-queue normal" key={stop.id}><div><span>STOP {stop.order}</span><h3>{stop.name}</h3><button disabled={busy} onClick={()=>void record("stop_arrived",undefined,stop.id)}>Arrived here</button></div></article>)}</div></section>
  <section className="panel"><div className="panel-title"><UsersRound/><div><span>LEARNERS</span><h3>Boarding and drop-off</h3></div></div><div className="command-queue-grid">{assignments.map(item=><article className="command-queue normal" key={item.studentId}><div><span>{item.pickupStopName} → {item.dropoffStopName}</span><h3>{item.studentName}</h3><div className="gate-scan-actions"><button className="primary" disabled={busy} onClick={()=>void record("student_boarded",item.studentId)}>Boarded</button><button disabled={busy} onClick={()=>void record("student_alighted",item.studentId)}>Dropped off</button></div></div></article>)}</div></section></>:<section className="panel"><p>No trip is assigned. You do not need to configure anything here.</p></section>}
 </div>;
}
