import { BookOpenCheck, BusFront, GraduationCap, IdCard, ReceiptText, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { WorkspaceData } from "../lib/repository";
import { loadLearnerFeeStatement, type LearnerFeeStatementRow } from "../lib/familyFinance";
import { loadPickupCircle, type PickupCircleMember } from "../lib/pickupCircle";

function messageFrom(reason: unknown) { return reason instanceof Error ? reason.message : reason && typeof reason === "object" && "message" in reason && typeof reason.message === "string" ? reason.message : "The family record could not be loaded."; }
const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";
const dateText=(value:string|undefined)=>value?new Date(value).toLocaleDateString():"—";

export default function FamilyLearningWorkspace({workspace}:{workspace:WorkspaceData}){
 const [selectedStudentId,setSelectedStudentId]=useState(workspace.learners[0]?.id??"");
 const [familyRecords,setFamilyRecords]=useState<{key:string;statement:LearnerFeeStatementRow[];pickupCircle:PickupCircleMember[]}>({key:"",statement:[],pickupCircle:[]}),[familyLoading,setFamilyLoading]=useState(false),[familyError,setFamilyError]=useState("");
 const learner=workspace.learners.find(item=>item.id===selectedStudentId)??workspace.learners[0],learnerId=learner?.id??"",learnerClass=learner?.className??"";
 const familyKey=JSON.stringify([workspace.viewer.id,learnerId]);
 const statement=familyRecords.key===familyKey?familyRecords.statement:[],pickupCircle=familyRecords.key===familyKey?familyRecords.pickupCircle:[];
 const assignments=useMemo(()=>workspace.academics.assignmentsForLearners.filter(item=>item.status==="published"&&(!learnerClass||item.className===learnerClass)),[workspace.academics.assignmentsForLearners,learnerClass]);
 const submissions=workspace.academics.assignmentSubmissions.filter(item=>item.studentId===learnerId),reportCards=workspace.academics.reportCards.filter(item=>item.studentId===learnerId&&item.status==="published");
 const transportAssignment=workspace.transport.assignments.find(item=>item.studentId===learnerId&&item.status==="active"),transportTrips=transportAssignment?workspace.transport.trips.filter(item=>item.routeId===transportAssignment.routeId&&item.status!=="cancelled").slice(0,3):[];
 const submittedAssignmentIds=new Set(submissions.filter(item=>item.status!=="needs_revision").map(item=>item.assignmentId)),due=assignments.filter(item=>!submittedAssignmentIds.has(item.id));
 const charges=statement.filter(item=>item.entryType==="charge"),payments=statement.filter(item=>item.entryType==="payment"),adjustments=statement.filter(item=>item.entryType==="adjustment"),overdue=charges.filter(item=>item.dueOn&&new Date(item.dueOn).getTime()<Date.now()&&!["paid","waived"].includes(item.status));
 useEffect(()=>{let cancelled=false;if(!learnerId)return;setFamilyLoading(true);setFamilyError("");Promise.all([loadLearnerFeeStatement(learnerId),loadPickupCircle(learnerId)]).then(([nextStatement,nextPickup])=>{if(cancelled)return;setFamilyRecords({key:familyKey,statement:nextStatement,pickupCircle:nextPickup});}).catch(reason=>{if(!cancelled){setFamilyRecords({key:familyKey,statement:[],pickupCircle:[]});setFamilyError(messageFrom(reason));}}).finally(()=>{if(!cancelled)setFamilyLoading(false);});return()=>{cancelled=true;};},[learnerId,familyKey]);
 if(!learner)return <div className="content"><section className="panel"><h2>No linked learner</h2><p>This family account does not currently have a learner record it is authorised to view.</p></section></div>;
 return <div className="content role-workspace">
 <section className="page-intro"><div><span>DREEM FAMILY</span><h2>Your child’s school life in one trusted view.</h2><p>Follow learning, fees, transport, official results and safe pickup without receiving teacher-only or unrelated learner records.</p></div><div className="care-assurance"><ShieldCheck/><span><strong>Family permissions</strong><small>View and family-authorized actions only; classroom authoring stays in DREEM Student / Teacher.</small></span></div></section>
 {workspace.learners.length>1?<label>Child<select value={learnerId} onChange={event=>setSelectedStudentId(event.target.value)}>{workspace.learners.map(item=><option key={item.id} value={item.id}>{item.name} · {item.className}</option>)}</select></label>:null}
 {familyError?<div className="form-status error" role="alert">Some family records could not be refreshed: {familyError}</div>:null}
 <section className="metrics"><article className="metric"><span>Attendance</span><strong>{Math.round(learner.attendance)}%</strong><small>{learner.className}</small></article><article className="metric blue"><span>Due work</span><strong>{due.length}</strong><small>{submissions.length} submission(s) recorded</small></article><article className="metric amber"><span>Fee balance</span><strong>{money(learner.feeBalance??0)}</strong><small>{overdue.length?`${overdue.length} overdue installment(s)`:learner.feeAccountId?"Verified learner account":"Fee account not yet created"}</small></article><article className="metric"><span>Published reports</span><strong>{reportCards.length}</strong><small>Official school results</small></article></section>
 <section className="panel lifecycle-panel"><div className="panel-title"><UsersRound/><div><span>FAMILY CYCLE</span><h3>Follow → respond → pay → authorize → stay informed</h3></div></div><div className="lifecycle-rail"><span><b>1</b>Follow attendance & work</span><span><b>2</b>Review feedback & results</span><span><b>3</b>Track fees & receipts</span><span><b>4</b>Review transport</span><span><b>5</b>Manage safe pickup through school workflow</span></div></section>
 <div className="academic-grid"><section className="panel"><div className="panel-title"><IdCard/><div><span>LEARNER STATUS</span><h3>Identity and school standing</h3></div></div><article className="document-row"><strong>{learner.name}</strong><span>{learner.matricule} · {learner.className}</span><small>ID credential: {learner.idStatus.replaceAll("_"," ")}</small></article></section><section className="panel"><div className="panel-title"><BusFront/><div><span>TRANSPORT</span><h3>Current route and recent journeys</h3></div></div>{transportAssignment?<><article className="document-row"><strong>{transportAssignment.routeName}</strong><span>{transportAssignment.pickupStopName} → {transportAssignment.dropoffStopName}</span><small>Active school transport assignment</small></article>{transportTrips.map(trip=><article className="document-row" key={trip.id}><strong>{trip.serviceDate} · {trip.direction}</strong><span>{trip.status.replaceAll("_"," ")}{trip.scheduledDeparture?` · ${trip.scheduledDeparture}`:""}</span></article>)}</>:<p>No active school transport assignment is linked to this learner.</p>}</section></div>
 <div className="academic-grid"><section className="panel"><div className="panel-title"><WalletCards/><div><span>FEES & INSTALLMENTS</span><h3>Charges, due dates and remaining balance</h3></div></div>{familyLoading?<p>Refreshing the protected learner statement…</p>:null}{charges.map(item=><article className="document-row" key={item.entryId}><strong>{item.label}</strong><span>{money(Math.abs(item.amount))} · due {dateText(item.dueOn)} · {item.status.replaceAll("_"," ")}</span>{item.note?<small>{item.note}</small>:null}</article>)}{!familyLoading&&!charges.length?<p>No fee installments have been released for this learner yet.</p>:null}{adjustments.map(item=><article className="document-row" key={item.entryId}><strong>{item.label}</strong><span>{money(item.amount)} · {item.status.replaceAll("_"," ")}</span>{item.note?<small>{item.note}</small>:null}</article>)}</section><section className="panel"><div className="panel-title"><ReceiptText/><div><span>PAYMENTS & RECEIPTS</span><h3>Verified payment history</h3></div></div>{payments.map(item=><article className="document-row" key={item.entryId}><strong>{item.receiptNumber||item.label}</strong><span>{money(Math.abs(item.amount))} · {dateText(item.occurredOn)}</span><small>{item.status.replaceAll("_"," ")}</small></article>)}{!familyLoading&&!payments.length?<p>No verified payments are visible for this learner yet.</p>:null}</section></div>
 <section className="panel"><div className="panel-title"><UsersRound/><div><span>PICKUP CIRCLE</span><h3>People the school currently recognises for pickup</h3></div></div><p className="panel-copy">This family view shows authorized people and recent gate outcome. New authorizations and changes follow the school’s controlled approval flow rather than being silently edited here.</p>{pickupCircle.map(member=><article className="document-row" key={member.collectorId}><strong>{member.fullName} · {member.relationship}</strong><span>{member.phoneLast4?`•••• ${member.phoneLast4} · `:""}{member.status} · valid to {dateText(member.validUntil)}</span><small>{member.lastReleaseAt?`Last gate outcome: ${member.lastDecision||"recorded"} · ${dateText(member.lastReleaseAt)}`:"No recorded release yet"}</small></article>)}{!familyLoading&&!pickupCircle.length?<p>No authorised pickup person is currently visible for this learner.</p>:null}</section>
 <div className="academic-grid"><section className="panel"><div className="panel-title"><BookOpenCheck/><div><span>SCHOOLWORK</span><h3>Published assignments and due work</h3></div></div>{assignments.map(item=><article className="document-row" key={item.id}><strong>{item.title}</strong><span>{item.subjectName} · due {new Date(item.dueAt).toLocaleString()}</span><small>{submittedAssignmentIds.has(item.id)?"Submitted":"Awaiting learner submission"}</small></article>)}{!assignments.length?<p>No published assignments are currently visible for this learner.</p>:null}<p className="panel-copy">Learner submissions are completed in DREEM Student. Family can follow status and feedback without impersonating the learner.</p></section><section className="panel"><div className="panel-title"><GraduationCap/><div><span>FEEDBACK & RESULTS</span><h3>Teacher feedback and published reports</h3></div></div>{submissions.filter(item=>item.feedback||typeof item.score==="number").slice(0,5).map(item=><article className="document-row" key={item.id}><strong>{assignments.find(a=>a.id===item.assignmentId)?.title||"Assignment"}</strong><span>{item.status.replaceAll("_"," ")}{typeof item.score==="number"?` · ${item.score} marks`:""}</span>{item.feedback?<small>{item.feedback}</small>:null}</article>)}{reportCards.map(item=><article className="document-row" key={item.id}><strong>{item.termName} report</strong><span>{typeof item.overallAverage==="number"?`Average ${item.overallAverage}`:"Average pending"} · revision {item.revision}</span><small>{item.evidenceCount} published assessment evidence item(s)</small></article>)}{!reportCards.length&&!submissions.some(item=>item.feedback||typeof item.score==="number")?<p>No released feedback or report card is available yet.</p>:null}</section></div>
 </div>;
}
