import { BookOpenCheck, BusFront, GraduationCap, ReceiptText, UsersRound, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { WorkspaceData } from "../lib/repository";
import { loadLearnerFeeStatement, type LearnerFeeStatementRow } from "../lib/familyFinance";
import { loadPickupCircle, type PickupCircleMember } from "../lib/pickupCircle";

function messageFrom(reason:unknown){return reason instanceof Error?reason.message:reason&&typeof reason==="object"&&"message" in reason&&typeof reason.message==="string"?reason.message:"The family record could not be loaded.";}
const money=(v:number)=>new Intl.NumberFormat("fr-FR").format(v)+" FCFA";
const dateText=(v:string|undefined)=>v?new Date(v).toLocaleDateString():"—";
type Tab="Today"|"Learning"|"Fees"|"Transport"|"Results";

export default function FamilyLearningWorkspace({workspace}:{workspace:WorkspaceData}){
 const[selectedStudentId,setSelectedStudentId]=useState(workspace.learners[0]?.id??""),[tab,setTab]=useState<Tab>("Today");
 const[familyRecords,setFamilyRecords]=useState<{key:string;statement:LearnerFeeStatementRow[];pickupCircle:PickupCircleMember[]}>({key:"",statement:[],pickupCircle:[]}),[familyError,setFamilyError]=useState("");
 const learner=workspace.learners.find(x=>x.id===selectedStudentId)??workspace.learners[0],learnerId=learner?.id??"",learnerClass=learner?.className??"";
 const familyKey=JSON.stringify([workspace.viewer.id,learnerId]),familyLoading=Boolean(learnerId)&&familyRecords.key!==familyKey&&!familyError;
 const statement=familyRecords.key===familyKey?familyRecords.statement:[],pickupCircle=familyRecords.key===familyKey?familyRecords.pickupCircle:[];
 const assignments=useMemo(()=>workspace.academics.assignmentsForLearners.filter(x=>x.status==="published"&&(!learnerClass||x.className===learnerClass)),[workspace.academics.assignmentsForLearners,learnerClass]);
 const submissions=workspace.academics.assignmentSubmissions.filter(x=>x.studentId===learnerId),reports=workspace.academics.reportCards.filter(x=>x.studentId===learnerId&&x.status==="published");
 const transportAssignment=workspace.transport.assignments.find(x=>x.studentId===learnerId&&x.status==="active"),transportTrips=transportAssignment?workspace.transport.trips.filter(x=>x.routeId===transportAssignment.routeId&&x.status!=="cancelled").slice(0,4):[];
 const submitted=new Set(submissions.filter(x=>x.status!=="needs_revision").map(x=>x.assignmentId)),due=assignments.filter(x=>!submitted.has(x.id));
 const charges=statement.filter(x=>x.entryType==="charge"),payments=statement.filter(x=>x.entryType==="payment"),overdue=charges.filter(x=>x.status==="overdue");
 useEffect(()=>{let cancelled=false;if(!learnerId)return;Promise.all([loadLearnerFeeStatement(learnerId),loadPickupCircle(learnerId)]).then(([s,p])=>{if(!cancelled){setFamilyRecords({key:familyKey,statement:s,pickupCircle:p});setFamilyError("");}}).catch(r=>{if(!cancelled){setFamilyRecords({key:familyKey,statement:[],pickupCircle:[]});setFamilyError(messageFrom(r));}});return()=>{cancelled=true;};},[learnerId,familyKey]);
 if(!learner)return <div className="content"><section className="panel"><h2>No linked learner</h2><p>This family account has no learner record it can view.</p></section></div>;
 const tabs:Tab[]=["Today","Learning","Fees","Transport","Results"];
 return <div className="content role-workspace family-workspace">
  <section className="role-hero"><div><span className="eyebrow">DREEM FAMILY</span><h2>Your children, one calm view</h2><p>See what matters today, then open detail only when you need it.</p></div></section>
  {workspace.learners.length>1?<div className="family-child-strip">{workspace.learners.map(x=><button key={x.id} className={"family-child "+(x.id===learner.id?"active":"")} onClick={()=>{setSelectedStudentId(x.id);setFamilyError("");}}><strong>{x.name}</strong><small>{x.className}</small></button>)}</div>:null}
  {familyError?<div className="form-status error">{familyError}</div>:null}
  <section className="visual-stats">
   <article className="visual-stat green"><div className="icon"><UsersRound/></div><div><span>ATTENDANCE</span><strong>{Math.round(learner.attendance)}%</strong><small>today / current term</small></div></article>
   <article className="visual-stat purple"><div className="icon"><BookOpenCheck/></div><div><span>DUE WORK</span><strong>{due.length}</strong><small>{submissions.length} submissions recorded</small></div></article>
   <article className={"visual-stat "+(overdue.length?"red":"amber")}><div className="icon"><WalletCards/></div><div><span>FEE BALANCE</span><strong>{money(learner.feeBalance??0)}</strong><small>{overdue.length?overdue.length+" overdue":"account current"}</small></div></article>
   <article className="visual-stat"><div className="icon"><BusFront/></div><div><span>TRANSPORT</span><strong>{transportAssignment?"Active":"—"}</strong><small>{transportAssignment?.routeName||"No route assigned"}</small></div></article>
  </section>
  <nav className="workspace-tabs" aria-label="Family sections">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>

  {tab==="Today"?<div className="focus-grid"><section className="focus-card"><span className="eyebrow">TODAY</span><h3>{learner.name}</h3><div className="action-list">{due.slice(0,3).map(x=><article className="action-row" key={x.id}><div className="action-icon"><BookOpenCheck/></div><div><strong>{x.title}</strong><small>{x.subjectName} · due {new Date(x.dueAt).toLocaleDateString()}</small></div></article>)}{!due.length?<article className="action-row"><div className="action-icon"><GraduationCap/></div><div><strong>No schoolwork needs attention</strong><small>New work will appear here automatically.</small></div></article>:null}</div></section><aside className="focus-card"><span className="eyebrow">WHAT NEEDS ACTION</span><h3>{overdue.length?overdue.length+" fee item"+(overdue.length===1?"":"s")+" overdue":"No urgent family action"}</h3><p>{transportAssignment?"Transport is assigned on "+transportAssignment.routeName+".":"No active transport route is linked."}</p>{overdue.length?<button className="primary" onClick={()=>setTab("Fees")}>View fees</button>:null}</aside></div>:null}

  {tab==="Learning"?<section className="focus-card"><div className="panel-title"><div><span>SCHOOLWORK</span><h3>Assignments and submission status</h3></div></div><div className="action-list">{assignments.map(x=><article className="action-row" key={x.id}><div className="action-icon"><BookOpenCheck/></div><div><strong>{x.title}</strong><small>{x.subjectName} · {submitted.has(x.id)?"Submitted":"Awaiting submission"} · due {new Date(x.dueAt).toLocaleDateString()}</small></div></article>)}{!assignments.length?<p>No published assignments yet.</p>:null}</div></section>:null}

  {tab==="Fees"?<div className="focus-grid"><section className="focus-card"><div className="panel-title"><div><span>INSTALLMENTS</span><h3>What is due</h3></div></div>{familyLoading?<p>Refreshing statement…</p>:charges.map(x=><article className="document-row" key={x.entryId}><strong>{x.label}</strong><span>{money(Math.abs(x.amount))} · due {dateText(x.dueOn)}</span><small>{x.status.replaceAll("_"," ")}</small></article>)}{!familyLoading&&!charges.length?<p>No fee installments released yet.</p>:null}</section><aside className="focus-card"><div className="panel-title"><div><span>PAYMENTS</span><h3>Verified receipts</h3></div></div>{payments.map(x=><article className="document-row" key={x.entryId}><strong>{x.receiptNumber||x.label}</strong><span>{money(Math.abs(x.amount))}</span><small>{dateText(x.occurredOn)} · {x.status.replaceAll("_"," ")}</small></article>)}{!payments.length?<p>No verified payment yet.</p>:null}</aside></div>:null}

  {tab==="Transport"?<div className="focus-grid"><section className="focus-card"><div className="panel-title"><div><span>TRANSPORT</span><h3>{transportAssignment?.routeName||"No active route"}</h3></div></div>{transportAssignment?<><p>{transportAssignment.pickupStopName} → {transportAssignment.dropoffStopName}</p>{transportTrips.map(x=><article className="document-row" key={x.id}><strong>{x.serviceDate} · {x.direction}</strong><span>{x.status.replaceAll("_"," ")}</span></article>)}</>:<p>No active school transport assignment.</p>}</section><aside className="focus-card"><div className="panel-title"><div><span>SAFE PICKUP</span><h3>Approved pickup circle</h3></div></div>{pickupCircle.map(x=><article className="document-row" key={x.collectorId}><strong>{x.fullName}</strong><span>{x.relationship} · {x.status}</span><small>Valid to {dateText(x.validUntil)}</small></article>)}{!familyLoading&&!pickupCircle.length?<p>No approved pickup person is visible.</p>:null}</aside></div>:null}

  {tab==="Results"?<section className="focus-card"><div className="panel-title"><div><span>FEEDBACK & RESULTS</span><h3>Released by the school</h3></div></div>{submissions.filter(x=>x.feedback||typeof x.score==="number").slice(0,6).map(x=><article className="document-row" key={x.id}><strong>{assignments.find(a=>a.id===x.assignmentId)?.title||"Assignment"}</strong><span>{typeof x.score==="number"?x.score+" marks":x.status.replaceAll("_"," ")}</span>{x.feedback?<small>{x.feedback}</small>:null}</article>)}{reports.map(x=><article className="document-row" key={x.id}><strong>{x.termName} report</strong><span>{typeof x.overallAverage==="number"?"Average "+x.overallAverage:"Average pending"}</span></article>)}{!reports.length&&!submissions.some(x=>x.feedback||typeof x.score==="number")?<p>No released results yet.</p>:null}</section>:null}
 </div>;
}