import { useEffect, useState, type FormEvent } from "react";
import { BadgeCheck, Banknote, Landmark, Scale, ShieldCheck } from "lucide-react";
import type { Role } from "../domain/types";
import { createCashDepositBatch, loadFinanceControlDesk, reviewCashDepositBatch, reviewCashierSession, submitCashierSession, type FinanceControlDeskData } from "../lib/repository";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";

export default function FinanceControlDesk({role,onChanged}:{role:Role;onChanged:()=>Promise<void>}){
  const[data,setData]=useState<FinanceControlDeskData|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const isCashier=role==="bursar",isReviewer=["platform_founder","school_owner","principal","accountant"].includes(role),isReadOnly=role==="auditor";
  async function reload(){try{setData(await loadFinanceControlDesk())}catch(reason){setError(reason instanceof Error?reason.message:"Finance controls could not be loaded.")}}
  useEffect(()=>{void reload()},[]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await Promise.all([reload(),onChanged()]);setMessage(success)}catch(reason){setError(reason instanceof Error?reason.message:"Finance command failed.")}finally{setBusy(false)}}
  async function closeSession(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data?.openSession)return;const f=new FormData(event.currentTarget);await run(()=>submitCashierSession({sessionId:data.openSession!.id,declaredCash:Number(f.get("declaredCash")),explanation:String(f.get("explanation")),evidenceReference:String(f.get("evidence"))}),"Cash count submitted for independent review.")}
  async function reviewSession(event:FormEvent<HTMLFormElement>,reviewId:string){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>reviewCashierSession({reviewId,approved:String(f.get("decision"))==="approved",note:String(f.get("note")),evidenceReference:String(f.get("evidence"))}),"Independent cashier review recorded.")}
  async function deposit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>createCashDepositBatch({paymentIds:f.getAll("paymentIds").map(String),destinationRailId:String(f.get("railId")),depositReference:String(f.get("depositReference")),evidenceReference:String(f.get("evidence"))}),"Deposit batch submitted for independent confirmation.")}
  async function reviewDeposit(event:FormEvent<HTMLFormElement>,batchId:string){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>reviewCashDepositBatch({batchId,approved:String(f.get("decision"))==="confirmed",note:String(f.get("note"))}),"Institutional settlement decision recorded.")}
  if(!data)return <section className="panel"><p>Loading protected finance controls…</p></section>;
  return <section className="finance-control-desk" aria-label="Finance control desk"><div className="panel-title"><div><span>CONTROLLED FINANCE JOURNEY</span><h3>Collect → count → review → deposit → confirm</h3></div><ShieldCheck/></div>{error&&<div className="form-status error">{error}</div>}{message&&<div className="form-status success">{message}</div>}
    {isCashier&&<div className="transport-grid"><section className="panel"><div className="panel-title"><Banknote/><div><span>1 · CASHIER CLOSURE</span><h3>Count and submit the open till</h3></div></div>{data.openSession?<form className="settings-form" onSubmit={closeSession}><p>Opened {new Date(data.openSession.openedAt).toLocaleString()} · opening float {money(data.openSession.openingFloat)}</p><div className="form-grid"><label>Physical cash counted<input name="declaredCash" type="number" min="0" step="1" inputMode="numeric" required/></label><label>Variance explanation<input name="explanation" placeholder="Required when count differs"/></label><label>Count-sheet evidence reference<input name="evidence" required/></label></div><button className="primary" disabled={busy}>Submit till for review</button></form>:<p>No open cash session. One opens automatically with the first cash collection.</p>}</section><section className="panel"><div className="panel-title"><Landmark/><div><span>3 · INSTITUTIONAL DEPOSIT</span><h3>Move approved cash into the school account</h3></div></div>{data.unsettledCash.length&&data.settlementRails.length?<form className="settings-form" onSubmit={deposit}><div className="checks">{data.unsettledCash.map(payment=><label key={payment.id}><input type="checkbox" name="paymentIds" value={payment.id}/>{payment.receiptNumber} · {money(payment.amount)}</label>)}</div><div className="form-grid"><label>School settlement account<select name="railId" required><option value="">Choose account</option>{data.settlementRails.map(rail=><option key={rail.id} value={rail.id}>{rail.name} · {rail.code}</option>)}</select></label><label>Bank / MoMo deposit reference<input name="depositReference" required/></label><label>Deposit-slip evidence reference<input name="evidence" required/></label></div><button className="primary" disabled={busy}>Submit deposit batch</button></form>:<p>Available after closure approval and settlement-account configuration.</p>}</section></div>}
    {isReviewer&&<div className="transport-grid"><section className="panel"><div className="panel-title"><Scale/><div><span>2 · INDEPENDENT REVIEW</span><h3>Reconcile cashier closures</h3></div></div>{data.pendingReviews.map(review=><form className="settings-form subform" key={review.id} onSubmit={event=>reviewSession(event,review.id)}><strong>Variance {money(review.variance)}</strong><small>{review.explanation||"No cashier explanation"}</small><div className="form-grid"><label>Decision<select name="decision"><option value="approved">Approve closure</option><option value="rejected">Reject and investigate</option></select></label><label>Independent review note<input name="note" required/></label><label>Review evidence reference<input name="evidence" required/></label></div><button className="primary" disabled={busy}>Record independent decision</button></form>)}{!data.pendingReviews.length&&<p>No cashier closure awaits review.</p>}</section><section className="panel"><div className="panel-title"><BadgeCheck/><div><span>4 · SETTLEMENT CONFIRMATION</span><h3>Confirm money reached the institution</h3></div></div>{data.pendingDeposits.map(batch=><form className="settings-form subform" key={batch.id} onSubmit={event=>reviewDeposit(event,batch.id)}><strong>{batch.reference} · {money(batch.amount)}</strong><small>Provider reference {batch.depositReference}</small><div className="form-grid"><label>Decision<select name="decision"><option value="confirmed">Confirm settlement</option><option value="rejected">Reject evidence</option></select></label><label>Bank-statement review note<input name="note" required/></label></div><button className="primary" disabled={busy}>Record settlement decision</button></form>)}{!data.pendingDeposits.length&&<p>No deposit batch awaits confirmation.</p>}</section></div>}
    {isReadOnly&&<section className="panel"><h3>Independent audit view</h3><p>{data.pendingReviews.length} cashier reviews and {data.pendingDeposits.length} deposit confirmations are pending. Auditors can inspect but cannot mutate money records.</p></section>}
  </section>;
}
