import { useEffect, useState, type FormEvent } from "react";
import { BadgeDollarSign, BookOpenCheck, ReceiptText, Scale } from "lucide-react";
import type { Role } from "../domain/types";
import { loadInstitutionFinance, postJournalEntry, requestRefund, reviewRefund, type FinanceControlSnapshot, type JournalEntry, type RefundRequestRow, type RefundablePayment } from "../lib/financeInstitution";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";
const errorText=(reason:unknown)=>reason instanceof Error?reason.message:"Finance control action could not be completed.";

export default function FinanceInstitutionControls({role,onChanged}:{role:Role;onChanged:()=>Promise<void>}){
  const [snapshot,setSnapshot]=useState<FinanceControlSnapshot|null>(null),[refunds,setRefunds]=useState<RefundRequestRow[]>([]),[payments,setPayments]=useState<RefundablePayment[]>([]),[journal,setJournal]=useState<JournalEntry[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const canRequest=["bursar","platform_founder","school_owner","principal"].includes(role),canReview=["accountant","platform_founder","school_owner","principal"].includes(role),canPost=["accountant","platform_founder","school_owner","principal"].includes(role),readOnly=role==="auditor";
  async function reload(){const data=await loadInstitutionFinance();setSnapshot(data.snapshot);setRefunds(data.refunds);setPayments(data.payments);setJournal(data.journal);}
  useEffect(()=>{reload().catch(reason=>setError(errorText(reason)));},[]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await Promise.all([reload(),onChanged()]);setMessage(success);}catch(reason){setError(errorText(reason));}finally{setBusy(false);}}
  async function submitRefund(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>requestRefund({paymentId:String(f.get("paymentId")),amount:Number(f.get("amount")),reason:String(f.get("reason")),idempotencyKey:`refund:${crypto.randomUUID()}`}),"Refund request sent for independent review.");}
  async function decideRefund(event:FormEvent<HTMLFormElement>,refundId:string){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>reviewRefund({refundId,decision:String(f.get("decision")) as "approve"|"reject",note:String(f.get("note"))}),"Refund review decision recorded.");}
  async function submitJournal(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>postJournalEntry({entryType:String(f.get("entryType")) as "charge"|"payment"|"allocation"|"waiver"|"refund"|"reversal"|"deposit"|"reconciliation"|"adjustment",referenceType:String(f.get("referenceType")),debitAccount:String(f.get("debitAccount")),creditAccount:String(f.get("creditAccount")),amount:Number(f.get("amount")),description:String(f.get("description")),idempotencyKey:`journal:${crypto.randomUUID()}`}),"Accounting journal entry posted and audited.");}
  return <section className="finance-institution-controls"><div className="panel-title"><Scale/><div><span>INSTITUTIONAL FINANCE CONTROL</span><h3>Correct, review and close the money trail without erasing history</h3></div></div>{error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
    {snapshot?<div className="metrics"><article className="metric"><span>Receivables</span><strong>{money(snapshot.receivables)}</strong><small>Current learner balances</small></article><article className="metric blue"><span>Gross collections</span><strong>{money(snapshot.grossCollections)}</strong><small>{money(snapshot.confirmedDeposits)} confirmed deposited</small></article><article className="metric amber"><span>Pending controls</span><strong>{snapshot.pendingReconciliations+snapshot.pendingDeposits}</strong><small>Reconciliation + deposit review</small></article><article className="metric red"><span>Refund review</span><strong>{snapshot.pendingRefunds}</strong><small>Independent decision required</small></article></div>:null}
    <div className="transport-grid">{canRequest?<section className="panel"><div className="panel-title"><ReceiptText/><div><span>REFUND REQUEST</span><h3>Request correction against an actual receipt</h3></div></div><form className="settings-form" onSubmit={submitRefund}><label>Original payment<select name="paymentId" required><option value="">Choose receipt</option>{payments.map(payment=><option key={payment.id} value={payment.id}>{payment.receiptNumber} · {money(payment.amount)} · {payment.payerName}</option>)}</select></label><div className="form-grid"><label>Refund amount<input name="amount" type="number" min="1" required/></label><label>Reason<input name="reason" minLength={5} required/></label></div><button className="primary" disabled={busy}>Request refund review</button></form></section>:null}
      {canReview?<section className="panel"><div className="panel-title"><BadgeDollarSign/><div><span>REFUND REVIEW</span><h3>Requester cannot approve their own refund</h3></div></div>{refunds.filter(item=>item.status==="pending_review").map(item=><form className="settings-form subform" key={item.id} onSubmit={event=>decideRefund(event,item.id)}><strong>{money(item.amount)}</strong><span>{item.reason}</span><div className="form-grid"><label>Decision<select name="decision"><option value="approve">Approve</option><option value="reject">Reject</option></select></label><label>Review note<input name="note" required/></label></div><button className="primary" disabled={busy}>Record independent decision</button></form>)}{!refunds.some(item=>item.status==="pending_review")?<p>No refund request awaits review.</p>:null}</section>:null}
    </div>
    {canPost?<section className="panel"><div className="panel-title"><BookOpenCheck/><div><span>ACCOUNTING JOURNAL</span><h3>Post controlled debit / credit evidence</h3></div></div><form className="settings-form" onSubmit={submitJournal}><div className="form-grid"><label>Entry type<select name="entryType"><option value="payment">Payment</option><option value="allocation">Allocation</option><option value="waiver">Waiver</option><option value="refund">Refund</option><option value="reversal">Reversal</option><option value="deposit">Deposit</option><option value="reconciliation">Reconciliation</option><option value="adjustment">Adjustment</option></select></label><label>Reference type<input name="referenceType" placeholder="payment, deposit, adjustment…" required/></label><label>Debit account<input name="debitAccount" placeholder="Cash / Bank / Receivable" required/></label><label>Credit account<input name="creditAccount" placeholder="Fees / Cash / Liability" required/></label><label>Amount<input name="amount" type="number" min="1" required/></label><label>Description<input name="description" required/></label></div><button className="primary" disabled={busy}>Post audited journal entry</button></form></section>:null}
    <section className="panel"><div className="panel-title"><BookOpenCheck/><div><span>{readOnly?"AUDIT JOURNAL":"RECENT ACCOUNTING JOURNAL"}</span><h3>Append-only accounting evidence</h3></div></div>{journal.slice(0,20).map(entry=><article className="document-row" key={entry.id}><strong>#{entry.entryNumber} · {entry.entryType}</strong><span>{money(entry.amount)} · {entry.debitAccount} → {entry.creditAccount}</span><small>{entry.description} · {new Date(entry.postedAt).toLocaleString()}</small></article>)}{!journal.length?<p>No accounting journal entry has been posted yet.</p>:null}</section>
  </section>;
}
