import { useEffect, useState, type FormEvent } from "react";
import { BadgeCheck, Banknote, Landmark, Scale, ShieldCheck } from "lucide-react";
import type { Role } from "../domain/types";
import type { AuthorityScope } from "../lib/authority";
import { canAuthority } from "../lib/access";
import { createCashDepositBatch, loadFinanceControlDesk, reviewCashDepositBatch, reviewCashierSession, submitCashierSession, type FinanceControlDeskData } from "../lib/repository";
import { userFacingError } from "../lib/userFacingError";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";
const financeError=(reason:unknown)=>userFacingError(reason,"This finance action could not be completed. Nothing has been assumed saved. Check the school finance setup and try again.");

export default function FinanceControlDesk({role,authorityScopes,onChanged}:{role:Role;authorityScopes?:AuthorityScope[];onChanged:()=>Promise<void>}){
  const[data,setData]=useState<FinanceControlDeskData|null>(null),[selectedPayments,setSelectedPayments]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const viewer={role,authorityScopes};
  const isCashier=canAuthority(viewer,"finance_collection")&&!canAuthority(viewer,"finance_approval"),isReviewer=canAuthority(viewer,"finance_approval"),isReadOnly=canAuthority(viewer,"audit")&&!isReviewer&&!isCashier;
  async function reload(){try{setData(await loadFinanceControlDesk())}catch(reason){setError(financeError(reason))}}
  useEffect(()=>{void reload()},[]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await Promise.all([reload(),onChanged()]);setMessage(success)}catch(reason){setError(financeError(reason))}finally{setBusy(false)}}
  async function closeSession(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data?.openSession)return;const f=new FormData(event.currentTarget);await run(()=>submitCashierSession({sessionId:data.openSession!.id,declaredCash:Number(f.get("declaredCash")),explanation:String(f.get("explanation")),evidenceReference:String(f.get("evidence"))}),"Cash count sent for review.")}
  async function reviewSession(event:FormEvent<HTMLFormElement>,reviewId:string){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>reviewCashierSession({reviewId,approved:String(f.get("decision"))==="approved",note:String(f.get("note")),evidenceReference:String(f.get("evidence"))}),"Cashier review saved.")}
  async function deposit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const paymentIds=f.getAll("paymentIds").map(String);if(!paymentIds.length){setError("Choose at least one verified cash receipt before preparing a deposit.");return;}await run(()=>createCashDepositBatch({paymentIds,destinationRailId:String(f.get("railId")),depositReference:String(f.get("depositReference")),evidenceReference:String(f.get("evidence"))}),"Deposit sent for confirmation.");setSelectedPayments([])}
  async function reviewDeposit(event:FormEvent<HTMLFormElement>,batchId:string){event.preventDefault();const f=new FormData(event.currentTarget);await run(()=>reviewCashDepositBatch({batchId,approved:String(f.get("decision"))==="confirmed",note:String(f.get("note"))}),"School receipt confirmed.")}
  if(!data)return <section className="panel" aria-live="polite">{error?<><div className="form-status error" role="alert">{error}</div><button type="button" className="primary" onClick={()=>void reload()}>Retry loading finance</button></>:<p>Loading finance…</p>}</section>;
  return <section className="finance-control-desk" aria-label="Finance control desk"><div className="panel-title"><div><span>TODAY'S MONEY</span><h3>Collect, close, deposit and confirm</h3></div><ShieldCheck/></div>{error&&<div className="form-status error">{error}</div>}{message&&<div className="form-status success">{message}</div>}
    {isCashier&&<div className="transport-grid"><section className="panel"><div className="panel-title"><Banknote/><div><span>1 · CLOSE THE TILL</span><h3>Count today's cash</h3></div></div>{data.openSession?<form className="settings-form" onSubmit={closeSession}><p>Opened {new Date(data.openSession.openedAt).toLocaleString()} · opening float {money(data.openSession.openingFloat)}</p><div className="form-grid"><label>Physical cash counted<input name="declaredCash" type="number" min="0" step="1" inputMode="numeric" required/></label><label>Explain any difference<input name="explanation" placeholder="Required when count differs"/></label><label>Count-sheet reference<input name="evidence" required/></label></div><button className="primary" disabled={busy}>Submit till for review</button></form>:<p>No open cash session. One opens automatically with the first cash collection.</p>}</section><section className="panel"><div className="panel-title"><Landmark/><div><span>3 · DEPOSIT</span><h3>Record money deposited to the school</h3></div></div>{data.unsettledCash.length&&data.settlementRails.length?<form className="settings-form" onSubmit={deposit}><div className="checks"><p>Choose the cash receipts included in this actual deposit.</p>{data.unsettledCash.map(payment=><label key={payment.id}><input type="checkbox" name="paymentIds" value={payment.id} checked={selectedPayments.includes(payment.id)} onChange={event=>setSelectedPayments(current=>event.target.checked?[...current,payment.id]:current.filter(id=>id!==payment.id))}/>{payment.receiptNumber} · {money(payment.amount)}</label>)}</div><p role="status" className="finance-selected-total">{selectedPayments.length} receipt{selectedPayments.length===1?"":"s"} selected · {money(data.unsettledCash.filter(payment=>selectedPayments.includes(payment.id)).reduce((sum,payment)=>sum+payment.amount,0))}</p><div className="form-grid"><label>School account<select name="railId" required><option value="">Choose account</option>{data.settlementRails.map(rail=><option key={rail.id} value={rail.id}>{rail.name} · {rail.code}</option>)}</select></label><label>Bank or Mobile Money reference<input name="depositReference" required/></label><label>Deposit slip reference<input name="evidence" required/></label></div><button className="primary" disabled={busy||!selectedPayments.some(id=>data.unsettledCash.some(payment=>payment.id===id))}>Submit deposit batch</button></form>:<p>Available after closure approval and settlement-account configuration.</p>}</section></div>}
    {isReviewer&&<div className="transport-grid"><section className="panel"><div className="panel-title"><Scale/><div><span>2 · REVIEW</span><h3>Cashier closings · {data.pendingReviews.length} awaiting a decision</h3></div></div>{data.pendingReviews.map(review=><details className="finance-review-item" key={review.id}><summary><span><strong>Cashier closing · variance {money(review.variance)}</strong><small>{review.explanation||"No cashier explanation recorded"}</small></span><span className="finance-review-cta">Review closing</span></summary><form className="settings-form subform" onSubmit={event=>reviewSession(event,review.id)}><div className="form-grid"><label>Decision<select name="decision"><option value="approved">Approve closure</option><option value="rejected">Reject and investigate</option></select></label><label>Review note<input name="note" required/></label><label>Review reference<input name="evidence" required/></label></div><button className="primary" disabled={busy}>Save decision</button></form></details>)}{!data.pendingReviews.length&&<p>No cashier closure awaits review.</p>}</section><section className="panel"><div className="panel-title"><BadgeCheck/><div><span>4 · CONFIRM DEPOSIT</span><h3>Deposits · {data.pendingDeposits.length} awaiting confirmation</h3></div></div>{data.pendingDeposits.map(batch=><details className="finance-review-item" key={batch.id}><summary><span><strong>{batch.reference} · {money(batch.amount)}</strong><small>Provider reference {batch.depositReference}</small></span><span className="finance-review-cta">Confirm deposit</span></summary><form className="settings-form subform" onSubmit={event=>reviewDeposit(event,batch.id)}><div className="form-grid"><label>Decision<select name="decision"><option value="confirmed">Confirm settlement</option><option value="rejected">Reject evidence</option></select></label><label>Confirmation note<input name="note" required/></label></div><button className="primary" disabled={busy}>Save confirmation</button></form></details>)}{!data.pendingDeposits.length&&<p>No deposit batch awaits confirmation.</p>}</section></div>}
    {isReadOnly&&<section className="panel"><h3>Independent audit view</h3><p>{data.pendingReviews.length} cashier reviews and {data.pendingDeposits.length} deposit confirmations are pending. Auditors can inspect but cannot mutate money records.</p></section>}
  </section>;
}
