import type { AccessMembership, FinanceSummary, LearnerSummary, Role, SchoolSetup } from "../domain/types";
import BursarCollectionWorkspace from "./BursarCollectionWorkspace";
import FinanceControlDesk from "./FinanceControlDesk";
import FeePlanStudio from "./FeePlanStudio";
import { Metric } from "./Views";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";

export default function FinanceWorkspace({finance,learners,operations,setup,role,onRecorded}:{finance:FinanceSummary;learners:LearnerSummary[];operations?:{memberships:AccessMembership[]};setup:SchoolSetup;role:Role;onRecorded:()=>Promise<void>}){
  const approvedRoles=new Set((operations?.memberships??[]).filter(item=>item.status==="approved").map(item=>item.role));
  const hasCollector=role==="bursar"||["platform_founder","school_owner","principal","administrator"].includes(role)||approvedRoles.has("bursar");
  const hasReviewer=role==="accountant"||["platform_founder","school_owner","principal","auditor"].includes(role)||approvedRoles.has("accountant");
  const hasFeeAccounts=learners.some(item=>item.feeAccountId);
  const prerequisites=<section className="panel prerequisite-panel"><div className="panel-title"><div><span>FINANCE PREREQUISITES</span><h3>Prepare the controlled money trail</h3></div></div><div className="prereq-grid"><article className={hasCollector?"ready":"missing"}><strong>1. Bursar / cashier</strong><p>{hasCollector?"A payment collector is available.":"Go to Daily operations → Invite staff, choose Bursar / cashier, then approve the membership."}</p></article><article className={hasReviewer?"ready":"missing"}><strong>2. Accountant / reviewer</strong><p>{hasReviewer?"Independent finance review is available.":"Invite and approve an Accountant so closures, deposits and exceptions are reviewed separately."}</p></article><article className={hasFeeAccounts?"ready":"missing"}><strong>3. Learner fee accounts</strong><p>{hasFeeAccounts?"Learner fee accounts exist for collection.":"Complete Admissions so the learner and fee account exist before collection."}</p></article></div></section>;
  if(role==="bursar")return <><div className="content">{prerequisites}<FeePlanStudio setup={setup} role={role} onChanged={onRecorded}/></div><BursarCollectionWorkspace finance={finance} learners={learners} onRecorded={onRecorded}/><div className="content"><FinanceControlDesk role={role} onChanged={onRecorded}/></div></>;
  const reviewer=["platform_founder","school_owner","principal","accountant"].includes(role);
  return <div className="content role-workspace"><section className="page-intro"><div><span>FINANCE & FEES</span><h2>{reviewer?"Review and confirm the institutional money trail":"Read-only financial assurance"}</h2><p>{reviewer?"Your controls begin after collection: review cashier closure evidence, then independently confirm deposit settlement.":"Inspect the verified money trail without changing operational records."}</p></div></section>{prerequisites}<FeePlanStudio setup={setup} role={role} onChanged={onRecorded}/><div className="metrics"><Metric label="Open fee balance" value={money(finance.expectedToday)} detail="Across learner accounts" tone="blue"/><Metric label="Cash awaiting deposit" value={money(finance.cashAwaitingDeposit)} detail={`${money(finance.cashCollected)} collected`} tone="amber"/><Metric label="Digital confirmed" value={money(finance.digitalConfirmed)} detail="Provider references captured"/><Metric label="Open exceptions" value={String(finance.openExceptions)} detail={money(finance.openExceptionValue)} tone={finance.openExceptions?"red":"green"}/></div><FinanceControlDesk role={role} onChanged={onRecorded}/></div>;
}