import { BadgeCheck, Banknote, Landmark, Scale, ShieldCheck } from "lucide-react";
import type { AccessMembership, FinanceSummary, LearnerSummary, Role, SchoolSetup } from "../domain/types";
import BursarCollectionWorkspace from "./BursarCollectionWorkspace";
import FinanceControlDesk from "./FinanceControlDesk";
import FinanceInstitutionControls from "./FinanceInstitutionControls";
import FeePlanStudio from "./FeePlanStudio";
import { Metric } from "./Views";

const money=(value:number)=>new Intl.NumberFormat("fr-FR").format(value)+" FCFA";

export default function FinanceWorkspace({finance,learners,operations,setup,role,onRecorded}:{finance:FinanceSummary;learners:LearnerSummary[];operations?:{memberships:AccessMembership[]};setup:SchoolSetup;role:Role;onRecorded:()=>Promise<void>}){
  const approvedRoles=new Set((operations?.memberships??[]).filter(item=>item.status==="approved").map(item=>item.role));
  const hasCollector=role==="bursar"||["platform_founder","school_owner","principal","administrator"].includes(role)||approvedRoles.has("bursar");
  const hasReviewer=role==="accountant"||["platform_founder","school_owner","principal","auditor"].includes(role)||approvedRoles.has("accountant");
  const hasFeeAccounts=learners.some(item=>item.feeAccountId);
  const isBursar=role==="bursar",isAccountant=role==="accountant",isAuditor=role==="auditor";
  const prerequisites=<section className="panel prerequisite-panel"><div className="panel-title"><ShieldCheck/><div><span>FINANCE CONTROL CONDITIONS</span><h3>Collection and review stay separate</h3></div></div><div className="prereq-grid"><article className={hasCollector?"ready":"missing"}><strong>Collector</strong><p>{hasCollector?"An approved bursar/cashier is available.":"Invite and approve a Bursar / cashier in Daily operations."}</p></article><article className={hasReviewer?"ready":"missing"}><strong>Independent reviewer</strong><p>{hasReviewer?"An accountant/reviewer is available.":"Invite and approve an Accountant before closure and settlement review."}</p></article><article className={hasFeeAccounts?"ready":"missing"}><strong>Learner accounts</strong><p>{hasFeeAccounts?"Learner fee accounts exist.":"Complete Admissions enrolment so learner fee accounts exist before collection."}</p></article></div></section>;
  const roleGuide=isBursar?<section className="panel finance-role-guide"><div className="panel-title"><Banknote/><div><span>YOUR BURSAR WORK</span><h3>Collect → receipt → close till → deposit</h3><p>You collect and prove money received. Your own till variance and institutional settlement must be reviewed by another authorized role.</p></div></div><div className="lifecycle-rail"><span className="active"><b>1</b>Collect payment<small>Collection desk</small></span><span><b>2</b>Issue receipt<small>Created with verified payment</small></span><span><b>3</b>Close till<small>Finance control desk</small></span><span><b>4</b>Independent review<small>Accountant owns this</small></span><span><b>5</b>Deposit approved cash<small>Finance control desk</small></span><span><b>6</b>Refund / correction<small>Request only; reviewer decides</small></span></div></section>:isAccountant?<section className="panel finance-role-guide"><div className="panel-title"><Scale/><div><span>YOUR ACCOUNTANT WORK</span><h3>Review → reconcile → confirm → account</h3><p>Collection stays with the bursar. Your job begins at independent review and ends with settlement, refund decisions and append-only accounting evidence.</p></div></div><div className="lifecycle-rail"><span><b>1</b>Collection<small>Bursar-owned</small></span><span className="active"><b>2</b>Review till<small>Finance control desk</small></span><span className="active"><b>3</b>Review exceptions<small>Compare evidence</small></span><span><b>4</b>Deposit<small>Bursar-owned</small></span><span className="active"><b>5</b>Confirm settlement<small>Finance control desk</small></span><span className="active"><b>6</b>Refund / journal<small>Independent accounting</small></span></div></section>:isAuditor?<section className="panel finance-role-guide"><div className="panel-title"><BadgeCheck/><div><span>YOUR AUDIT VIEW</span><h3>Inspect the trail without changing it</h3><p>Review collection, allocation, closure, deposit, refund and journal evidence. Operational mutation remains disabled for auditors.</p></div></div></section>:<section className="panel finance-role-guide"><div className="panel-title"><Landmark/><div><span>LEADERSHIP FINANCE VIEW</span><h3>Set fee policy and protect separation of duties</h3><p>Leadership controls fee structures and sees exceptions; bursars collect and accountants independently review settlement, refunds and accounting evidence.</p></div></div></section>;

  if(isBursar)return <><div className="content role-workspace">{roleGuide}{prerequisites}<FeePlanStudio setup={setup} role={role} onChanged={onRecorded}/></div><BursarCollectionWorkspace finance={finance} learners={learners} onRecorded={onRecorded}/><div className="content role-workspace"><FinanceControlDesk role={role} onChanged={onRecorded}/><FinanceInstitutionControls role={role} onChanged={onRecorded}/></div></>;
  const reviewer=["platform_founder","school_owner","principal","accountant"].includes(role);
  return <div className="content role-workspace"><section className="page-intro"><div><span>FINANCE & FEES</span><h2>{reviewer?"Review and confirm the institutional money trail":"Read-only financial assurance"}</h2><p>{reviewer?"Every stage has an owner, evidence and an auditable correction path. Collection and approval cannot quietly collapse into one person.":"Inspect the verified money trail without changing operational records."}</p></div></section>{roleGuide}{prerequisites}<FeePlanStudio setup={setup} role={role} onChanged={onRecorded}/><div className="metrics"><Metric label="Open fee balance" value={money(finance.expectedToday)} detail="Across learner accounts" tone="blue"/><Metric label="Cash awaiting deposit" value={money(finance.cashAwaitingDeposit)} detail={`${money(finance.cashCollected)} collected`} tone="amber"/><Metric label="Digital confirmed" value={money(finance.digitalConfirmed)} detail="Provider references captured"/><Metric label="Open exceptions" value={String(finance.openExceptions)} detail={money(finance.openExceptionValue)} tone={finance.openExceptions?"red":"green"}/></div><FinanceControlDesk role={role} onChanged={onRecorded}/><FinanceInstitutionControls role={role} onChanged={onRecorded}/></div>;
}
