// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { demoBrand, demoLearners } from "../domain/demo";
import LearnersWorkspace from "./LearnersWorkspace";

const loadLearnerOneFile=vi.fn();
vi.mock("../lib/repository",async()=>{const actual=await vi.importActual<typeof import("../lib/repository")>("../lib/repository");return{...actual,loadLearnerOneFile:(id:string)=>loadLearnerOneFile(id)}});
const oneFile={identity:{id:"1",matricule:"DRM-001",name:"Amina N.",className:"Form 4A",attendanceRate:93,riskLevel:"low"},guardians:[{name:"Verified Guardian",relationship:"Mother",phone:"***1234",isPrimary:true,canCollect:true}],attendance:[{status:"present",recordedAt:"2026-08-26T08:00:00Z"}],assessments:[{title:"Mathematics test",score:16,maxScore:20,date:"2026-08-20"}],interventions:[],cases:[],finance:{amountDue:100000,amountPaid:60000,balanceDue:40000,status:"partial",receipts:[{number:"GBC-001",amount:60000,method:"cash",receivedAt:"2026-08-20T10:00:00Z"}]},credential:{status:"active",validUntil:"2027-07-31",issuedAt:"2026-08-01"},transport:{routeName:"Mendong",pickupStop:"Junction",dropoffStop:"School Gate",status:"active"}};
describe("authoritative learner OneFile",()=>{afterEach(()=>{cleanup();vi.clearAllMocks()});it("opens the connected institutional record",async()=>{loadLearnerOneFile.mockResolvedValue(oneFile);render(<LearnersWorkspace learners={[demoLearners[0]]} brand={demoBrand} role="principal"/>);fireEvent.click(screen.getByRole("button",{name:/open complete onefile/i}));await waitFor(()=>expect(loadLearnerOneFile).toHaveBeenCalledWith(demoLearners[0].id));expect(await screen.findByRole("region",{name:"Amina N. OneFile"})).toHaveTextContent("Verified Guardian");expect(screen.getByText("Mathematics test")).toBeInTheDocument();expect(screen.getByText(/40.*FCFA outstanding/i)).toBeInTheDocument()});it("keeps care and finance sections out of the family view",async()=>{loadLearnerOneFile.mockResolvedValue(oneFile);render(<LearnersWorkspace learners={[demoLearners[0]]} brand={demoBrand} role="parent"/>);fireEvent.click(screen.getByRole("button",{name:/open complete onefile/i}));await screen.findByRole("region",{name:"Amina N. OneFile"});expect(screen.queryByRole("heading",{name:"Support and care"})).not.toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Fee-account evidence"})).not.toBeInTheDocument();expect(screen.getByRole("heading",{name:"Guardians and collection authority"})).toBeInTheDocument()})});
