import { useCallback, useEffect, useState } from "react";
import { BellRing, Mail, MessageSquareText, Send } from "lucide-react";
import type { Role } from "../domain/types";
import type { AuthorityScope } from "../lib/authority";
import { canAuthority } from "../lib/access";
import { acknowledgeNotificationDelivery, disableNotificationChannel, dispatchQueuedNotifications, enableVerifiedAuthChannel, loadDeliverySummary, loadMyNotificationDeliveries, loadMyNotificationEndpoints, type DeliverySummary, type MyNotificationDelivery, type NotificationEndpoint } from "../lib/notificationChannels";
import { userFacingError } from "../lib/userFacingError";

const errorText=(reason:unknown)=>userFacingError(reason,"Notification settings could not be updated. Nothing has been assumed changed. Check your connection and try again.");
export default function NotificationDeliveryPanel({role,authorityScopes}:{role:Role;authorityScopes?:AuthorityScope[]}){
 const viewer={role,authorityScopes};
 const [endpoints,setEndpoints]=useState<NotificationEndpoint[]>([]),[summary,setSummary]=useState<DeliverySummary[]>([]),[mine,setMine]=useState<MyNotificationDelivery[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const canDispatch=canAuthority(viewer,"communications_publish")||canAuthority(viewer,"communications_approve")||canAuthority(viewer,"institutional_leadership");
 const reload=useCallback(async()=>{const [channels,delivery,myDeliveries]=await Promise.all([loadMyNotificationEndpoints(),canDispatch?loadDeliverySummary():Promise.resolve([]),loadMyNotificationDeliveries()]);setEndpoints(channels);setSummary(delivery);setMine(myDeliveries);},[canDispatch]);
 useEffect(()=>{reload().catch(reason=>setError(errorText(reason)));},[reload]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await reload();setMessage(success);}catch(reason){setError(errorText(reason));}finally{setBusy(false);}}
 const active=(channel:string)=>endpoints.some(item=>item.channel===channel&&item.enabled&&item.verified);
 return <section className="panel notification-delivery-panel"><div className="panel-title"><BellRing/><div><span>DELIVERY CHANNELS</span><h3>In-app first, verified external channels when enabled</h3><p>DREEM only marks external delivery successful after the provider accepts it.</p></div></div>{error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
   <div className="prereq-grid"><article className="ready"><strong>In-app</strong><p>Always available for approved school accounts.</p></article>{(["email","sms","whatsapp"] as const).map(channel=><article className={active(channel)?"ready":"missing"} key={channel}><strong>{channel==="email"?<Mail/>:<MessageSquareText/>}{channel.toUpperCase()}</strong><p>{active(channel)?"Verified account contact enabled.":"Uses your verified DREEM account contact."}</p>{active(channel)?<button disabled={busy} onClick={()=>void run(()=>disableNotificationChannel(channel),`${channel} notifications disabled.`)}>Disable</button>:<button disabled={busy} onClick={()=>void run(()=>enableVerifiedAuthChannel(channel),`${channel} notifications enabled from your verified account contact.`)}>Enable verified {channel}</button>}</article>)}</div>
   {canDispatch?<><div className="card-actions"><button className="primary" disabled={busy} onClick={()=>void run(async()=>{const result=await dispatchQueuedNotifications();return result;},"Queued external notifications processed. Any provider failure remains available for retry.")}><Send/>Process queued delivery</button></div><div className="compact-table">{summary.slice(0,20).map((item,index)=><div className="document-row" key={`${item.announcementId}-${item.channel}-${item.status}-${index}`}><strong>{item.channel} · {item.status}</strong><span>{item.deliveries} delivery record{item.deliveries===1?"":"s"}</span><small>{new Date(item.lastUpdatedAt).toLocaleString()}</small></div>)}{!summary.length?<p>No external delivery activity yet.</p>:null}</div></>:null}
   <div className="notification-receipts"><div className="panel-title"><MessageSquareText/><div><span>MY DELIVERY RECEIPTS</span><h3>Messages that reached your account</h3><p>Queued, dispatched, delivered and acknowledged are shown separately. Acknowledgement requires your action.</p></div></div>{mine.slice(0,12).map(item=><article className="document-row" key={item.id}><div><strong>{item.title}</strong><span>{item.channel} · {item.status}</span><small>{new Date(item.queuedAt).toLocaleString()}</small></div>{item.status!=="acknowledged"&&!["failed","cancelled"].includes(item.status)?<button disabled={busy} onClick={()=>void run(()=>acknowledgeNotificationDelivery(item.id),"Message acknowledged.")}>Acknowledge</button>:null}</article>)}{!mine.length?<p>No personal delivery records yet.</p>:null}</div>
 </section>;
}
