import { useState, type FormEvent } from "react";
import { BadgeCheck, GraduationCap, MailPlus, RefreshCw, UserPlus } from "lucide-react";
import type { AccessMembership, AssessmentCommand, AttendanceCommand, EnrollmentPayload, StaffInvitation } from "../domain/types";
import { createIdempotencyKey } from "../domain/rules";
import type { WorkspaceData } from "../lib/repository";
import { canAuthority } from "../lib/access";

type Status = { tone: "idle" | "success" | "error"; message: string };
const roleOptions:{value:StaffInvitation["role"];label:string;purpose:string}[]=[
  {value:"principal",label:"Principal",purpose:"School leadership and approvals"},
  {value:"administrator",label:"Administrator",purpose:"Admissions, people and daily administration"},
  {value:"academic_head",label:"Academic head",purpose:"Teaching, timetable and academic review"},
  {value:"bursar",label:"Bursar / cashier",purpose:"Collections and cashier work"},
  {value:"accountant",label:"Accountant",purpose:"Finance review and confirmation"},
  {value:"teacher",label:"Teacher",purpose:"Classes, attendance and assessment"},
  {value:"tutor",label:"Tutor",purpose:"Learner follow-up and support"},
  {value:"transport_manager",label:"Transport manager",purpose:"Routes, vehicles and transport operations"},
  {value:"driver",label:"Driver",purpose:"Assigned school journeys"},
  {value:"security_guard",label:"Security / gate officer",purpose:"Safe learner release at the gate"},
  {value:"auditor",label:"Auditor",purpose:"Read-only school review"},
];
function readableError(reason:unknown){if(reason instanceof Error&&reason.message)return reason.message;return "This action could not be completed. Check your access and try again.";}

export default function OperationalWorkflowsView({workspace,onInviteStaff,onUpdateAccess,onEnrolLearner,onIssueCredential,onRecordAttendance,onRecordAssessment,onRefresh}:{workspace:WorkspaceData;onInviteStaff:(input:{email:string;fullName:string;role:StaffInvitation["role"];idempotencyKey:string})=>Promise<unknown>;onUpdateAccess:(membershipId:string,status:AccessMembership["status"])=>Promise<unknown>;onEnrolLearner:(input:EnrollmentPayload)=>Promise<{studentId:string;matricule:string}>;onIssueCredential:(studentId:string,validUntil:string,idempotencyKey:string)=>Promise<{credentialId:string;verificationToken:string}>;onRecordAttendance:(command:AttendanceCommand)=>Promise<{sessionId:string;recordedCount:number}>;onRecordAssessment:(command:AssessmentCommand)=>Promise<{assessmentId:string;marksCount:number}>;onRefresh:()=>Promise<void>}){
  void onIssueCredential;void onRecordAttendance;void onRecordAssessment;
  const [status,setStatus]=useState<Status>({tone:"idle",message:""});
  const classes=workspace.setup.classes.length?workspace.setup.classes.map(item=>item.name):Array.from(new Set(workspace.learners.map(item=>item.className)));
  const canManageAccess=canAuthority(workspace.viewer,"staff_management");
  const pending=workspace.operations.memberships.filter(item=>item.status==="pending");
  async function run(action:()=>Promise<string>){setStatus({tone:"idle",message:"Saving…"});try{const message=await action();await onRefresh();setStatus({tone:"success",message});}catch(reason){setStatus({tone:"error",message:readableError(reason)});}}
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);await run(async()=>{await onInviteStaff({email:String(form.get("email")??""),fullName:String(form.get("fullName")??""),role:String(form.get("role")??"teacher") as StaffInvitation["role"],idempotencyKey:createIdempotencyKey("staff-invite")});element.reset();return "Invitation sent.";});}
  async function enrol(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);await run(async()=>{const learner=await onEnrolLearner({fullName:String(form.get("fullName")??""),className:String(form.get("className")??""),dateOfBirth:String(form.get("dateOfBirth")||""),sex:String(form.get("sex")||"") as EnrollmentPayload["sex"],guardianName:String(form.get("guardianName")??""),guardianPhone:String(form.get("guardianPhone")??""),guardianEmail:String(form.get("guardianEmail")||""),relationship:String(form.get("relationship")||"guardian"),openingBalance:Number(form.get("openingBalance")||0),idempotencyKey:createIdempotencyKey("learner-enrolment")});element.reset();return `Learner enrolled with matricule ${learner.matricule}.`;});}
  return <div className="content operations-workspace role-workspace">
    <section className="role-hero"><div><span className="eyebrow">SCHOOL OPERATIONS · TODAY</span><h2>{pending.length?`${pending.length} access request${pending.length===1?"":"s"} waiting`:"People and access"}</h2><p>Manage who works in DREEM and the access they need. Teaching, marks, learner cards and admissions now stay in their own workspaces.</p></div><button className="primary" onClick={()=>run(async()=>{await onRefresh();return "Workspace refreshed.";})}><RefreshCw/>Refresh</button></section>
    {status.message?<div className={`form-status ${status.tone==="error"?"error":"success"}`}><BadgeCheck/>{status.message}</div>:null}
    <section className="operations-object"><header><div><span>PEOPLE</span><h3>Invite staff</h3><p>Add the person first. Their school title and permissions can be adjusted after they join.</p></div><MailPlus/></header><form className="settings-form compact-action-form" onSubmit={invite}><div className="form-grid"><label>Full name<input name="fullName" autoComplete="name" required/></label><label>Email<input name="email" type="email" inputMode="email" autoComplete="email" required/></label><label>School role<select name="role" defaultValue="teacher">{roleOptions.map(role=><option key={role.value} value={role.value}>{role.label} — {role.purpose}</option>)}</select></label></div><button className="primary" type="submit"><UserPlus/>Send invitation</button></form></section>
    <section className="operations-object"><header><div><span>ACCESS REQUESTS</span><h3>{pending.length?`${pending.length} waiting for review`:"No request waiting"}</h3><p>Approve only people who should enter this school workspace.</p></div></header><div className="people-review-list">{pending.map(membership=><article key={membership.id}><div><strong>{membership.name}</strong><small>{membership.role.replaceAll("_"," ")}</small></div>{canManageAccess?<div className="row-actions"><button type="button" onClick={()=>run(async()=>{await onUpdateAccess(membership.id,"approved");return `${membership.name} approved.`;})}>Approve</button><button type="button" className="danger-link" onClick={()=>run(async()=>{await onUpdateAccess(membership.id,"rejected");return `${membership.name} rejected.`;})}>Reject</button></div>:<span className="status-pill">Waiting</span>}</article>)}{!pending.length?<p className="empty-copy">New access requests will appear here.</p>:null}</div></section>
    <details className="exception-drawer"><summary><GraduationCap/><span><strong>Direct enrolment</strong><small>Use only when there is no admissions application</small></span></summary><div className="exception-drawer-body"><p>Normal enrolment should start in Admissions. Use this only for a walk-in, approved import or historical learner.</p><form className="settings-form" onSubmit={enrol}><div className="form-grid"><label>Full name<input name="fullName" required/></label><label>Class<input name="className" list="classes" required/></label><label>Date of birth<input name="dateOfBirth" type="date"/></label><label>Sex<select name="sex" defaultValue=""><option value="">Not set</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label><label>Guardian<input name="guardianName" required/></label><label>Guardian phone<input name="guardianPhone"/></label><label>Guardian email<input name="guardianEmail" type="email"/></label><label>Relationship<input name="relationship" defaultValue="parent"/></label><label>Opening fee balance<input name="openingBalance" type="number" min="0" step="1" defaultValue="0"/></label></div><button className="primary" type="submit"><GraduationCap/>Create learner record</button></form></div></details>
    <datalist id="classes">{classes.map(name=><option key={name} value={name}/>)}</datalist>
  </div>;
}
