import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Camera, Printer, ShieldCheck, UserCheck, Users, Ban, PauseCircle, RotateCcw } from "lucide-react";
import { uploadCollectorPhoto, removeIdentityMedia } from "../lib/identity";
import { authorizeLearnerCollector, type WorkspaceData } from "../lib/repository";
import { loadPickupCircle, setPickupCircleMemberStatus, type PickupCircleMember } from "../lib/pickupCircle";
import { makeQrMatrix } from "../lib/qr";

function expiryDefault(){const value=new Date();value.setMonth(value.getMonth()+6);return value.toISOString().slice(0,10);}
function errorText(reason:unknown){if(reason instanceof Error&&reason.message)return reason.message;if(reason&&typeof reason==="object"&&"message" in reason&&typeof reason.message==="string")return reason.message;return "Pickup Circle operation could not be completed.";}
function CollectorQr({value}:{value:string}){const matrix=useMemo(()=>makeQrMatrix(value),[value]);const quiet=4,size=matrix.length+quiet*2;return <svg className="credential-qr" viewBox={`0 0 ${size} ${size}`} role="img" aria-label="Collector authorization QR code" shapeRendering="crispEdges"><rect width={size} height={size} fill="white"/>{matrix.flatMap((row,y)=>row.map((dark,x)=>dark?<rect key={`${x}-${y}`} x={x+quiet} y={y+quiet} width="1" height="1" fill="black"/>:null))}</svg>;}

export default function PickupAuthorizationStudio({workspace}:{workspace:WorkspaceData}){
 const [studentId,setStudentId]=useState(workspace.learners[0]?.id??"");const [circle,setCircle]=useState<PickupCircleMember[]>([]);const [loadingCircle,setLoadingCircle]=useState(false);const [photo,setPhoto]=useState<File|null>(null);const [preview,setPreview]=useState("");const [token,setToken]=useState("");const [authorizedName,setAuthorizedName]=useState("");const [authorizedRelationship,setAuthorizedRelationship]=useState("");const [validUntil,setValidUntil]=useState(expiryDefault());const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const refreshCircle=useCallback(async()=>{if(!studentId){setCircle([]);return;}setLoadingCircle(true);try{setCircle(await loadPickupCircle(studentId));}catch(reason){setError(errorText(reason));}finally{setLoadingCircle(false);}},[studentId]);
 useEffect(()=>{void refreshCircle();},[refreshCircle]);
 function choosePhoto(file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Choose a JPG, PNG or WebP collector photograph.");return;}if(file.size>5*1024*1024){setError("Collector photographs must be 5 MB or smaller.");return;}if(preview)URL.revokeObjectURL(preview);setPhoto(file);setPreview(URL.createObjectURL(file));setError("");setToken("");}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const fullName=String(form.get("fullName")??"").trim(),relationship=String(form.get("relationship")??"").trim(),phoneLast4=String(form.get("phoneLast4")??"").trim(),evidenceNote=String(form.get("evidence")??"").trim();if(!photo){setError("Take or upload the collector photograph before authorization.");return;}setBusy(true);setError("");setMessage("");setToken("");let storedPath="";try{const uploaded=await uploadCollectorPhoto(studentId,photo);storedPath=uploaded.path;const result=await authorizeLearnerCollector({studentId,fullName,relationship,phoneLast4,photoUrl:storedPath,validUntil:validUntil?new Date(`${validUntil}T23:59:59`).toISOString():undefined,evidenceNote,idempotencyKey:`collector:${crypto.randomUUID()}`});setToken(result.collectorToken);setAuthorizedName(fullName);setAuthorizedRelationship(relationship);setMessage("Pickup Circle updated. Save or print the new member QR now; DREEM retains only its secure hash.");await refreshCircle();}catch(reason){if(storedPath){try{await removeIdentityMedia(storedPath);}catch{/* preserve original error */}}setError(errorText(reason));}finally{setBusy(false);}}
 async function changeStatus(member:PickupCircleMember,status:"active"|"suspended"|"revoked"){const label=status==="active"?"reactivate":status;const reason=window.prompt(`Reason to ${label} ${member.fullName}?`);if(!reason)return;setBusy(true);setError("");try{await setPickupCircleMemberStatus(member.collectorId,status,reason);setMessage(`${member.fullName} is now ${status}. Gate verification uses this status immediately.`);await refreshCircle();}catch(reasonValue){setError(errorText(reasonValue));}finally{setBusy(false);}}
 function printCollectorPass(){document.documentElement.classList.add("print-collector");const cleanup=()=>document.documentElement.classList.remove("print-collector");window.addEventListener("afterprint",cleanup,{once:true});window.print();window.setTimeout(cleanup,1000);}
 const learner=workspace.learners.find(item=>item.id===studentId);
 return <section className="panel pickup-authorization credential-card-controls">
  <div className="panel-title"><Users/><div><span>LEARNER PICKUP CIRCLE</span><h3>Trusted people allowed to collect this learner</h3><p>Keep parents, relatives, nanny/tutor, family driver and temporary trusted people in one auditable safety circle.</p></div></div>
  <div className="pickup-circle-list" aria-label="Pickup Circle lifecycle">
   <div className="panel-title"><ShieldCheck/><div><span>HOW THIS CYCLE WORKS</span><h3>Authorize → use at gate → review → suspend, revoke or renew</h3><p>1. Verify guardian authority and collector identity. 2. Create the individual credential. 3. Gate staff match learner + collector credentials. 4. Every release or refusal becomes history. 5. School staff can suspend, revoke or reactivate at any time.</p></div></div>
  </div>
  {error&&<div className="form-status error">{error}</div>}{message&&<div className="form-status success"><ShieldCheck/>{message}</div>}
  <label>Learner<select value={studentId} onChange={event=>{setStudentId(event.target.value);setToken("");setMessage("");}}>{workspace.learners.map(item=><option value={item.id} key={item.id}>{item.name} · {item.matricule}</option>)}</select></label>
  <div className="pickup-circle-list" aria-live="polite"><div className="panel-title"><UserCheck/><div><span>1 · CURRENT PICKUP CIRCLE</span><h3>{loadingCircle?"Loading Pickup Circle…":`${circle.filter(x=>x.status==="active").length} active · ${circle.length} total`}</h3><p>Review who is currently trusted before adding or changing anyone.</p></div></div>{!loadingCircle&&circle.length===0&&<p className="empty-state">No trusted collector has been registered for this learner yet. Continue to step 2 to add the first person.</p>}{circle.map(member=><article className="pickup-circle-member" key={member.collectorId}><div className="credential-photo">{member.photoUrl?<span aria-label="Collector photograph secured">Photo secured</span>:<UserCheck/>}</div><div><strong>{member.fullName}</strong><p>{member.relationship}{member.phoneLast4?` · phone •••• ${member.phoneLast4}`:""}</p><small>Status: {member.status}{member.validUntil?` · until ${new Date(member.validUntil).toLocaleDateString()}`:""}{member.lastReleaseAt?` · last gate ${member.lastDecision} ${new Date(member.lastReleaseAt).toLocaleDateString()}`:""}</small></div><div className="pickup-circle-actions">{member.status==="active"?<><button type="button" disabled={busy} onClick={()=>void changeStatus(member,"suspended")}><PauseCircle/>Suspend</button><button type="button" disabled={busy} onClick={()=>void changeStatus(member,"revoked")}><Ban/>Revoke</button></>:member.status==="suspended"?<><button type="button" disabled={busy} onClick={()=>void changeStatus(member,"active")}><RotateCcw/>Reactivate</button><button type="button" disabled={busy} onClick={()=>void changeStatus(member,"revoked")}><Ban/>Revoke</button></>:null}</div></article>)}</div>
  <div className="panel-title"><UserCheck/><div><span>2 · AUTHORIZE A PERSON</span><h3>Verify identity and add them to the Pickup Circle</h3><p>Capture the minimum identity evidence, set validity, then DREEM creates that person’s independent credential.</p></div></div>
  <form className="settings-form" onSubmit={submit}><div className="form-grid"><label>Collector full name<input name="fullName" minLength={3} required/></label><label>Relationship<input name="relationship" required placeholder="Mother, father, aunt, uncle, nanny, driver…"/></label><label>Final 4 phone digits<input name="phoneLast4" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="7739"/></label><label>Authorization valid until<input type="date" value={validUntil} min={new Date().toISOString().slice(0,10)} onChange={event=>setValidUntil(event.target.value)}/></label><label>Guardian authorization evidence<input name="evidence" required placeholder="Consent recorded; identity checked; source noted"/></label></div><div className="collector-photo-capture"><div className="credential-photo">{preview?<img src={preview} alt="Collector preview"/>:<span><Camera/></span>}</div><label className="primary"><Camera/>{photo?"Retake / replace collector photo":"Take collector photograph"}<input hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={event=>choosePhoto(event.target.files?.[0])}/></label></div><button className="primary" disabled={busy} type="submit"><ShieldCheck/>{busy?"Securing authorization…":"Authorize person and create gate QR"}</button></form>
  {token&&<article className="collector-pass"><div>{preview&&<img src={preview} alt={`${authorizedName} collector`}/>}</div><div><small>3 · ACTIVE PICKUP CREDENTIAL / RETRAIT AUTORISÉ</small><h3>{authorizedName}</h3><p>{authorizedRelationship} · {learner?.name}</p><strong>Valid until {validUntil}</strong></div><CollectorQr value={token}/><footer><small>Next: use this credential together with the learner badge at DREEM Secure Gate. Suspended, revoked or expired credentials cannot authorize release.</small><button type="button" onClick={printCollectorPass}><Printer/>Print collector pass</button></footer></article>}
 </section>;
}
