import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Eye, ShieldAlert, ShieldCheck } from "lucide-react";
import {loadPolicyRules,savePolicyRule,seedRecommendedPolicies,simulatePolicyRule,type PolicyActionLevel,type PolicyCode,type PolicyRule,type PolicyService} from "../lib/policyEngine";
import { userFacingError } from "../lib/userFacingError";

const labels:Record<PolicyCode,{title:string;help:string;unit:string;domain:string;ownerScope:string}>={
 attendance_followup:{title:"Attendance follow-up",help:"Show learners for follow-up when attendance falls below this level.",unit:"%",domain:"attendance",ownerScope:"academics_delivery"},
 missing_work_followup:{title:"Missing school work",help:"Show repeated overdue work to the teacher before it becomes a bigger problem.",unit:" tasks",domain:"learning",ownerScope:"academics_delivery"},
 fee_overdue_followup:{title:"Overdue fees",help:"Show overdue fees to the finance team without automatically blocking the learner.",unit:" overdue item(s)",domain:"finance",ownerScope:"finance_collection"},
};
const services:PolicyService[]=["exam","report","trip","renewal","graduation","transport","boarding","library","activity","document"];
const errorText=(reason:unknown)=>userFacingError(reason,"School rules could not be updated. Nothing has been assumed saved. Check your connection or access and try again.");

export default function PolicyStudio(){
 const[rules,setRules]=useState<PolicyRule[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[advanced,setAdvanced]=useState(false),[impact,setImpact]=useState<Record<string,string>>({});
 async function refresh(){setError("");setRules(await loadPolicyRules());}
 useEffect(()=>{void refresh().catch(reason=>setError(errorText(reason)));},[]);
 const byCode=useMemo(()=>new Map(rules.map(rule=>[rule.code,rule])),[rules]),codes=Object.keys(labels) as PolicyCode[];
 async function seed(){setBusy("seed");setError("");setMessage("");try{await seedRecommendedPolicies();await refresh();setMessage("Recommended school rules are ready.");}catch(reason){setError(errorText(reason));}finally{setBusy("");}}
 function update(code:PolicyCode,patch:Partial<PolicyRule>){setRules(current=>current.map(rule=>rule.code===code?{...rule,...patch}:rule));}
 async function preview(code:PolicyCode){const rule=byCode.get(code);if(!rule)return;setBusy("preview:"+code);setError("");try{const result=await simulatePolicyRule(code,rule.threshold);setImpact(current=>({...current,[code]:result.affected+" of "+result.total+" learners would need follow-up today."}));}catch(reason){setError(errorText(reason));}finally{setBusy("");}}
 async function save(code:PolicyCode){const rule=byCode.get(code);if(!rule)return;setBusy("save:"+code);setError("");setMessage("");try{await savePolicyRule({code:rule.code,name:rule.name,domain:rule.domain,threshold:rule.threshold,actionLevel:rule.actionLevel,targetService:rule.targetService,ownerScope:rule.ownerScope,enabled:rule.enabled});await refresh();setMessage(labels[code].title+" saved.");}catch(reason){setError(errorText(reason));}finally{setBusy("");}}
 return <section className="school-rules-studio">
  <header className="object-header"><div><span>SCHOOL RULES</span><h3>Decide when DREEM should bring something to your attention</h3><p>Start with simple follow-up rules. DREEM can flag the right people, but important decisions still stay with school staff.</p></div><ShieldCheck/></header>
  {error?<div className="form-status error" role="alert"><ShieldAlert/>{error}</div>:null}{message?<div className="form-status success" role="status"><BadgeCheck/>{message}</div>:null}
  {!rules.length?<div className="recommended-start"><small>RECOMMENDED START</small><strong>Use sensible defaults</strong><p>Begin with attendance, missing work and overdue-fee follow-up. You can adjust them later.</p><button type="button" className="primary" disabled={busy==="seed"} onClick={()=>void seed()}>Use recommended rules</button></div>:null}
  <div className="policy-rule-grid">{codes.map(code=>{const rule=byCode.get(code);if(!rule)return null;const meta=labels[code];return <article className="policy-rule-card" key={code}><div><strong>{meta.title}</strong><small>{meta.help}</small></div><label>Bring this up when<span className="policy-threshold"><input aria-label={meta.title+" threshold"} type="number" min={code==="attendance_followup"?0:1} max={code==="attendance_followup"?100:999} value={rule.threshold} onChange={e=>update(code,{threshold:Number(e.target.value)})}/><small>{meta.unit}</small></span></label><label className="policy-toggle"><input type="checkbox" checked={rule.enabled} onChange={e=>update(code,{enabled:e.target.checked})}/><span>{rule.enabled?"On":"Off"}</span></label>{advanced?<div className="advanced-settings"><label>What should happen<select value={rule.actionLevel} onChange={e=>update(code,{actionLevel:e.target.value as PolicyActionLevel})}><option value="notify">Show it to staff</option><option value="remind">Send a reminder</option><option value="review">Ask staff to review</option><option value="restrict_specific_service">Ask leadership to consider a service restriction</option></select></label>{rule.actionLevel==="restrict_specific_service"?<label>Service<select value={rule.targetService??"exam"} onChange={e=>update(code,{targetService:e.target.value as PolicyService})}>{services.map(service=><option value={service} key={service}>{service.replaceAll("_"," ")}</option>)}</select><small>This never happens automatically. A school leader must review and record the reason.</small></label>:null}</div>:null}{impact[code]?<div className="care-assurance"><Eye/><span><strong>Right now</strong><small>{impact[code]}</small></span></div>:null}<div className="policy-actions"><button type="button" disabled={busy!==""} onClick={()=>void preview(code)}>See who this affects</button><button type="button" className="primary" disabled={busy!==""} onClick={()=>void save(code)}>Save</button></div></article>;})}</div>
  {rules.length?<button type="button" className="secondary" onClick={()=>setAdvanced(value=>!value)}>{advanced?"Hide extra options":"More options"}</button>:null}
  <div className="brand-live-note"><strong>Important:</strong> a rule can bring something to the right person; it does not make a serious decision on its own.</div>
 </section>;
}
