import { Search, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import type { LearnerSummary } from "../domain/types";
import { loadLearnerDirectoryPage } from "../lib/learnerDirectory";
import { userFacingError } from "../lib/userFacingError";

export default function RemoteLearnerPicker({name,label="Learner",requireOpenFee=false,onSelect}:{name:string;label?:string;requireOpenFee?:boolean;onSelect?:(learner:LearnerSummary|undefined)=>void}){
 const[query,setQuery]=useState(""),[rows,setRows]=useState<LearnerSummary[]>([]),[selected,setSelected]=useState<LearnerSummary|undefined>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{setBusy(true);loadLearnerDirectoryPage({page:0,pageSize:20,query}).then(result=>{if(active)setRows(requireOpenFee?result.rows.filter(item=>item.feeAccountId&&Number(item.feeBalance)>0):result.rows)}).catch(reason=>{if(active)setError(userFacingError(reason,"Learners could not be searched. Check your connection and try again."))}).finally(()=>{if(active)setBusy(false)});},query.trim()?250:0);return()=>{active=false;window.clearTimeout(timer)};},[query,requireOpenFee]);
 function choose(learner:LearnerSummary){setSelected(learner);setQuery(learner.name);setRows([]);setError("");onSelect?.(learner);}
 return <div className="remote-learner-picker"><label>{label}<span className="remote-learner-search"><Search size={16}/><input value={query} onChange={event=>{setQuery(event.target.value);setSelected(undefined);onSelect?.(undefined)}} placeholder="Search name, matricule or class" autoComplete="off" aria-autocomplete="list"/></span></label><input type="hidden" name={name} value={selected?.id??""}/>{selected?<div className="selected-learner"><UserRound/><span><strong>{selected.name}</strong><small>{selected.matricule} · {selected.className}{requireOpenFee&&selected.feeBalance!==undefined?` · ${new Intl.NumberFormat("fr-FR").format(selected.feeBalance)} FCFA balance`:""}</small></span></div>:null}{!selected&&query?<div className="learner-picker-results" role="listbox" aria-label={`${label} search results`}>{busy?<p>Searching…</p>:rows.length?rows.map(item=><button type="button" role="option" aria-selected="false" key={item.id} onClick={()=>choose(item)}><strong>{item.name}</strong><small>{item.matricule} · {item.className}{requireOpenFee&&item.feeBalance!==undefined?` · ${new Intl.NumberFormat("fr-FR").format(item.feeBalance)} FCFA`:""}</small></button>):<p>No matching learner found.</p>}</div>:null}{error?<small className="form-status error" role="alert">{error}</small>:null}</div>;
}
