import { AlertTriangle, BookOpenCheck, BusFront, CircleDollarSign, ClipboardCheck, FolderHeart, MessageSquareMore, ShieldCheck, UserPlus } from "lucide-react";
import type { Role } from "../domain/types";
import type { WorkspaceData } from "../lib/repository";
import type { ViewKey } from "./Shell";
type QueueItem={id:string;view:ViewKey;title:string;detail:string;count:number;tone:"urgent"|"attention"|"normal";owner:string;icon:React.ReactNode};
const leadershipRoles:Role[]=["platform_founder","school_owner","principal","administrator","academic_head"];
export default function SchoolCommandCentre({workspace,onNavigate}:{workspace:WorkspaceData;onNavigate:(view:ViewKey)=>void}){
 const role=workspace.viewer.role,ownerView=["platform_founder","school_owner","principal"].includes(role);
 const admissionPending=workspace.admissions.filter(item=>!["admitted","rejected","withdrawn"].includes(item.status)).length;
 const lessonReview=workspace.academics.lessonPlans.filter(item=>item.status==="submitted").length,assessmentReview=workspace.academics.assessments.filter(item=>item.status==="submitted").length;
 const careOpen=workspace.cases.filter(item=>!["resolved","closed"].includes(item.status)).length,urgentCare=workspace.cases.filter(item=>!["resolved","closed"].includes(item.status)&&["urgent","critical"].includes(item.priority)).length;
 const openSignals=workspace.signals.filter(item=>!["resolved","closed"].includes(item.status)).length,urgentSignals=workspace.signals.filter(item=>!["resolved","closed"].includes(item.status)&&["urgent","safeguarding"].includes(item.severity)).length;
 const openTrips=workspace.transport.trips.filter(item=>!["completed","cancelled"].includes(item.status)).length,delayedTrips=workspace.transport.trips.filter(item=>item.status==="delayed").length;
 const financeExceptions=workspace.finance.openExceptions,cashAwaiting=workspace.finance.cashAwaitingDeposit;
 const can=(view:ViewKey)=>ownerView||role==="administrator"&&(["admissions","operations","learners","signals","studio"] as ViewKey[]).includes(view)||role==="academic_head"&&(["academics","learning","learners","teachers","care","signals","studio"] as ViewKey[]).includes(view);
 const all:QueueItem[]=[
 {id:"admissions",view:"admissions",title:"Admissions waiting",detail:"Review, decide, offer or enrol. Accepted learners should flow into school records without re-entry.",count:admissionPending,tone:admissionPending?"attention":"normal",owner:"Admissions",icon:<UserPlus/>},
 {id:"academic",view:"academics",title:"Teaching awaiting review",detail:`${lessonReview} lesson plan(s) and ${assessmentReview} assessment(s) need academic review.`,count:lessonReview+assessmentReview,tone:lessonReview+assessmentReview?"attention":"normal",owner:"Academic Head",icon:<BookOpenCheck/>},
 {id:"care",view:"care",title:"Protected learner concerns",detail:urgentCare?`${urgentCare} urgent/critical case(s) require authorised attention.`:"Only authorised safeguarding staff can open protected detail.",count:careOpen,tone:urgentCare?"urgent":careOpen?"attention":"normal",owner:"Safeguarding",icon:<FolderHeart/>},
 {id:"finance",view:"finance",title:"Money needing control",detail:cashAwaiting?`${cashAwaiting.toLocaleString("fr-FR")} FCFA is still in custody or awaiting settlement.`:"Collections, reconciliation and exceptions are under control.",count:financeExceptions,tone:financeExceptions?"urgent":cashAwaiting?"attention":"normal",owner:"Finance",icon:<CircleDollarSign/>},
 {id:"transport",view:"transport",title:"Transport operating now",detail:delayedTrips?`${delayedTrips} delayed journey(s) need intervention.`:"See active school journeys and exceptions.",count:openTrips,tone:delayedTrips?"urgent":openTrips?"attention":"normal",owner:"Transport Control",icon:<BusFront/>},
 {id:"signals",view:"signals",title:"Messages needing follow-up",detail:urgentSignals?`${urgentSignals} urgent/safeguarding message(s) require routing.`:"Unresolved school feedback and follow-up.",count:openSignals,tone:urgentSignals?"urgent":openSignals?"attention":"normal",owner:"School Office",icon:<MessageSquareMore/>}];
 const candidates=all.filter(item=>can(item.view)),active=candidates.filter(item=>item.count>0||item.id==="finance"&&cashAwaiting>0),priority=financeExceptions+urgentCare+urgentSignals+delayedTrips;
 if(!leadershipRoles.includes(role))return null;
 return <div className="content role-workspace command-today"><section className="page-intro"><div><span>{ownerView?"SCHOOL CONTROL · TODAY":"MY SCHOOL WORK · TODAY"}</span><h2>{ownerView?priority?`${priority} issue${priority===1?"":"s"} need leadership attention`:"The school is operating without a priority exception":"What needs your attention now?"}</h2><p>{ownerView?"This is the owner/principal control plane: exceptions, money in custody, academic approvals, safeguarding and live operations. Open any item to see the responsible workflow and evidence.":"DREEM shows only work owned by your approved role."}</p></div><div className="care-assurance"><ShieldCheck/><span><strong>{active.length} active area{active.length===1?"":"s"}</strong><small>{ownerView?"School-wide, permission-aware view":"Scoped to your role"}</small></span></div></section>
 <div className="command-summary"><article><CircleDollarSign/><span><strong>{cashAwaiting.toLocaleString("fr-FR")}</strong><small>FCFA awaiting deposit/settlement</small></span></article><article><ClipboardCheck/><span><strong>{admissionPending}</strong><small>admissions in progress</small></span></article><article><AlertTriangle/><span><strong>{priority}</strong><small>priority exceptions</small></span></article><article><BusFront/><span><strong>{openTrips}</strong><small>journeys operating</small></span></article></div>
 <section className="command-queue-grid">{candidates.map(item=><article className={`command-queue ${item.tone}`} key={item.id}><div className="command-queue-icon">{item.icon}</div><div><span>{item.owner}</span><h3>{item.title}</h3><strong>{item.count}</strong><p>{item.detail}</p><button className={item.count>0?"primary":""} onClick={()=>onNavigate(item.view)}>{item.count>0?"Review and act":"Open evidence"}</button></div></article>)}</section></div>;
}
