import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { CheckCircle2, ImagePlus, Palette, Printer, Settings2, ShieldCheck, Upload } from "lucide-react";
import type { AccessMembership, SchoolBrand, SchoolSetup } from "../domain/types";
import InstitutionAuthorityStudio from "./InstitutionAuthorityStudio";
import PolicyStudio from "./PolicyStudio";
import { buildClassPack, classPacks, type ClassPackId } from "../domain/classPacks";

const palettes=[
 {name:"Forest",primary:"#123b2c",accent:"#c9df83"},{name:"Royal",primary:"#173f70",accent:"#f0c75e"},{name:"Crimson",primary:"#6f1d2c",accent:"#f2cf72"},{name:"Teal",primary:"#075d5b",accent:"#a7e0d2"},{name:"Charcoal",primary:"#263238",accent:"#90caf9"},
] as const;
function normalizePrefix(value:string){return value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8)}
function contrast(hex:string){const value=hex.replace("#","");const rgb=[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}

export function SchoolStudioView({brand,setup,memberships,onSave,onSaveSetup,onUploadLogo,onAuthorityChanged}:{brand:SchoolBrand;setup:SchoolSetup;memberships?:AccessMembership[];onSave:(brand:SchoolBrand)=>Promise<void>;onSaveSetup:(setup:SchoolSetup)=>Promise<void>;onUploadLogo:(file:File)=>Promise<string>;onAuthorityChanged?:()=>Promise<void>}){
 const[draft,setDraft]=useState(brand),[setupDraft,setSetupDraft]=useState(setup),[status,setStatus]=useState(""),[failed,setFailed]=useState(false),[uploading,setUploading]=useState(false),[selectedPack,setSelectedPack]=useState<ClassPackId>("bilingual-primary"),[advancedBrand,setAdvancedBrand]=useState(false);
 useEffect(()=>setDraft(brand),[brand]);useEffect(()=>setSetupDraft(setup),[setup]);
 const readable=useMemo(()=>Math.abs(contrast(draft.primaryColor)-contrast(draft.accentColor))>=.35,[draft.primaryColor,draft.accentColor]);
 function field<K extends keyof SchoolBrand>(key:K,value:SchoolBrand[K]){setDraft(current=>({...current,[key]:value}))}
 async function saveIdentity(event:FormEvent){event.preventDefault();setFailed(false);setStatus("Saving school identity…");try{if(!readable)throw new Error("Choose colours with stronger contrast so text, buttons and printed IDs remain readable.");await onSave(draft);setStatus("School identity saved.");}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"School identity could not be saved.")}}
 async function logo(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setUploading(true);setFailed(false);setStatus("Uploading logo…");try{const logoUrl=await onUploadLogo(file);field("logoUrl",logoUrl);setStatus("Logo uploaded. Save identity when you are ready to publish it.");}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"Logo could not be uploaded.");}finally{setUploading(false);event.target.value=""}}
 async function saveStructure(event:FormEvent){event.preventDefault();setFailed(false);setStatus("Saving school structure…");try{await onSaveSetup(setupDraft);setStatus("School structure saved.");}catch(reason){setFailed(true);const detail=reason instanceof Error?reason.message:(reason&&typeof reason==="object"&&"message" in reason?String((reason as {message?:unknown}).message):String(reason));setStatus(detail||"School structure could not be saved.");}}
 function applyPack(){const existing=setupDraft.academicYears.length+setupDraft.terms.length+setupDraft.classes.length+setupDraft.subjects.length;setSetupDraft(buildClassPack(selectedPack));setFailed(false);setStatus(existing?"Starting point loaded as a draft. Nothing saved has changed yet.":"Starting point loaded. Review it before saving.");}
 const setupCount=setupDraft.academicYears.length+setupDraft.terms.length+setupDraft.classes.length+setupDraft.subjects.length;
 return <div className="content studio-workspace role-workspace">
  <section className="role-hero"><div><span className="eyebrow">SCHOOL STUDIO</span><h2>Make DREEM fit your school</h2><p>Set the school identity first. Then open only the parts you need: structure, school rules, and staff responsibilities.</p></div><div className="role-hero-status"><span className="status-pill"><ShieldCheck size={14}/>{setupCount?"School configured":"Setup in progress"}</span></div></section>
  {status?<div className={`form-status ${failed?"error":"success"}`}><CheckCircle2/>{status}</div>:null}
  <section className="studio-overview"><article><span>IDENTITY</span><strong>{draft.shortName||draft.name}</strong><small>{draft.city||"City not set"}</small></article><article><span>CLASSES</span><strong>{setupDraft.classes.length}</strong><small>configured</small></article><article><span>SUBJECTS</span><strong>{setupDraft.subjects.length}</strong><small>configured</small></article><article><span>TEACHING SYSTEM</span><strong>{draft.subsystem}</strong><small>{draft.currency}</small></article></section>
  <div className="studio-grid studio-identity-grid">
   <form id="brand-form" className="studio-section brand-editor settings-form" onSubmit={saveIdentity}>
    <header className="object-header"><div><span>SCHOOL IDENTITY</span><h3>Name, logo and appearance</h3><p>These choices carry through navigation, learner cards, reports, receipts and school documents.</p></div><Palette/></header>
    <div className="logo-editor"><div className="logo-preview">{draft.logoUrl?<img src={draft.logoUrl} alt="School logo preview"/>:<span>{draft.shortName.slice(0,3)}</span>}</div><div><strong>School logo</strong><p>PNG, JPG, WebP or SVG. Maximum 2 MB.</p><label className="upload-button"><Upload/>{uploading?"Uploading…":"Upload logo"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={logo} disabled={uploading}/></label></div></div>
    <div className="form-grid"><label>Legal school name<input value={draft.name} disabled title="The legal name is founder controlled"/></label><label>Display name<input value={draft.shortName} maxLength={24} onChange={e=>field("shortName",e.target.value)} required/></label><label>Motto<input value={draft.motto} maxLength={100} onChange={e=>field("motto",e.target.value)}/></label><label>City<input value={draft.city} onChange={e=>field("city",e.target.value)}/></label><label className="full-field">Address<input value={draft.address} onChange={e=>field("address",e.target.value)}/></label><label>Teaching system<select value={draft.subsystem} onChange={e=>field("subsystem",e.target.value as SchoolBrand["subsystem"])}><option value="bilingual">Bilingual</option><option value="anglophone">Anglophone</option><option value="francophone">Francophone</option></select></label><label>Currency<select value={draft.currency} onChange={e=>field("currency",e.target.value)}><option value="XAF">FCFA (XAF)</option><option value="NGN">Naira (NGN)</option><option value="EUR">Euro (EUR)</option><option value="USD">US Dollar (USD)</option></select></label></div>
    <fieldset className="palette-field"><legend>School theme</legend><div className="palette-list">{palettes.map(item=><button type="button" className={draft.primaryColor===item.primary&&draft.accentColor===item.accent?"selected":""} key={item.name} onClick={()=>setDraft(current=>({...current,primaryColor:item.primary,accentColor:item.accent}))}><i style={{background:item.primary}}/><i style={{background:item.accent}}/><span>{item.name}</span></button>)}</div><div className="colour-fields"><label>Primary colour<span><input aria-label="Primary colour picker" type="color" value={draft.primaryColor} onChange={e=>field("primaryColor",e.target.value)}/><input aria-label="Primary colour value" value={draft.primaryColor} pattern="#[0-9A-Fa-f]{6}" onChange={e=>field("primaryColor",e.target.value)}/></span></label><label>Accent colour<span><input aria-label="Accent colour picker" type="color" value={draft.accentColor} onChange={e=>field("accentColor",e.target.value)}/><input aria-label="Accent colour value" value={draft.accentColor} pattern="#[0-9A-Fa-f]{6}" onChange={e=>field("accentColor",e.target.value)}/></span></label></div><small className={readable?"contrast-ok":"contrast-warning"}>{readable?"Theme is readable on screen and in print.":"Choose colours with more contrast."}</small></fieldset>
    <button className="primary" type="submit"><Palette/>Save identity</button>
    <button type="button" className="secondary" onClick={()=>setAdvancedBrand(value=>!value)}>{advancedBrand?"Hide document details":"Document details"}</button>{advancedBrand?<div className="form-grid advanced-settings"><label>Receipt prefix<input value={draft.receiptPrefix} onChange={e=>field("receiptPrefix",normalizePrefix(e.target.value))} required/></label><label>Learner ID prefix<input value={draft.studentIdPrefix} onChange={e=>field("studentIdPrefix",normalizePrefix(e.target.value))} required/></label><label>Timezone<input value={draft.timezone} onChange={e=>field("timezone",e.target.value)} required/></label></div>:null}
   </form>
   <section className="studio-section document-preview"><span className="kicker">LEARNER CARD PREVIEW</span><div className="identity-card improved-id" style={{background:draft.primaryColor,color:contrast(draft.primaryColor)<.35?"white":"#17221c"}}><header>{draft.logoUrl?<img src={draft.logoUrl} alt=""/>:<span style={{background:draft.accentColor}}>{draft.shortName.slice(0,3)}</span>}<div><strong>{draft.name}</strong><small>{draft.motto||"School motto"}</small></div></header><section><div className="photo"><ImagePlus/><small>Learner photo</small></div><div><span className="id-label">STUDENT</span><h3>Demo Learner</h3><p>Class 5</p><strong className="matricule">{draft.studentIdPrefix}-26-1001</strong><small>Valid through 31 July 2027</small></div><div className="qr-placeholder"><span>QR appears when the card is issued</span></div></section><footer><ShieldCheck/>School identification and pickup verification</footer></div><button type="button" onClick={()=>window.print()}><Printer/>Print preview</button></section>
  </div>
  <details className="studio-stage" open><summary><span><small>2</small><strong>School structure</strong><em>{setupDraft.classes.length} classes · {setupDraft.subjects.length} subjects</em></span><Settings2/></summary><form className="studio-stage-body settings-form" onSubmit={saveStructure}><div className="pack-builder"><div><span className="kicker">STARTING POINT</span><h3>Choose a school structure to begin from</h3><p>Load a bilingual, English or French starting point, then adapt it to the real school.</p></div><div className="pack-controls"><label>Starting point<select aria-label="Class pack" value={selectedPack} onChange={e=>setSelectedPack(e.target.value as ClassPackId)}>{classPacks.map(pack=><option key={pack.id} value={pack.id}>{pack.name}</option>)}</select></label><button type="button" onClick={applyPack}>Load draft</button></div><div className="pack-grid">{classPacks.map(pack=><article className={selectedPack===pack.id?"selected":""} key={pack.id} onClick={()=>setSelectedPack(pack.id)}><strong>{pack.name}</strong><small>{pack.description}</small><span>{pack.levels.length} levels · {pack.languages}</span></article>)}</div></div><StructureEditor value={setupDraft} onChange={setSetupDraft}/><button className="primary" type="submit"><Settings2/>Save school structure</button></form></details>
  <details className="studio-stage"><summary><span><small>3</small><strong>School rules</strong><em>Attendance, school work and fees</em></span><ShieldCheck/></summary><div className="studio-stage-body"><PolicyStudio/></div></details>
  {memberships?<details className="studio-stage"><summary><span><small>4</small><strong>Staff responsibilities</strong><em>Who can do what</em></span><ShieldCheck/></summary><div className="studio-stage-body"><InstitutionAuthorityStudio memberships={memberships} onChanged={onAuthorityChanged}/></div></details>:null}
 </div>;
}

function StructureEditor({value,onChange}:{value:SchoolSetup;onChange:(value:SchoolSetup)=>void}){
 return <div className="structure-columns"><section><h4>Academic years</h4>{value.academicYears.map((item,index)=><div className="setup-row" key={item.id}><input aria-label={`Academic year ${index+1}`} value={item.name} onChange={e=>onChange({...value,academicYears:value.academicYears.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/><select value={item.status} onChange={e=>onChange({...value,academicYears:value.academicYears.map((row,i)=>i===index?{...row,status:e.target.value as typeof row.status}:row)})}><option value="planning">Planning</option><option value="active">Active</option><option value="closed">Closed</option></select></div>)}<button type="button" onClick={()=>onChange({...value,academicYears:[...value.academicYears,{id:crypto.randomUUID(),name:"New academic year",startsOn:"",endsOn:"",status:"planning"}]})}>Add academic year</button></section><section><h4>Terms</h4>{value.terms.map((item,index)=><input key={item.id} aria-label={`Term ${index+1}`} value={item.name} onChange={e=>onChange({...value,terms:value.terms.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/>)}<button type="button" disabled={!value.academicYears.length} onClick={()=>onChange({...value,terms:[...value.terms,{id:crypto.randomUUID(),academicYearId:value.academicYears[0].id,name:`Term ${value.terms.length+1}`,startsOn:"",endsOn:"",orderIndex:value.terms.length+1}]})}>Add term</button></section><section><h4>Classes and streams</h4>{value.classes.map((item,index)=><input key={item.id} aria-label={`Class ${index+1}`} value={item.name} onChange={e=>onChange({...value,classes:value.classes.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/>)}<button type="button" onClick={()=>onChange({...value,classes:[...value.classes,{id:crypto.randomUUID(),name:"New class",sectionName:"",streamName:"",levelName:"",academicYearId:value.academicYears[0]?.id}]})}>Add class</button></section><section><h4>Subjects</h4>{value.subjects.map((item,index)=><div className="setup-row" key={item.id}><input aria-label={`Subject ${index+1}`} value={item.name} onChange={e=>onChange({...value,subjects:value.subjects.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/><input aria-label={`Subject code ${index+1}`} value={item.code} onChange={e=>onChange({...value,subjects:value.subjects.map((row,i)=>i===index?{...row,code:e.target.value.toUpperCase()}:row)})}/></div>)}<button type="button" onClick={()=>onChange({...value,subjects:[...value.subjects,{id:crypto.randomUUID(),name:"New subject",code:"SUB",subsystem:"bilingual",gradingWeight:100}]})}>Add subject</button></section></div>;
}
