import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { CheckCircle2, ImagePlus, Palette, Printer, Settings2, ShieldCheck, Upload } from "lucide-react";
import type { SchoolBrand, SchoolSetup } from "../domain/types";
import { buildClassPack, classPacks, type ClassPackId } from "../domain/classPacks";

const palettes = [
  { name:"Forest", primary:"#123b2c", accent:"#c9df83" },
  { name:"Royal", primary:"#173f70", accent:"#f0c75e" },
  { name:"Crimson", primary:"#6f1d2c", accent:"#f2cf72" },
  { name:"Teal", primary:"#075d5b", accent:"#a7e0d2" },
  { name:"Charcoal", primary:"#263238", accent:"#90caf9" },
] as const;

function normalizePrefix(value:string){return value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8)}
function contrast(hex:string){const value=hex.replace("#","");const rgb=[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}

export function SchoolStudioView({brand,setup,onSave,onSaveSetup,onUploadLogo}:{brand:SchoolBrand;setup:SchoolSetup;onSave:(brand:SchoolBrand)=>Promise<void>;onSaveSetup:(setup:SchoolSetup)=>Promise<void>;onUploadLogo:(file:File)=>Promise<string>}){
  const [draft,setDraft]=useState(brand),[setupDraft,setSetupDraft]=useState(setup),[status,setStatus]=useState(""),[failed,setFailed]=useState(false),[uploading,setUploading]=useState(false);
  const [selectedPack,setSelectedPack]=useState<ClassPackId>("bilingual-primary");
  useEffect(()=>setDraft(brand),[brand]);
  useEffect(()=>setSetupDraft(setup),[setup]);
  const readable=useMemo(()=>Math.abs(contrast(draft.primaryColor)-contrast(draft.accentColor))>=.35,[draft.primaryColor,draft.accentColor]);
  function field<K extends keyof SchoolBrand>(key:K,value:SchoolBrand[K]){setDraft(current=>({...current,[key]:value}))}
  async function saveIdentity(event:FormEvent){event.preventDefault();setFailed(false);setStatus("Saving school identity...");try{if(!readable)throw new Error("Choose colours with stronger contrast so text, buttons and printed IDs remain readable.");await onSave(draft);setStatus("School identity saved and applied across the workspace.")}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"School identity could not be saved.")}}
  async function logo(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setUploading(true);setFailed(false);setStatus("Uploading a new logo version...");try{const logoUrl=await onUploadLogo(file);field("logoUrl",logoUrl);setStatus("Logo uploaded. Save identity to publish it across DREEM.")}catch(reason){setFailed(true);setStatus(reason instanceof Error?reason.message:"Logo could not be uploaded.")}finally{setUploading(false);event.target.value=""}}
async function saveStructure(event:FormEvent){event.preventDefault();setFailed(false);setStatus("Saving academic structure...");try{await onSaveSetup(setupDraft);setStatus("Academic structure saved.")}catch(reason){setFailed(true);const detail=reason instanceof Error?reason.message:(reason&&typeof reason==="object"&&"message" in reason?String((reason as {message?:unknown}).message):String(reason));setStatus(detail||"Academic structure could not be saved.")}}
  function applyPack(){const existing=setupDraft.academicYears.length+setupDraft.terms.length+setupDraft.classes.length+setupDraft.subjects.length;setSetupDraft(buildClassPack(selectedPack));setFailed(false);setStatus(existing?"Pack loaded as a new editable draft. Existing saved records are unchanged until you save.":"Pack loaded. Review and customise it before saving.")}
  return <div className="content studio-workspace">
    <section className="page-intro"><div><span>DREEM SCHOOL STUDIO</span><h2>Give the school a consistent institutional identity.</h2><p>Branding is applied to the workspace, IDs, receipts, reports and authorized documents.</p></div><button className="primary" form="brand-form" type="submit"><Palette/>Save and publish identity</button></section>
    <div className="studio-grid">
      <form id="brand-form" className="panel settings-form brand-editor" onSubmit={saveIdentity}>
        <div className="panel-title"><div><span>SCHOOL BRAND</span><h3>Identity and document rules</h3></div><Palette/></div>
        <div className="logo-editor"><div className="logo-preview">{draft.logoUrl?<img src={draft.logoUrl} alt="School logo preview"/>:<span>{draft.shortName.slice(0,3)}</span>}</div><div><strong>School logo</strong><p>PNG, JPG, WebP or SVG. Maximum 2 MB. A new version is created for every upload.</p><label className="upload-button"><Upload/>{uploading?"Uploading...":"Upload logo"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={logo} disabled={uploading}/></label></div></div>
        <div className="form-grid"><label>Legal school name<input value={draft.name} disabled title="The legal name is founder controlled"/></label><label>Display name<input value={draft.shortName} maxLength={24} onChange={e=>field("shortName",e.target.value)} required/></label><label>Motto<input value={draft.motto} maxLength={100} onChange={e=>field("motto",e.target.value)}/></label><label>City<input value={draft.city} onChange={e=>field("city",e.target.value)}/></label><label className="full-field">Address<input value={draft.address} onChange={e=>field("address",e.target.value)}/></label><label>Subsystem<select value={draft.subsystem} onChange={e=>field("subsystem",e.target.value as SchoolBrand["subsystem"])}><option value="bilingual">Bilingual</option><option value="anglophone">Anglophone</option><option value="francophone">Francophone</option></select></label><label>Currency<input value={draft.currency} maxLength={3} onChange={e=>field("currency",e.target.value.toUpperCase())}/></label><label>Receipt prefix<input value={draft.receiptPrefix} onChange={e=>field("receiptPrefix",normalizePrefix(e.target.value))} required/></label><label>Student ID prefix<input value={draft.studentIdPrefix} onChange={e=>field("studentIdPrefix",normalizePrefix(e.target.value))} required/></label><label>Timezone<input value={draft.timezone} onChange={e=>field("timezone",e.target.value)} required/></label></div>
        <fieldset className="palette-field"><legend>School colours</legend><div className="palette-list">{palettes.map(item=><button type="button" className={draft.primaryColor===item.primary&&draft.accentColor===item.accent?"selected":""} key={item.name} onClick={()=>setDraft(current=>({...current,primaryColor:item.primary,accentColor:item.accent}))}><i style={{background:item.primary}}/><i style={{background:item.accent}}/><span>{item.name}</span></button>)}</div><div className="colour-fields"><label>Primary colour<span><input aria-label="Primary colour picker" type="color" value={draft.primaryColor} onChange={e=>field("primaryColor",e.target.value)}/><input aria-label="Primary colour value" value={draft.primaryColor} pattern="#[0-9A-Fa-f]{6}" onChange={e=>field("primaryColor",e.target.value)}/></span></label><label>Accent colour<span><input aria-label="Accent colour picker" type="color" value={draft.accentColor} onChange={e=>field("accentColor",e.target.value)}/><input aria-label="Accent colour value" value={draft.accentColor} pattern="#[0-9A-Fa-f]{6}" onChange={e=>field("accentColor",e.target.value)}/></span></label></div><small className={readable?"contrast-ok":"contrast-warning"}>{readable?"Contrast check passed for workspace and print.":"Contrast is too weak for accessible text and printed IDs."}</small></fieldset>
        {status&&<div className={`form-status ${failed?"error":"success"}`}><CheckCircle2/>{status}</div>}
      </form>
      <section className="panel document-preview"><span className="kicker">LIVE SCHOOL ID PREVIEW</span><div className="identity-card improved-id" style={{background:draft.primaryColor,color:contrast(draft.primaryColor)<.35?"white":"#17221c"}}><header>{draft.logoUrl?<img src={draft.logoUrl} alt=""/>:<span style={{background:draft.accentColor}}>{draft.shortName.slice(0,3)}</span>}<div><strong>{draft.name}</strong><small>{draft.motto||"School motto"}</small></div></header><section><div className="photo"><ImagePlus/><small>Learner photo</small></div><div><span className="id-label">STUDENT</span><h3>Demo Learner</h3><p>Class 5</p><strong className="matricule">{draft.studentIdPrefix}-26-1001</strong><small>Valid through 31 July 2027</small></div><div className="qr-placeholder"><span>QR issued with learner credential</span></div></section><footer><ShieldCheck/>The final QR is generated only after credential issuance and reveals role-authorized information.</footer></div><button type="button" onClick={()=>window.print()}><Printer/>Print identity proof</button><div className="record-rule"><strong>Record lifecycle</strong><p>Drafts can be edited. Submitted records need a reasoned amendment. Approved records are corrected by a new version or reversal, never silent overwrite.</p></div></section>
    </div>
    <form className="panel settings-form structure-editor" onSubmit={saveStructure}><div className="panel-title"><div><span>ACADEMIC OPERATIONS</span><h3>Build the school structure</h3></div><button className="primary" type="submit"><Settings2/>Save structure</button></div><div className="pack-builder"><div><span className="kicker">STARTING POINT, NEVER A LIMIT</span><h3>Choose a class pack</h3><p>Use a bilingual, English or French baseline, then adapt sections, streams, classes and subjects to the school&apos;s actual organisation.</p></div><div className="pack-controls"><label>Base pack<select aria-label="Class pack" value={selectedPack} onChange={e=>setSelectedPack(e.target.value as ClassPackId)}>{classPacks.map(pack=><option key={pack.id} value={pack.id}>{pack.name}</option>)}</select></label><button type="button" onClick={applyPack}>Load editable draft</button></div><div className="pack-grid">{classPacks.map(pack=><article className={selectedPack===pack.id?"selected":""} key={pack.id} onClick={()=>setSelectedPack(pack.id)}><strong>{pack.name}</strong><small>{pack.description}</small><span>{pack.levels.length} levels · {pack.languages}</span></article>)}</div><div className="form-status success"><CheckCircle2/>Customise names, sections, streams, subjects and progression before saving. Published records are versioned; they are never silently overwritten.</div></div><StructureEditor value={setupDraft} onChange={setSetupDraft}/></form>
  </div>
}

function StructureEditor({value,onChange}:{value:SchoolSetup;onChange:(value:SchoolSetup)=>void}){
  return <div className="structure-columns">
    <section><h4>Academic years</h4>{value.academicYears.map((item,index)=><div className="setup-row" key={item.id}><input aria-label={`Academic year ${index+1}`} value={item.name} onChange={e=>onChange({...value,academicYears:value.academicYears.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/><select value={item.status} onChange={e=>onChange({...value,academicYears:value.academicYears.map((row,i)=>i===index?{...row,status:e.target.value as typeof row.status}:row)})}><option value="planning">Planning</option><option value="active">Active</option><option value="closed">Closed</option></select></div>)}<button type="button" onClick={()=>onChange({...value,academicYears:[...value.academicYears,{id:crypto.randomUUID(),name:"New academic year",startsOn:"",endsOn:"",status:"planning"}]})}>Add academic year</button></section>
    <section><h4>Terms</h4>{value.terms.map((item,index)=><input key={item.id} aria-label={`Term ${index+1}`} value={item.name} onChange={e=>onChange({...value,terms:value.terms.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/>)}<button type="button" disabled={!value.academicYears.length} onClick={()=>onChange({...value,terms:[...value.terms,{id:crypto.randomUUID(),academicYearId:value.academicYears[0].id,name:`Term ${value.terms.length+1}`,startsOn:"",endsOn:"",orderIndex:value.terms.length+1}]})}>Add term</button></section>
    <section><h4>Classes and streams</h4>{value.classes.map((item,index)=><input key={item.id} aria-label={`Class ${index+1}`} value={item.name} onChange={e=>onChange({...value,classes:value.classes.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/>)}<button type="button" onClick={()=>onChange({...value,classes:[...value.classes,{id:crypto.randomUUID(),name:"New class",sectionName:"",streamName:"",levelName:"",academicYearId:value.academicYears[0]?.id}]})}>Add class</button></section>
    <section><h4>Subjects</h4>{value.subjects.map((item,index)=><div className="setup-row" key={item.id}><input aria-label={`Subject ${index+1}`} value={item.name} onChange={e=>onChange({...value,subjects:value.subjects.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/><input aria-label={`Subject code ${index+1}`} value={item.code} onChange={e=>onChange({...value,subjects:value.subjects.map((row,i)=>i===index?{...row,code:e.target.value.toUpperCase()}:row)})}/></div>)}<button type="button" onClick={()=>onChange({...value,subjects:[...value.subjects,{id:crypto.randomUUID(),name:"New subject",code:"SUB",subsystem:"bilingual",gradingWeight:100}]})}>Add subject</button></section>
  </div>
}
