import { BookOpenCheck, CalendarClock, ClipboardCheck, FileText, UsersRound, Wifi, WifiOff } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { AttendanceCommand, LearnerSummary } from "../domain/types";
import { createIdempotencyKey } from "../domain/rules";
import { recordAssessment, uploadAcademicDocument, type WorkspaceData } from "../lib/repository";
import { prepareTeacherOfflineContext, recordAttendanceResilient, recordLessonPlanResilient, replayTeacherOffline } from "../lib/teacherOffline";
import { loadTeacherClassRoster } from "../lib/teacherClassRoster";
import { userFacingError } from "../lib/userFacingError";

type Task="Teach"|"Attendance"|"Assess"|"Resources";
const tasks:[Task,React.ReactNode][]=[["Teach",<BookOpenCheck key="teach"/>],["Attendance",<UsersRound key="attendance"/>],["Assess",<ClipboardCheck key="assess"/>],["Resources",<FileText key="resources"/>]];
const readableError=(reason:unknown)=>userFacingError(reason,"This classroom action could not be completed. Nothing has been assumed saved. Check your connection and try again.");
const today=()=>new Date().toISOString().slice(0,10);

export default function TeacherClassroomWorkspace({workspace,onRefresh}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>}){
 const assigned=workspace.academics.assignments.filter(item=>item.status==="active"&&(!workspace.viewer.id||item.teacherUserId===workspace.viewer.id));
 const classes=useMemo(()=>Array.from(new Set(assigned.map(item=>item.className))),[assigned]);
 const [className,setClassName]=useState(classes[0]??""),[task,setTask]=useState<Task>("Teach"),[lessonAssignmentId,setLessonAssignmentId]=useState("");
 const [online,setOnline]=useState(typeof navigator==="undefined"?true:navigator.onLine),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[roster,setRoster]=useState<LearnerSummary[]>([]),[rosterLoading,setRosterLoading]=useState(false);
 const subjects=assigned.filter(item=>item.className===className),periods=workspace.academics.timetable.filter(item=>item.status==="active"&&assigned.some(a=>a.id===item.assignmentId));
 const selectedAssignment=subjects.find(item=>item.id===lessonAssignmentId)??subjects[0];
 const lessonOutcomes=workspace.academics.curriculumOutcomes.filter(item=>item.status==="active"&&selectedAssignment&&item.classId===selectedAssignment.classId&&item.subjectId===selectedAssignment.subjectId);
 const learners=roster.length?roster:workspace.learners.filter(item=>item.className===className);
 useEffect(()=>{setLessonAssignmentId(subjects[0]?.id??"");},[className,subjects.length]);
 useEffect(()=>{let active=true;if(!className)return;setRosterLoading(true);loadTeacherClassRoster(className).then(rows=>{if(active)setRoster(rows)}).catch(reason=>{if(active)setError(readableError(reason))}).finally(()=>{if(active)setRosterLoading(false)});return()=>{active=false};},[className]);
 useEffect(()=>{let active=true;const connect=async()=>{setOnline(true);try{const result=await replayTeacherOffline(workspace.viewer);if(active&&result.synced){setMessage(`${result.synced} offline classroom change${result.synced===1?"":"s"} synced to school records.`);await onRefresh();}}catch(reason){if(active)setError(readableError(reason));}};const disconnect=()=>setOnline(false);if(navigator.onLine)prepareTeacherOfflineContext().catch(()=>{});window.addEventListener("online",connect);window.addEventListener("offline",disconnect);return()=>{active=false;window.removeEventListener("online",connect);window.removeEventListener("offline",disconnect);};},[workspace.viewer,onRefresh]);
 async function submitAttendance(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const marks=learners.map(learner=>({studentId:learner.id,status:String(f.get(`status:${learner.id}`)) as AttendanceCommand["marks"][number]["status"],note:String(f.get(`note:${learner.id}`)||"")}));setBusy(true);setError("");setMessage("");try{const result=await recordAttendanceResilient({className,sessionDate:String(f.get("date")),periodLabel:String(f.get("period")),marks,idempotencyKey:createIdempotencyKey("teacher-attendance")},workspace.viewer);if(result.queued)setMessage(`${marks.length} attendance mark${marks.length===1?"":"s"} saved on this device and will sync when connected.`);else{await onRefresh();setMessage(`${marks.length} attendance record${marks.length===1?"":"s"} saved.`);}}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 async function submitLesson(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),outcomeIds=f.getAll("outcomeId").map(String),chosen=lessonOutcomes.filter(item=>outcomeIds.includes(item.id)),localObjective=String(f.get("localObjective")||"").trim(),objectives=[...chosen.map(item=>`${item.code}: ${item.titleEn}`),localObjective].filter(Boolean).join(" · ");if(!outcomeIds.length){setError("Choose at least one curriculum outcome for this lesson.");return;}setBusy(true);setError("");setMessage("");try{const result=await recordLessonPlanResilient({assignmentId:String(f.get("assignmentId")),lessonDate:String(f.get("lessonDate")),title:String(f.get("title")),objectives,learningActivity:String(f.get("activity")),evidence:String(f.get("evidence")),followUp:String(f.get("followUp")||""),outcomeIds,idempotencyKey:createIdempotencyKey("teacher-lesson-plan")},workspace.viewer);if(result.queued)setMessage("Lesson plan and curriculum links saved on this device and will sync when connected.");else{await onRefresh();setMessage("Lesson plan saved against the selected curriculum outcomes.");}}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 async function submitAssessment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!navigator.onLine){setError("Reconnect before sending marks for academic review. Attendance and lesson planning remain available offline.");return;}const f=new FormData(event.currentTarget),maxScore=Number(f.get("maxScore"));const marks=learners.map(learner=>({studentId:learner.id,score:Number(f.get(`score:${learner.id}`)),comment:String(f.get(`comment:${learner.id}`)||"")}));setBusy(true);setError("");setMessage("");try{await recordAssessment({subjectId:String(f.get("subjectId")),className,title:String(f.get("title")),assessmentType:String(f.get("assessmentType")) as "quiz"|"assignment"|"test"|"exam"|"mock"|"practical"|"project"|"oral"|"observation",durationMinutes:Number(f.get("durationMinutes"))||undefined,paperReference:String(f.get("paperReference")||""),questionSummary:String(f.get("questionSummary")||""),markingGuide:String(f.get("markingGuide")||""),syllabusObjectives:String(f.get("syllabusObjectives")||""),maxScore,assessmentDate:String(f.get("date")),marks,idempotencyKey:createIdempotencyKey("teacher-assessment")});await onRefresh();setMessage(`${marks.length} marks sent for review.`);}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 async function uploadDocument(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!navigator.onLine){setError("Reconnect before uploading this file. Keep it on your device and try again when connected.");return;}const f=new FormData(event.currentTarget),file=f.get("file");if(!(file instanceof File)||!file.size){setError("Choose a document to upload.");return;}setBusy(true);setError("");setMessage("");try{await uploadAcademicDocument({file,title:String(f.get("documentTitle")),documentType:String(f.get("documentType")) as "syllabus"|"assessment_paper"|"marking_guide"|"past_paper"|"lesson_resource",language:String(f.get("language")) as "english"|"french"|"bilingual"|"other",subjectId:String(f.get("subjectId"))});await onRefresh();setMessage("Document added to the school academic library.");}catch(reason){setError(readableError(reason));}finally{setBusy(false);}}
 return <div className="content role-workspace teacher-classroom">
  <section className="role-hero"><div><span className="eyebrow">MY CLASSROOM</span><h2>{className||"Choose an assigned class"}</h2><p>{className?`${learners.length} learner${learners.length===1?"":"s"} · ${subjects.length} subject assignment${subjects.length===1?"":"s"}`:"Your assigned classes appear here."}</p></div><div className="role-hero-status"><span className={"status-pill "+(online?"":"attention")}>{online?<Wifi size={14}/>:<WifiOff size={14}/>} {online?"Connected":"Offline-safe work"}</span></div></section>
  {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
  <div className="classroom-context"><label>Class<select aria-label="Working class" value={className} onChange={e=>{setClassName(e.target.value);setRoster([])}}><option value="">Choose assigned class</option>{classes.map(name=><option key={name}>{name}</option>)}</select></label><div className="classroom-next-period"><CalendarClock/><span><small>NEXT / ASSIGNED PERIODS</small><strong>{periods.filter(item=>item.className===className).length?`${periods.filter(item=>item.className===className).length} timetable period(s)":"No active period"}</strong></span></div>{rosterLoading?<small>Refreshing the complete class list…</small>:null}</div>
  {className?<nav className="workspace-tabs classroom-task-tabs" aria-label="Classroom work">{tasks.map(([name,icon])=><button type="button" key={name} className={task===name?"active":""} onClick={()=>setTask(name)}>{icon}{name}</button>)}</nav>:null}

  {className&&task==="Teach"?<section className="focus-card classroom-task"><header className="object-header"><div><span>PLAN TODAY'S LESSON</span><h3>Start from the curriculum, then adapt for your class</h3><p>DREEM links the lesson to approved outcomes instead of asking you to type curriculum references from memory.</p></div><BookOpenCheck/></header><form className="settings-form" onSubmit={submitLesson}><div className="form-grid"><label>Subject<select name="assignmentId" required value={lessonAssignmentId||selectedAssignment?.id||""} onChange={e=>setLessonAssignmentId(e.target.value)}><option value="">Choose subject</option>{subjects.map(item=><option value={item.id} key={item.id}>{item.subjectName}</option>)}</select></label><label>Lesson date<input name="lessonDate" type="date" defaultValue={today()} required/></label><label>Lesson title<input name="title" required/></label></div><fieldset className="curriculum-choice"><legend>What should learners achieve?</legend>{lessonOutcomes.length?lessonOutcomes.map(item=><label key={item.id}><input type="checkbox" name="outcomeId" value={item.id}/><span><strong>{item.code}</strong>{item.titleEn}{item.titleFr?<small>{item.titleFr}</small>:null}</span></label>):<p>No active curriculum outcome is mapped to this class and subject yet. Academic leadership must add one before the lesson can be submitted.</p>}</fieldset><label>Class-specific objective or adaptation (optional)<input name="localObjective" placeholder="Add only what is specific to this lesson or class"/></label><label>Learner activity / teaching approach<textarea name="activity" rows={3} required/></label><label>How will you know they understood?<input name="evidence" required/></label><label>Support or follow-up<input name="followUp"/></label><button className="primary" disabled={busy||!subjects.length||!lessonOutcomes.length}>Save lesson plan</button></form></section>:null}

  {className&&task==="Attendance"?<section className="focus-card classroom-task"><header className="object-header"><div><span>ATTENDANCE</span><h3>Take the register</h3><p>The class list is loaded directly from the assigned class, not from a limited school dashboard snapshot.</p></div><UsersRound/></header><form className="settings-form" onSubmit={submitAttendance}><div className="form-grid"><label>Date<input name="date" type="date" defaultValue={today()} required/></label><label>Period<select name="period"><option value="AM">Morning</option><option value="PM">Afternoon</option><option value="EXTRA">Extra class</option></select></label></div><AttendanceRows learners={learners}/><button className="primary" disabled={busy||!learners.length}>Save attendance</button></form></section>:null}

  {className&&task==="Assess"?<section className="focus-card classroom-task"><header className="object-header"><div><span>ASSESSMENT</span><h3>Record marks for review</h3><p>Enter the essentials first. Extra paper and marking details stay optional.</p></div><ClipboardCheck/></header><form className="settings-form" onSubmit={submitAssessment}><div className="form-grid"><label>Subject<select name="subjectId" required><option value="">Choose subject</option>{subjects.map(item=><option value={item.subjectId} key={item.id}>{item.subjectName}</option>)}</select></label><label>Type<select name="assessmentType"><option value="quiz">Quiz</option><option value="assignment">Assignment</option><option value="test">Test</option><option value="exam">Exam</option><option value="mock">Mock exam</option><option value="practical">Practical</option><option value="project">Project</option><option value="oral">Oral</option><option value="observation">Observation</option></select></label><label>Title<input name="title" required/></label><label>Date<input name="date" type="date" defaultValue={today()} required/></label><label>Maximum score<input name="maxScore" type="number" min="1" defaultValue="20" required/></label></div><details className="workflow-exceptions"><summary>Add paper, syllabus or marking details</summary><div className="form-grid"><label>Duration (minutes)<input name="durationMinutes" type="number" min="1"/></label><label>Paper / scan reference<input name="paperReference"/></label><label>Syllabus objectives<input name="syllabusObjectives"/></label></div><label>Questions or task<textarea name="questionSummary" rows={2}/></label><label>Marking guide<textarea name="markingGuide" rows={2}/></label></details><AssessmentRows learners={learners}/><button className="primary" disabled={busy||!learners.length||!online}>Send marks for review</button>{!online?<p className="panel-copy">Reconnect before sending marks. Attendance and lesson planning remain available offline.</p>:null}</form></section>:null}

  {className&&task==="Resources"?<section className="focus-card classroom-task"><header className="object-header"><div><span>CLASS RESOURCES</span><h3>Add syllabus, papers or teaching material</h3><p>Files remain source documents. DREEM does not pretend an upload has been understood until document intelligence is connected.</p></div><FileText/></header><form className="settings-form" onSubmit={uploadDocument}><div className="form-grid"><label>Title<input name="documentTitle" required/></label><label>Type<select name="documentType"><option value="syllabus">Syllabus</option><option value="assessment_paper">Assessment paper</option><option value="marking_guide">Marking guide</option><option value="past_paper">Past paper</option><option value="lesson_resource">Lesson resource</option></select></label><label>Language<select name="language"><option value="bilingual">Bilingual</option><option value="english">English</option><option value="french">French</option><option value="other">Other</option></select></label><label>Subject<select name="subjectId" required><option value="">Choose subject</option>{subjects.map(item=><option value={item.subjectId} key={item.id}>{item.subjectName}</option>)}</select></label><label>File<input name="file" type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg,.webp" required/></label></div><button className="primary" disabled={busy||!online}>Add to academic library</button>{!online?<p className="panel-copy">Reconnect to upload this file.</p>:null}</form></section>:null}
 </div>;
}
function AttendanceRows({learners}:{learners:LearnerSummary[]}){return <div className="attendance-grid">{learners.map(item=><article key={item.id}><strong>{item.name}</strong><select name={`status:${item.id}`} defaultValue="present"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select><input name={`note:${item.id}`} placeholder="Note (optional)"/></article>)}{!learners.length?<p>No learner is enrolled in this class.</p>:null}</div>;}
function AssessmentRows({learners}:{learners:LearnerSummary[]}){return <div className="attendance-grid">{learners.map(item=><article key={item.id}><strong>{item.name}</strong><input name={`score:${item.id}`} type="number" min="0" step="0.01" required/><input name={`comment:${item.id}`} placeholder="Comment"/></article>)}</div>;}
