import { ArrowDown, ArrowUp, BusFront, MapPinned, Plus, Route, ShieldCheck, Trash2, UsersRound } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { assignStudentTransport, configureTransportRoute, dispatchTransportTrip, progressTransportTrip, recordTransportConsent, registerTransportDriver, registerTransportVehicle, type WorkspaceData } from "../lib/repository";

const tabs=["Network","Fleet & drivers","Learners","Live journeys"] as const;
type Tab=typeof tabs[number];
const key=(scope:string)=>`${scope}:${crypto.randomUUID()}`;
function errorText(reason:unknown){return reason instanceof Error?reason.message:reason&&typeof reason==="object"&&"message" in reason&&typeof reason.message==="string"?reason.message:"Transport action could not be completed.";}

export default function TransportManagerWorkspace({workspace,onRefresh}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>}){
 const t=workspace.transport;
 const [tab,setTab]=useState<Tab>("Network"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [routeStops,setRouteStops]=useState([{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""},{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""}]);
 const [routeId,setRouteId]=useState(t.routes.find(x=>x.status==="active")?.id??t.routes[0]?.id??""),[tripId,setTripId]=useState(t.trips.find(x=>!["completed","cancelled"].includes(x.status))?.id??"");
 const route=t.routes.find(x=>x.id===routeId),trip=t.trips.find(x=>x.id===tripId);
 const driverMembers=workspace.operations.memberships.filter(x=>x.status==="approved"&&x.role==="driver");
 const routeLearners=useMemo(()=>trip?workspace.transport.assignments.filter(item=>item.routeId===trip.routeId&&item.status==="active"):[],[workspace.transport.assignments,trip]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await onRefresh();setMessage(success);}catch(reason){setError(errorText(reason));}finally{setBusy(false);}}
 function updateStop(id:string,field:"name"|"landmark"|"pickupTime",value:string){setRouteStops(rows=>rows.map(row=>row.id===id?{...row,[field]:value}:row));}
 function moveStop(index:number,direction:-1|1){setRouteStops(rows=>{const next=[...rows],target=index+direction;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next;});}
 async function routeForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const stops=routeStops.filter(x=>x.name.trim()).map(({name,landmark,pickupTime})=>({name:name.trim(),landmark:landmark.trim(),pickupTime}));if(stops.length<2){setError("Add at least two named stops to activate a route.");return;}await run(()=>configureTransportRoute({code:String(f.get("code")),name:String(f.get("name")),direction:String(f.get("direction")) as "inbound"|"outbound"|"both",stops,idempotencyKey:key("transport-route")}),"Route and ordered stops activated.");}
 async function vehicleForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>registerTransportVehicle({code:String(f.get("code")),registrationNumber:String(f.get("registration")),vehicleType:String(f.get("type")),capacity:Number(f.get("capacity")),inspectionDueOn:String(f.get("inspection")),insuranceDueOn:String(f.get("insurance")),idempotencyKey:key("transport-vehicle")}),"Vehicle registered with compliance dates.");}
 async function driverForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>registerTransportDriver({userId:String(f.get("userId")),licenseReference:String(f.get("licence")),licenseExpiresOn:String(f.get("expires")),phone:String(f.get("phone")),idempotencyKey:key("transport-driver")}),"Driver profile activated.");}
 async function consentForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>recordTransportConsent({studentId:String(f.get("studentId")),decision:String(f.get("decision")) as "granted"|"revoked",guardianName:String(f.get("guardian")),termsVersion:String(f.get("terms")),captureMethod:String(f.get("method")),evidenceNote:String(f.get("evidence")),idempotencyKey:key("transport-consent")}),"Guardian transport authority recorded.");}
 async function assignmentForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>assignStudentTransport({studentId:String(f.get("studentId")),routeId:String(f.get("routeId")),pickupStopId:String(f.get("pickup")),dropoffStopId:String(f.get("dropoff")),effectiveFrom:String(f.get("from")),effectiveTo:String(f.get("to")),idempotencyKey:key("transport-assignment")}),"Learner assigned to route after consent checks.");}
 async function dispatchForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>dispatchTransportTrip({routeId:String(f.get("routeId")),vehicleId:String(f.get("vehicleId")),driverId:String(f.get("driverId")),serviceDate:String(f.get("date")),direction:String(f.get("direction")) as "inbound"|"outbound",scheduledDeparture:String(f.get("departure")),idempotencyKey:key("transport-trip")}),"Controlled trip dispatched to the driver.");}
 async function eventForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>progressTransportTrip({tripId:String(f.get("tripId")),eventType:String(f.get("eventType")),stopId:String(f.get("stopId"))||undefined,studentId:String(f.get("studentId"))||undefined,note:String(f.get("note")),idempotencyKey:key("transport-event")}),"Journey event recorded.");}
 return <div className="content role-workspace transport-manager-workspace">
  <section className="role-hero"><div><span className="eyebrow">TRANSPORT CONTROL</span><h2>Run today’s school transport</h2><p>Routes, vehicles, drivers and learner assignments stay together. Open setup only when something needs changing.</p></div><div className="role-hero-status"><span className="status-pill"><ShieldCheck size={15}/>{t.trips.filter(x=>!["completed","cancelled"].includes(x.status)).length} open journey(s)</span></div></section>
  {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
  <details className="depth-drawer"><summary>How school transport works</summary><section className="panel lifecycle-panel"><div className="lifecycle-rail"><span><b>1</b>Route</span><span><b>2</b>Fleet</span><span><b>3</b>Consent</span><span><b>4</b>Assign</span><span><b>5</b>Dispatch</span><span><b>6</b>Journey</span><span><b>7</b>Handover</span></div></section></details>
  <nav className="workspace-tabs" aria-label="Transport manager sections">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {tab==="Network"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><Route/><div><span>ROUTE NETWORK</span><h3>Define ordered stops before assignment</h3></div></div><form className="settings-form route-builder" onSubmit={routeForm}><div className="form-grid route-basics"><Field name="code" label="Route code"/><Field name="name" label="Route name"/><Select name="direction" label="Direction" rows={[["both","Both"],["inbound","Inbound"],["outbound","Outbound"]]}/></div><div className="ordered-stops"><div className="ordered-stops-heading"><div><small>ORDERED STOPS</small><strong>Build the route in travel order</strong></div><button type="button" onClick={()=>setRouteStops(rows=>[...rows,{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""}])}><Plus size={16}/>Add stop</button></div>{routeStops.map((stop,index)=><div className="ordered-stop" key={stop.id}><span className="stop-order">{index+1}</span><label>Stop name<input value={stop.name} onChange={e=>updateStop(stop.id,"name",e.target.value)} placeholder="e.g. Mendong Carrefour" required/></label><label>Landmark<input value={stop.landmark} onChange={e=>updateStop(stop.id,"landmark",e.target.value)} placeholder="Optional landmark"/></label><label>Pickup time<input type="time" value={stop.pickupTime} onChange={e=>updateStop(stop.id,"pickupTime",e.target.value)}/></label><div className="stop-actions"><button type="button" aria-label="Move stop up" disabled={index===0} onClick={()=>moveStop(index,-1)}><ArrowUp size={15}/></button><button type="button" aria-label="Move stop down" disabled={index===routeStops.length-1} onClick={()=>moveStop(index,1)}><ArrowDown size={15}/></button><button type="button" aria-label="Remove stop" disabled={routeStops.length<=2} onClick={()=>setRouteStops(rows=>rows.filter(row=>row.id!==stop.id))}><Trash2 size={15}/></button></div></div>)}</div><button className="primary" disabled={busy}>Activate route</button></form></section><section className="panel"><div className="panel-title"><MapPinned/><div><span>ACTIVE NETWORK</span><h3>{t.routes.filter(x=>x.status==="active").length} route(s)</h3></div></div>{t.routes.map(item=><article className="document-row" key={item.id}><strong>{item.code} · {item.name}</strong><span>{item.direction} · {item.status}</span><small>{item.stops.map(stop=>stop.name).join(" → ")||"No stops"}</small></article>)}</section></section>:null}
  {tab==="Fleet & drivers"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><BusFront/><div><span>VEHICLES</span><h3>Register compliance-ready fleet</h3></div></div><form className="settings-form" onSubmit={vehicleForm}><div className="form-grid"><Field name="code" label="Vehicle code"/><Field name="registration" label="Registration number"/><Select name="type" label="Vehicle type" rows={[["bus","Bus"],["minibus","Minibus"],["van","Van"],["car","Car"]]}/><Field name="capacity" label="Seat capacity" type="number"/><Field name="inspection" label="Inspection due" type="date"/><Field name="insurance" label="Insurance due" type="date"/></div><button className="primary" disabled={busy}>Register vehicle</button></form>{t.vehicles.map(item=><article className="document-row" key={item.id}><strong>{item.code} · {item.registrationNumber}</strong><span>{item.vehicleType} · {item.capacity} seats · {item.status}</span></article>)}</section><section className="panel"><div className="panel-title"><UsersRound/><div><span>DRIVERS</span><h3>Activate approved driver accounts</h3></div></div><form className="settings-form" onSubmit={driverForm}><div className="form-grid"><label>Approved driver<select name="userId" required><option value="">Choose driver account</option>{driverMembers.map(x=><option key={x.id} value={x.profileId}>{x.name}</option>)}</select></label><Field name="licence" label="Licence reference"/><Field name="expires" label="Licence expiry" type="date"/><Field name="phone" label="Driver phone"/></div><button className="primary" disabled={busy}>Activate driver</button></form>{t.drivers.map(item=><article className="document-row" key={item.id}><strong>{item.name}</strong><span>{item.status} · licence to {item.licenseExpiresOn}</span></article>)}</section></section>:null}
  {tab==="Learners"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><ShieldCheck/><div><span>GUARDIAN AUTHORITY</span><h3>Record consent before assignment</h3></div></div><form className="settings-form" onSubmit={consentForm}><div className="form-grid"><Learners workspace={workspace} name="studentId" label="Learner"/><Field name="guardian" label="Guardian full name"/><Select name="decision" label="Decision" rows={[["granted","Granted"],["revoked","Revoked"]]}/><Field name="terms" label="Terms version" defaultValue="transport-v1"/><Select name="method" label="Capture method" rows={[["signed_form","Signed form"],["parent_portal","Parent portal"],["school_desk","School desk"],["verified_call","Verified call"]]}/><Field name="evidence" label="Evidence note"/></div><button className="primary" disabled={busy}>Record guardian decision</button></form></section><section className="panel"><div className="panel-title"><UsersRound/><div><span>ROUTE ASSIGNMENT</span><h3>Place consented learner on active route</h3></div></div><form className="settings-form" onSubmit={assignmentForm}><div className="form-grid"><Learners workspace={workspace} name="studentId" label="Learner"/><label>Route<select name="routeId" value={routeId} onChange={e=>setRouteId(e.target.value)} required><option value="">Choose route</option>{t.routes.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><Stops stops={route?.stops??[]} name="pickup" label="Pickup stop"/><Stops stops={route?.stops??[]} name="dropoff" label="Drop-off stop"/><Field name="from" label="Effective from" type="date"/><Field name="to" label="Effective to" type="date"/></div><button className="primary" disabled={busy||!route}>Assign learner</button></form>{t.assignments.map(item=><article className="document-row" key={item.id}><strong>{item.studentName}</strong><span>{item.routeName} · {item.pickupStopName} → {item.dropoffStopName}</span><small>{item.status}</small></article>)}</section></section>:null}
  {tab==="Live journeys"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><BusFront/><div><span>DISPATCH</span><h3>Create a controlled school journey</h3></div></div><form className="settings-form" onSubmit={dispatchForm}><div className="form-grid"><label>Route<select name="routeId" required><option value="">Choose route</option>{t.routes.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Vehicle<select name="vehicleId" required><option value="">Choose vehicle</option>{t.vehicles.filter(x=>["available","assigned"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.code} · {x.capacity} seats</option>)}</select></label><label>Driver<select name="driverId" required><option value="">Choose driver</option>{t.drivers.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field name="date" label="Service date" type="date"/><Select name="direction" label="Direction" rows={[["inbound","Inbound"],["outbound","Outbound"]]}/><Field name="departure" label="Departure" type="time"/></div><button className="primary" disabled={busy}>Dispatch trip</button></form></section><section className="panel"><div className="panel-title"><MapPinned/><div><span>LIVE JOURNEYS</span><h3>Monitor and support driver events</h3></div></div><form className="settings-form" onSubmit={eventForm}><div className="form-grid"><label>Open trip<select name="tripId" value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">Choose trip</option>{t.trips.filter(x=>!["completed","cancelled"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.routeName} · {x.serviceDate} · {x.status}</option>)}</select></label><Select name="eventType" label="Manager event" rows={[["delay_reported","Delay reported"],["cancelled","Cancel trip"],["note","Operational note"]]}/><Stops stops={t.routes.find(x=>x.id===trip?.routeId)?.stops??[]} name="stopId" label="Stop (optional)" optional/><LearnersFromAssignments rows={routeLearners} name="studentId" label="Learner (optional)"/><Field name="note" label="Manager note"/></div><button className="primary" disabled={busy||!trip}>Record manager event</button></form>{t.trips.map(item=><article className="document-row" key={item.id}><strong>{item.routeName} · {item.serviceDate}</strong><span>{item.driverName} · {item.vehicleCode} · {item.status}</span><small>{item.assignedStudents} learner(s){item.scheduledDeparture?` · departure ${item.scheduledDeparture}`:""}</small></article>)}</section></section>:null}
 </div>;
}
function Field({name,label,type="text",defaultValue=""}:{name:string;label:string;type?:string;defaultValue?:string}){return <label>{label}<input name={name} type={type} defaultValue={defaultValue} required={!["phone","note"].includes(name)}/></label>;}
function Select({name,label,rows}:{name:string;label:string;rows:[string,string][]}){return <label>{label}<select name={name} required>{rows.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
function Learners({workspace,name,label}:{workspace:WorkspaceData;name:string;label:string}){return <label>{label}<select name={name} required><option value="">Choose learner</option>{workspace.learners.map(item=><option key={item.id} value={item.id}>{item.name} · {item.className}</option>)}</select></label>;}
function Stops({stops,name,label,optional=false}:{stops:{id:string;name:string}[];name:string;label:string;optional?:boolean}){return <label>{label}<select name={name} required={!optional}><option value="">{optional?"No stop":"Choose stop"}</option>{stops.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;}
function LearnersFromAssignments({rows,name,label}:{rows:{studentId:string;studentName:string}[];name:string;label:string}){return <label>{label}<select name={name}><option value="">No learner</option>{rows.map(item=><option key={item.studentId} value={item.studentId}>{item.studentName}</option>)}</select></label>;}
