import { ArrowDown, ArrowUp, BusFront, MapPinned, Plus, Route, ShieldCheck, Trash2, UsersRound } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { assignStudentTransport, configureTransportRoute, dispatchTransportTrip, progressTransportTrip, recordTransportConsent, registerTransportDriver, registerTransportVehicle, type WorkspaceData } from "../lib/repository";
import { userFacingError } from "../lib/userFacingError";
import RemoteLearnerPicker from "./RemoteLearnerPicker";

const tabs=["Live journeys","Learners","Network","Fleet & drivers"] as const;
type Tab=typeof tabs[number];
const key=(scope:string)=>`${scope}:${crypto.randomUUID()}`;
const errorText=(reason:unknown)=>userFacingError(reason,"The transport action could not be completed. Nothing has been assumed saved. Check your connection or access and try again.");

export default function TransportManagerWorkspace({workspace,onRefresh}:{workspace:WorkspaceData;onRefresh:()=>Promise<void>}){
 const t=workspace.transport;
 const openTrips=t.trips.filter(item=>!["completed","cancelled"].includes(item.status));
 const [tab,setTab]=useState<Tab>("Live journeys"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [routeStops,setRouteStops]=useState([{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""},{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""}]);
 const [routeId,setRouteId]=useState(t.routes.find(item=>item.status==="active")?.id??t.routes[0]?.id??""),[tripId,setTripId]=useState(openTrips[0]?.id??"");
 const route=t.routes.find(item=>item.id===routeId),trip=t.trips.find(item=>item.id===tripId);
 const driverMembers=workspace.operations.memberships.filter(item=>item.status==="approved"&&item.role==="driver");
 const routeLearners=useMemo(()=>trip?t.assignments.filter(item=>item.routeId===trip.routeId&&item.status==="active"):[],[t.assignments,trip]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError("");setMessage("");try{await action();await onRefresh();setMessage(success);}catch(reason){setError(errorText(reason));}finally{setBusy(false);}}
 function updateStop(id:string,field:"name"|"landmark"|"pickupTime",value:string){setRouteStops(rows=>rows.map(row=>row.id===id?{...row,[field]:value}:row));}
 function moveStop(index:number,direction:-1|1){setRouteStops(rows=>{const next=[...rows],target=index+direction;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next;});}
 async function routeForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const stops=routeStops.filter(item=>item.name.trim()).map(({name,landmark,pickupTime})=>({name:name.trim(),landmark:landmark.trim(),pickupTime}));if(stops.length<2){setError("Add at least two named stops before activating the route.");return;}await run(()=>configureTransportRoute({code:String(form.get("code")),name:String(form.get("name")),direction:String(form.get("direction")) as "inbound"|"outbound"|"both",stops,idempotencyKey:key("transport-route")}),"Route saved and activated.");}
 async function vehicleForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>registerTransportVehicle({code:String(form.get("code")),registrationNumber:String(form.get("registration")),vehicleType:String(form.get("type")),capacity:Number(form.get("capacity")),inspectionDueOn:String(form.get("inspection")),insuranceDueOn:String(form.get("insurance")),idempotencyKey:key("transport-vehicle")}),"Vehicle registered with its compliance dates.");}
 async function driverForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>registerTransportDriver({userId:String(form.get("userId")),licenseReference:String(form.get("licence")),licenseExpiresOn:String(form.get("expires")),phone:String(form.get("phone")),idempotencyKey:key("transport-driver")}),"Driver activated for transport work.");}
 async function consentForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>recordTransportConsent({studentId:String(form.get("studentId")),decision:String(form.get("decision")) as "granted"|"revoked",guardianName:String(form.get("guardian")),termsVersion:String(form.get("terms")),captureMethod:String(form.get("method")),evidenceNote:String(form.get("evidence")),idempotencyKey:key("transport-consent")}),"Guardian transport decision recorded.");}
 async function assignmentForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>assignStudentTransport({studentId:String(form.get("studentId")),routeId:String(form.get("routeId")),pickupStopId:String(form.get("pickup")),dropoffStopId:String(form.get("dropoff")),effectiveFrom:String(form.get("from")),effectiveTo:String(form.get("to")),idempotencyKey:key("transport-assignment")}),"Learner assigned to the route after consent checks.");}
 async function dispatchForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>dispatchTransportTrip({routeId:String(form.get("routeId")),vehicleId:String(form.get("vehicleId")),driverId:String(form.get("driverId")),serviceDate:String(form.get("date")),direction:String(form.get("direction")) as "inbound"|"outbound",scheduledDeparture:String(form.get("departure")),idempotencyKey:key("transport-trip")}),"Journey dispatched to the driver.");}
 async function eventForm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>progressTransportTrip({tripId:String(form.get("tripId")),eventType:String(form.get("eventType")),stopId:String(form.get("stopId"))||undefined,studentId:String(form.get("studentId"))||undefined,note:String(form.get("note")),idempotencyKey:key("transport-event")}),"Journey update recorded.");}
 return <div className="content role-workspace transport-manager-workspace">
  <section className="role-hero"><div><span className="eyebrow">TRANSPORT · TODAY</span><h2>{openTrips.length?`${openTrips.length} journey${openTrips.length===1?"":"s"} in progress`:"No journey is currently open"}</h2><p>Run today’s journeys first. Learner assignments, routes, vehicles and drivers stay one tap away when something needs changing.</p></div><div className="role-hero-status"><span className="status-pill"><ShieldCheck size={15}/>Guardian consent controls assignment</span></div></section>
  <section className="studio-overview transport-overview"><article><span>OPEN JOURNEYS</span><strong>{openTrips.length}</strong><small>live or awaiting completion</small></article><article><span>ACTIVE ROUTES</span><strong>{t.routes.filter(item=>item.status==="active").length}</strong><small>with ordered stops</small></article><article><span>LEARNERS</span><strong>{t.assignments.filter(item=>item.status==="active").length}</strong><small>currently assigned</small></article><article><span>AVAILABLE VEHICLES</span><strong>{t.vehicles.filter(item=>item.status==="available").length}</strong><small>ready for dispatch</small></article></section>
  {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status">{message}</div>:null}
  <nav className="workspace-tabs" aria-label="Transport manager sections">{tabs.map(item=><button type="button" key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {tab==="Live journeys"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><BusFront/><div><span>DISPATCH</span><h3>Start an authorised school journey</h3></div></div><form className="settings-form" onSubmit={dispatchForm}><div className="form-grid"><label>Route<select name="routeId" required><option value="">Choose route</option>{t.routes.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Vehicle<select name="vehicleId" required><option value="">Choose vehicle</option>{t.vehicles.filter(item=>["available","assigned"].includes(item.status)).map(item=><option key={item.id} value={item.id}>{item.code} · {item.capacity} seats</option>)}</select></label><label>Driver<select name="driverId" required><option value="">Choose driver</option>{t.drivers.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field name="date" label="Service date" type="date"/><Select name="direction" label="Direction" rows={[["inbound","Inbound"],["outbound","Outbound"]]}/><Field name="departure" label="Departure time" type="time"/></div><button className="primary" disabled={busy}>Dispatch journey</button></form></section><section className="panel"><div className="panel-title"><MapPinned/><div><span>JOURNEY STATUS</span><h3>{openTrips.length?"Record only what actually happened":"No open journey"}</h3></div></div>{openTrips.length?<form className="settings-form" onSubmit={eventForm}><div className="form-grid"><label>Open journey<select name="tripId" value={tripId} onChange={event=>setTripId(event.target.value)} required><option value="">Choose journey</option>{openTrips.map(item=><option key={item.id} value={item.id}>{item.routeName} · {item.serviceDate} · {item.status}</option>)}</select></label><Select name="eventType" label="Update" rows={[["delay_reported","Delay reported"],["cancelled","Cancel journey"],["note","Operational note"]]}/><Stops stops={t.routes.find(item=>item.id===trip?.routeId)?.stops??[]} name="stopId" label="Stop (optional)" optional/><label>Learner (optional)<select name="studentId"><option value="">No learner</option>{routeLearners.map(item=><option key={item.studentId} value={item.studentId}>{item.studentName}</option>)}</select></label><Field name="note" label="What happened" optional/></div><button className="primary" disabled={busy||!trip}>Record journey update</button></form>:<p className="empty-copy">Dispatch a journey when a route, vehicle and driver are ready.</p>}{t.trips.slice(0,8).map(item=><article className="document-row" key={item.id}><strong>{item.routeName} · {item.serviceDate}</strong><span>{item.driverName} · {item.vehicleCode}</span><small>{item.status} · {item.assignedStudents} learner(s){item.scheduledDeparture?` · ${item.scheduledDeparture}`:""}</small></article>)}</section></section>:null}
  {tab==="Learners"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><ShieldCheck/><div><span>GUARDIAN DECISION</span><h3>Record consent before any route assignment</h3></div></div><form className="settings-form" onSubmit={consentForm}><div className="form-grid"><RemoteLearnerPicker name="studentId" label="Learner"/><Field name="guardian" label="Guardian full name"/><Select name="decision" label="Decision" rows={[["granted","Consent granted"],["revoked","Consent revoked"]]}/><Field name="terms" label="Consent version" defaultValue="transport-v1"/><Select name="method" label="How it was confirmed" rows={[["signed_form","Signed form"],["parent_portal","Parent portal"],["school_desk","School desk"],["verified_call","Verified call"]]}/><Field name="evidence" label="Confirmation note"/></div><button className="primary" disabled={busy}>Record guardian decision</button></form></section><section className="panel"><div className="panel-title"><UsersRound/><div><span>ROUTE ASSIGNMENT</span><h3>Place a consented learner on a route</h3></div></div><form className="settings-form" onSubmit={assignmentForm}><div className="form-grid"><RemoteLearnerPicker name="studentId" label="Learner"/><label>Route<select name="routeId" value={routeId} onChange={event=>setRouteId(event.target.value)} required><option value="">Choose route</option>{t.routes.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><Stops stops={route?.stops??[]} name="pickup" label="Pickup stop"/><Stops stops={route?.stops??[]} name="dropoff" label="Drop-off stop"/><Field name="from" label="Starts on" type="date"/><Field name="to" label="Ends on" type="date" optional/></div><button className="primary" disabled={busy||!route}>Assign learner</button></form>{t.assignments.slice(0,20).map(item=><article className="document-row" key={item.id}><strong>{item.studentName}</strong><span>{item.routeName} · {item.pickupStopName} → {item.dropoffStopName}</span><small>{item.status}</small></article>)}</section></section>:null}
  {tab==="Network"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><Route/><div><span>ROUTE NETWORK</span><h3>Build stops in the order the vehicle travels</h3></div></div><form className="settings-form route-builder" onSubmit={routeForm}><div className="form-grid route-basics"><Field name="code" label="Route code"/><Field name="name" label="Route name"/><Select name="direction" label="Direction" rows={[["both","Both"],["inbound","Inbound"],["outbound","Outbound"]]}/></div><div className="ordered-stops"><div className="ordered-stops-heading"><div><small>ORDERED STOPS</small><strong>Travel order</strong></div><button type="button" onClick={()=>setRouteStops(rows=>[...rows,{id:crypto.randomUUID(),name:"",landmark:"",pickupTime:""}])}><Plus size={16}/>Add stop</button></div>{routeStops.map((stop,index)=><div className="ordered-stop" key={stop.id}><span className="stop-order">{index+1}</span><label>Stop name<input value={stop.name} onChange={event=>updateStop(stop.id,"name",event.target.value)} placeholder="e.g. Mendong Carrefour" required/></label><label>Landmark<input value={stop.landmark} onChange={event=>updateStop(stop.id,"landmark",event.target.value)} placeholder="Optional landmark"/></label><label>Pickup time<input type="time" value={stop.pickupTime} onChange={event=>updateStop(stop.id,"pickupTime",event.target.value)}/></label><div className="stop-actions"><button type="button" aria-label="Move stop up" disabled={index===0} onClick={()=>moveStop(index,-1)}><ArrowUp size={15}/></button><button type="button" aria-label="Move stop down" disabled={index===routeStops.length-1} onClick={()=>moveStop(index,1)}><ArrowDown size={15}/></button><button type="button" aria-label="Remove stop" disabled={routeStops.length<=2} onClick={()=>setRouteStops(rows=>rows.filter(row=>row.id!==stop.id))}><Trash2 size={15}/></button></div></div>)}</div><button className="primary" disabled={busy}>Activate route</button></form></section><section className="panel"><div className="panel-title"><MapPinned/><div><span>ACTIVE NETWORK</span><h3>{t.routes.filter(item=>item.status==="active").length} route(s)</h3></div></div>{t.routes.map(item=><article className="document-row" key={item.id}><strong>{item.code} · {item.name}</strong><span>{item.direction} · {item.status}</span><small>{item.stops.map(stop=>stop.name).join(" → ")||"No stops"}</small></article>)}</section></section>:null}
  {tab==="Fleet & drivers"?<section className="transport-manager-grid"><section className="panel"><div className="panel-title"><BusFront/><div><span>VEHICLES</span><h3>Register the real vehicle and compliance dates</h3></div></div><form className="settings-form" onSubmit={vehicleForm}><div className="form-grid"><Field name="code" label="Vehicle code"/><Field name="registration" label="Registration number"/><Select name="type" label="Vehicle type" rows={[["bus","Bus"],["minibus","Minibus"],["van","Van"],["car","Car"]]}/><Field name="capacity" label="Seat capacity" type="number"/><Field name="inspection" label="Inspection due" type="date"/><Field name="insurance" label="Insurance due" type="date"/></div><button className="primary" disabled={busy}>Register vehicle</button></form>{t.vehicles.map(item=><article className="document-row" key={item.id}><strong>{item.code} · {item.registrationNumber}</strong><span>{item.vehicleType} · {item.capacity} seats</span><small>{item.status}</small></article>)}</section><section className="panel"><div className="panel-title"><UsersRound/><div><span>DRIVERS</span><h3>Activate only approved driver accounts</h3></div></div><form className="settings-form" onSubmit={driverForm}><div className="form-grid"><label>Approved driver<select name="userId" required><option value="">Choose driver account</option>{driverMembers.map(item=><option key={item.id} value={item.profileId}>{item.name}</option>)}</select></label><Field name="licence" label="Licence reference"/><Field name="expires" label="Licence expiry" type="date"/><Field name="phone" label="Driver phone" optional/></div><button className="primary" disabled={busy}>Activate driver</button></form>{t.drivers.map(item=><article className="document-row" key={item.id}><strong>{item.name}</strong><span>{item.status}</span><small>Licence valid to {item.licenseExpiresOn}</small></article>)}</section></section>:null}
 </div>;
}
function Field({name,label,type="text",defaultValue="",optional=false}:{name:string;label:string;type?:string;defaultValue?:string;optional?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={defaultValue} required={!optional}/></label>;}
function Select({name,label,rows}:{name:string;label:string;rows:[string,string][]}){return <label>{label}<select name={name} required>{rows.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
function Stops({stops,name,label,optional=false}:{stops:{id:string;name:string}[];name:string;label:string;optional?:boolean}){return <label>{label}<select name={name} required={!optional}><option value="">{optional?"No stop":"Choose stop"}</option>{stops.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;}
