import { ArrowRight, CalendarRange, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import type { SchoolSetup } from "../domain/types";
import { createIdempotencyKey } from "../domain/rules";
import { executeClassTransition, previewClassTransition, type ClassTransitionPreview } from "../lib/yearTransition";
import { userFacingError } from "../lib/userFacingError";

export default function YearTransitionStudio({setup,onChanged}:{setup:SchoolSetup;onChanged?:()=>Promise<void>}){
 const classes=setup.classes.filter(item=>item.academicYearId),years=new Map(setup.academicYears.map(item=>[item.id,item]));
 const[fromClassId,setFromClassId]=useState(classes[0]?.id??""),[toClassId,setToClassId]=useState(""),[preview,setPreview]=useState<ClassTransitionPreview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const fromClass=classes.find(item=>item.id===fromClassId),toChoices=useMemo(()=>classes.filter(item=>item.id!==fromClassId&&item.academicYearId!==fromClass?.academicYearId),[classes,fromClassId,fromClass?.academicYearId]);
 const toClass=toChoices.find(item=>item.id===toClassId);
 async function review(){setBusy(true);setError("");setMessage("");setPreview(null);try{setPreview(await previewClassTransition(fromClassId,toClassId));}catch(reason){setError(userFacingError(reason,"The year transition could not be previewed. Check the class setup and try again."));}finally{setBusy(false);}}
 async function execute(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!preview)return;const f=new FormData(event.currentTarget),reason=String(f.get("reason")||"");setBusy(true);setError("");setMessage("");try{const result=await executeClassTransition({fromClassId,toClassId,expectedCount:preview.affectedLearners,reason,idempotencyKey:createIdempotencyKey("class-transition")});setMessage(`${result.movedLearners} learner${result.movedLearners===1?"":"s"} moved to ${result.destinationClass}. The previous placement remains in school history.`);setPreview(null);if(onChanged)await onChanged();}catch(reason){setError(userFacingError(reason,"The class transition could not be completed. Nothing has been assumed changed. Review the class again and try once more."));}finally{setBusy(false);}}
 if(classes.length<2)return <section className="studio-section"><header className="object-header"><div><span>YEAR TRANSITION</span><h3>Promote or move learners safely</h3><p>Add classes to academic years before using year-end transitions.</p></div><CalendarRange/></header></section>;
 return <section className="studio-section year-transition-studio"><header className="object-header"><div><span>YEAR TRANSITION</span><h3>Move a class into its next academic year</h3><p>Preview first. DREEM checks the learner count again at execution time, preserves each previous placement and records who made the change.</p></div><CalendarRange/></header>
  {error?<div className="form-status error" role="alert">{error}</div>:null}{message?<div className="form-status success" role="status"><ShieldCheck/>{message}</div>:null}
  <div className="transition-builder"><label>Current class<select value={fromClassId} onChange={event=>{setFromClassId(event.target.value);setToClassId("");setPreview(null)}}><option value="">Choose current class</option>{classes.map(item=><option key={item.id} value={item.id}>{item.name} · {years.get(item.academicYearId??"")?.name??"Year not named"}</option>)}</select></label><ArrowRight/><label>Destination class<select value={toClassId} onChange={event=>{setToClassId(event.target.value);setPreview(null)}}><option value="">Choose destination class</option>{toChoices.map(item=><option key={item.id} value={item.id}>{item.name} · {years.get(item.academicYearId??"")?.name??"Year not named"}</option>)}</select></label><button type="button" disabled={busy||!fromClassId||!toClassId} onClick={()=>void review()}>Preview transition</button></div>
  {fromClass&&toClass&&!preview?<p className="quiet-note">Nothing changes until you preview and confirm. Learners currently remain in {fromClass.name}.</p>:null}
  {preview?<form className="transition-preview" onSubmit={execute}><div className="transition-count"><UsersRound/><div><small>LEARNERS AFFECTED</small><strong>{preview.affectedLearners}</strong><span>{preview.fromClassName} → {preview.toClassName}</span></div></div><div><strong>Before you continue</strong><p>DREEM will re-check that {preview.affectedLearners} learners are still in {preview.fromClassName}. If the class changed after this preview, the transition stops instead of moving the wrong learners.</p></div><label>Reason for this transition<textarea name="reason" required minLength={5} rows={3} placeholder="Example: End-of-year promotion approved after final results."/></label><button className="primary" disabled={busy||preview.affectedLearners<1}>{busy?"Moving learners…":`Move ${preview.affectedLearners} learner${preview.affectedLearners===1?"":"s"} to ${preview.toClassName}`}</button></form>:null}
 </section>;
}
