-- DREEM-TRANSPORT-001: school-owned transport operations. AFAT remains the
-- source of external place, road-condition, incident and mobility intelligence.

alter table public.dreem_school_memberships drop constraint if exists dreem_school_memberships_role_check;
alter table public.dreem_school_memberships add constraint dreem_school_memberships_role_check check(role in ('platform_founder','school_owner','principal','administrator','academic_head','bursar','accountant','teacher','tutor','transport_manager','driver','parent','student','auditor'));
alter table public.dreem_staff_invitations drop constraint if exists dreem_staff_invitations_role_check;
alter table public.dreem_staff_invitations add constraint dreem_staff_invitations_role_check check(role in ('school_owner','principal','administrator','academic_head','bursar','accountant','teacher','tutor','transport_manager','driver','auditor'));

create table public.dreem_transport_routes(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  route_code text not null,name text not null,direction text not null check(direction in ('inbound','outbound','both')),
  status text not null default 'active' check(status in ('planning','active','paused','retired')),created_by uuid not null references auth.users(id),
  idempotency_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(school_id,route_code),unique(school_id,idempotency_key)
);
create table public.dreem_transport_stops(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  route_id uuid not null references public.dreem_transport_routes(id) on delete cascade,stop_order integer not null check(stop_order>0),name text not null,
  landmark text,latitude numeric(9,6),longitude numeric(9,6),pickup_time time,dropoff_time time,created_at timestamptz not null default now(),
  unique(route_id,stop_order),check((latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180))
);
create table public.dreem_transport_vehicles(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  vehicle_code text not null,registration_number text not null,vehicle_type text not null check(vehicle_type in ('bus','minibus','van','car','other')),
  capacity integer not null check(capacity between 1 and 100),status text not null default 'available' check(status in ('available','assigned','maintenance','retired')),
  inspection_due_on date,insurance_due_on date,created_by uuid not null references auth.users(id),idempotency_key text not null,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,vehicle_code),unique(school_id,registration_number),unique(school_id,idempotency_key)
);
create table public.dreem_transport_drivers(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  user_id uuid not null references auth.users(id),license_reference text not null,license_expires_on date not null,phone text,
  status text not null default 'active' check(status in ('active','suspended','expired','inactive')),created_by uuid not null references auth.users(id),
  idempotency_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,user_id),unique(school_id,license_reference),unique(school_id,idempotency_key)
);
create table public.dreem_transport_consents(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,guardian_id uuid references public.dreem_guardians(id) on delete set null,
  decision text not null check(decision in ('granted','revoked')),terms_version text not null,capture_method text not null check(capture_method in ('signed_form','parent_portal','school_desk','verified_call')),
  guardian_name text not null,evidence jsonb not null default '{}'::jsonb,captured_by uuid not null references auth.users(id),idempotency_key text not null,
  captured_at timestamptz not null default now(),unique(school_id,idempotency_key)
);
create table public.dreem_transport_assignments(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,route_id uuid not null references public.dreem_transport_routes(id),
  pickup_stop_id uuid not null references public.dreem_transport_stops(id),dropoff_stop_id uuid not null references public.dreem_transport_stops(id),
  effective_from date not null,effective_to date,status text not null default 'active' check(status in ('active','paused','ended')),
  created_by uuid not null references auth.users(id),idempotency_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(school_id,idempotency_key),check(effective_to is null or effective_from<=effective_to)
);
create unique index dreem_transport_assignment_active_student_idx on public.dreem_transport_assignments(student_id) where status='active';
create table public.dreem_transport_trips(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,
  route_id uuid not null references public.dreem_transport_routes(id),vehicle_id uuid not null references public.dreem_transport_vehicles(id),driver_id uuid not null references public.dreem_transport_drivers(id),
  service_date date not null,direction text not null check(direction in ('inbound','outbound')),status text not null default 'dispatched' check(status in ('dispatched','in_progress','delayed','completed','cancelled')),
  assigned_students integer not null check(assigned_students>=0),scheduled_departure time,departed_at timestamptz,completed_at timestamptz,
  created_by uuid not null references auth.users(id),idempotency_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,idempotency_key),unique(route_id,service_date,direction)
);
create table public.dreem_transport_trip_events(
  id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,trip_id uuid not null references public.dreem_transport_trips(id) on delete cascade,
  event_type text not null check(event_type in ('dispatched','departed','stop_arrived','delay_reported','student_boarded','student_alighted','completed','cancelled','note')),
  stop_id uuid references public.dreem_transport_stops(id),student_id uuid references public.students(id),note text,evidence jsonb not null default '{}'::jsonb,
  actor_user_id uuid not null references auth.users(id),idempotency_key text not null,occurred_at timestamptz not null default now(),unique(school_id,idempotency_key)
);

alter table public.dreem_transport_routes enable row level security;alter table public.dreem_transport_stops enable row level security;alter table public.dreem_transport_vehicles enable row level security;alter table public.dreem_transport_drivers enable row level security;alter table public.dreem_transport_consents enable row level security;alter table public.dreem_transport_assignments enable row level security;alter table public.dreem_transport_trips enable row level security;alter table public.dreem_transport_trip_events enable row level security;
create index dreem_transport_stops_route_idx on public.dreem_transport_stops(route_id,stop_order);create index dreem_transport_consents_student_idx on public.dreem_transport_consents(student_id,captured_at desc);create index dreem_transport_assignments_route_idx on public.dreem_transport_assignments(route_id,status);create index dreem_transport_trips_service_idx on public.dreem_transport_trips(school_id,service_date,status);create index dreem_transport_trip_events_trip_idx on public.dreem_transport_trip_events(trip_id,occurred_at);

create policy dreem_transport_routes_read on public.dreem_transport_routes for select to authenticated using((select private.dreem_is_member(school_id)));
create policy dreem_transport_stops_read on public.dreem_transport_stops for select to authenticated using((select private.dreem_is_member(school_id)));
create policy dreem_transport_vehicles_read on public.dreem_transport_vehicles for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','driver','auditor'])));
create policy dreem_transport_drivers_read on public.dreem_transport_drivers for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','auditor'])) or user_id=(select auth.uid()));
create policy dreem_transport_consents_read on public.dreem_transport_consents for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','auditor'])) or (select private.dreem_can_view_student(school_id,student_id)));
create policy dreem_transport_assignments_read on public.dreem_transport_assignments for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','driver','auditor'])) or (select private.dreem_can_view_student(school_id,student_id)));
create policy dreem_transport_trips_read on public.dreem_transport_trips for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','driver','auditor'])) or exists(select 1 from public.dreem_transport_assignments a where a.route_id=dreem_transport_trips.route_id and a.status='active' and (select private.dreem_can_view_student(a.school_id,a.student_id))));
create policy dreem_transport_trip_events_read on public.dreem_transport_trip_events for select to authenticated using((select private.dreem_has_role(school_id,array['leadership','administrator','transport_manager','driver','auditor'])) or exists(select 1 from public.dreem_transport_trips t join public.dreem_transport_assignments a on a.route_id=t.route_id and a.status='active' where t.id=trip_id and (select private.dreem_can_view_student(a.school_id,a.student_id))));
revoke all on public.dreem_transport_routes,public.dreem_transport_stops,public.dreem_transport_vehicles,public.dreem_transport_drivers,public.dreem_transport_consents,public.dreem_transport_assignments,public.dreem_transport_trips,public.dreem_transport_trip_events from anon,authenticated;
grant select on public.dreem_transport_routes,public.dreem_transport_stops,public.dreem_transport_vehicles,public.dreem_transport_drivers,public.dreem_transport_consents,public.dreem_transport_assignments,public.dreem_transport_trips,public.dreem_transport_trip_events to authenticated;

create or replace function private.dreem_transport_school() returns uuid language sql stable security definer set search_path='' as $$select private.dreem_active_school_for_role(array['leadership','administrator','transport_manager'])$$;
revoke all on function private.dreem_transport_school() from public,anon;grant execute on function private.dreem_transport_school() to authenticated;

create or replace function public.dreem_configure_transport_route(p_route_code text,p_name text,p_direction text,p_stops jsonb,p_idempotency_key text)
returns table(route_id uuid,stops_count integer,route_status text) language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_route uuid;v_count integer;v_existing public.dreem_transport_routes%rowtype;
begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;if p_direction not in('inbound','outbound','both') then raise exception 'Unsupported route direction.';end if;if jsonb_typeof(p_stops)<>'array' or jsonb_array_length(p_stops)<1 then raise exception 'At least one ordered stop is required.';end if;
select * into v_existing from public.dreem_transport_routes where school_id=v_school and idempotency_key=p_idempotency_key;if found then route_id:=v_existing.id;select count(*) into stops_count from public.dreem_transport_stops where route_id=v_existing.id;route_status:=v_existing.status;return next;return;end if;
insert into public.dreem_transport_routes(school_id,route_code,name,direction,status,created_by,idempotency_key) values(v_school,upper(trim(p_route_code)),trim(p_name),p_direction,'active',v_actor,p_idempotency_key) returning id into v_route;
insert into public.dreem_transport_stops(school_id,route_id,stop_order,name,landmark,latitude,longitude,pickup_time,dropoff_time) select v_school,v_route,row_number() over(),trim(x->>'name'),nullif(trim(x->>'landmark'),''),nullif(x->>'latitude','')::numeric,nullif(x->>'longitude','')::numeric,nullif(x->>'pickup_time','')::time,nullif(x->>'dropoff_time','')::time from jsonb_array_elements(p_stops) x where nullif(trim(x->>'name'),'') is not null;
select count(*) into v_count from public.dreem_transport_stops where route_id=v_route;if v_count<1 then raise exception 'No valid route stops were supplied.';end if;perform private.dreem_write_event(v_school,'transport_route',v_route,'transport.route_configured',concat('transport.route:',p_idempotency_key),jsonb_build_object('route_code',p_route_code,'stops_count',v_count));route_id:=v_route;stops_count:=v_count;route_status:='active';return next;end;$$;

create or replace function public.dreem_register_transport_vehicle(p_vehicle_code text,p_registration_number text,p_vehicle_type text,p_capacity integer,p_inspection_due_on date,p_insurance_due_on date,p_idempotency_key text)
returns table(vehicle_id uuid,vehicle_status text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_id uuid;v_status text;begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;if p_vehicle_type not in('bus','minibus','van','car','other') or p_capacity not between 1 and 100 then raise exception 'Vehicle type or capacity is invalid.';end if;insert into public.dreem_transport_vehicles(school_id,vehicle_code,registration_number,vehicle_type,capacity,inspection_due_on,insurance_due_on,created_by,idempotency_key) values(v_school,upper(trim(p_vehicle_code)),upper(trim(p_registration_number)),p_vehicle_type,p_capacity,p_inspection_due_on,p_insurance_due_on,v_actor,p_idempotency_key) on conflict(school_id,idempotency_key) do update set updated_at=now() returning id,status into v_id,v_status;perform private.dreem_write_event(v_school,'transport_vehicle',v_id,'transport.vehicle_registered',concat('transport.vehicle:',p_idempotency_key),jsonb_build_object('capacity',p_capacity));vehicle_id:=v_id;vehicle_status:=v_status;return next;end;$$;

create or replace function public.dreem_register_transport_driver(p_user_id uuid,p_license_reference text,p_license_expires_on date,p_phone text,p_idempotency_key text)
returns table(driver_id uuid,driver_status text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_id uuid;v_status text;begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;if p_license_expires_on<current_date then raise exception 'An expired driver licence cannot be activated.';end if;if not exists(select 1 from public.dreem_school_memberships m where m.school_id=v_school and m.profile_id=p_user_id and m.status='approved' and m.role='driver') then raise exception 'Driver must have an approved driver membership.';end if;insert into public.dreem_transport_drivers(school_id,user_id,license_reference,license_expires_on,phone,status,created_by,idempotency_key) values(v_school,p_user_id,upper(trim(p_license_reference)),p_license_expires_on,nullif(trim(p_phone),''),'active',v_actor,p_idempotency_key) on conflict(school_id,idempotency_key) do update set updated_at=now() returning id,status into v_id,v_status;perform private.dreem_write_event(v_school,'transport_driver',v_id,'transport.driver_registered',concat('transport.driver:',p_idempotency_key),jsonb_build_object('user_id',p_user_id,'license_expires_on',p_license_expires_on));driver_id:=v_id;driver_status:=v_status;return next;end;$$;

create or replace function public.dreem_record_transport_consent(p_student_id uuid,p_guardian_id uuid,p_decision text,p_guardian_name text,p_terms_version text,p_capture_method text,p_evidence jsonb,p_idempotency_key text)
returns table(consent_id uuid,consent_decision text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_id uuid;begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;if p_decision not in('granted','revoked') or p_capture_method not in('signed_form','parent_portal','school_desk','verified_call') then raise exception 'Consent decision or capture method is invalid.';end if;if not exists(select 1 from public.students s where s.id=p_student_id and s.school_id=v_school) then raise exception 'Learner does not belong to this school.';end if;if p_guardian_id is not null and not exists(select 1 from public.dreem_student_guardians g where g.student_id=p_student_id and g.guardian_id=p_guardian_id and g.school_id=v_school) then raise exception 'Guardian is not linked to this learner.';end if;insert into public.dreem_transport_consents(school_id,student_id,guardian_id,decision,terms_version,capture_method,guardian_name,evidence,captured_by,idempotency_key) values(v_school,p_student_id,p_guardian_id,p_decision,trim(p_terms_version),p_capture_method,trim(p_guardian_name),coalesce(p_evidence,'{}'::jsonb),v_actor,p_idempotency_key) on conflict(school_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id,decision into v_id,consent_decision;perform private.dreem_write_event(v_school,'student',p_student_id,concat('transport.consent_',p_decision),concat('transport.consent:',p_idempotency_key),jsonb_build_object('consent_id',v_id,'guardian_id',p_guardian_id,'terms_version',p_terms_version));consent_id:=v_id;return next;end;$$;

create or replace function public.dreem_assign_student_transport(p_student_id uuid,p_route_id uuid,p_pickup_stop_id uuid,p_dropoff_stop_id uuid,p_effective_from date,p_effective_to date,p_idempotency_key text)
returns table(assignment_id uuid,assignment_status text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_id uuid;v_status text;v_consent text;begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;select c.decision into v_consent from public.dreem_transport_consents c where c.school_id=v_school and c.student_id=p_student_id order by c.captured_at desc limit 1;if v_consent is distinct from 'granted' then raise exception 'Current guardian transport consent is required.';end if;if not exists(select 1 from public.dreem_transport_routes r join public.dreem_transport_stops p on p.route_id=r.id join public.dreem_transport_stops d on d.route_id=r.id where r.id=p_route_id and r.school_id=v_school and r.status='active' and p.id=p_pickup_stop_id and d.id=p_dropoff_stop_id) then raise exception 'Route and stops must be active and belong together.';end if;if not exists(select 1 from public.students s where s.id=p_student_id and s.school_id=v_school) then raise exception 'Learner does not belong to this school.';end if;insert into public.dreem_transport_assignments(school_id,student_id,route_id,pickup_stop_id,dropoff_stop_id,effective_from,effective_to,status,created_by,idempotency_key) values(v_school,p_student_id,p_route_id,p_pickup_stop_id,p_dropoff_stop_id,p_effective_from,p_effective_to,'active',v_actor,p_idempotency_key) on conflict(school_id,idempotency_key) do update set updated_at=now() returning id,status into v_id,v_status;perform private.dreem_write_event(v_school,'transport_assignment',v_id,'transport.student_assigned',concat('transport.assignment:',p_idempotency_key),jsonb_build_object('student_id',p_student_id,'route_id',p_route_id));assignment_id:=v_id;assignment_status:=v_status;return next;end;$$;

create or replace function public.dreem_dispatch_transport_trip(p_route_id uuid,p_vehicle_id uuid,p_driver_id uuid,p_service_date date,p_direction text,p_scheduled_departure time,p_idempotency_key text)
returns table(trip_id uuid,trip_status text,assigned_students integer) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid:=private.dreem_transport_school();v_vehicle public.dreem_transport_vehicles%rowtype;v_driver public.dreem_transport_drivers%rowtype;v_count integer;v_id uuid;begin if v_actor is null or v_school is null then raise exception 'Transport management authorization is required.';end if;if p_direction not in('inbound','outbound') then raise exception 'Trip direction is invalid.';end if;select * into v_vehicle from public.dreem_transport_vehicles where id=p_vehicle_id and school_id=v_school and status in('available','assigned');select * into v_driver from public.dreem_transport_drivers where id=p_driver_id and school_id=v_school and status='active';if v_vehicle.id is null or v_driver.id is null or v_driver.license_expires_on<p_service_date then raise exception 'An available vehicle and licensed active driver are required.';end if;select count(*) into v_count from public.dreem_transport_assignments a where a.route_id=p_route_id and a.status='active' and p_service_date>=a.effective_from and (a.effective_to is null or p_service_date<=a.effective_to);if v_count>v_vehicle.capacity then raise exception 'Assigned learners exceed vehicle capacity.';end if;if not exists(select 1 from public.dreem_transport_routes r where r.id=p_route_id and r.school_id=v_school and r.status='active' and r.direction in(p_direction,'both')) then raise exception 'Route is not active for this direction.';end if;insert into public.dreem_transport_trips(school_id,route_id,vehicle_id,driver_id,service_date,direction,status,assigned_students,scheduled_departure,created_by,idempotency_key) values(v_school,p_route_id,p_vehicle_id,p_driver_id,p_service_date,p_direction,'dispatched',v_count,p_scheduled_departure,v_actor,p_idempotency_key) on conflict(school_id,idempotency_key) do update set updated_at=now() returning id,status,dreem_transport_trips.assigned_students into v_id,trip_status,assigned_students;insert into public.dreem_transport_trip_events(school_id,trip_id,event_type,note,actor_user_id,idempotency_key) values(v_school,v_id,'dispatched','Trip dispatched after licence, route and capacity checks.',v_actor,concat(p_idempotency_key,':event')) on conflict(school_id,idempotency_key) do nothing;perform private.dreem_write_event(v_school,'transport_trip',v_id,'transport.trip_dispatched',concat('transport.trip:',p_idempotency_key),jsonb_build_object('route_id',p_route_id,'vehicle_id',p_vehicle_id,'driver_id',p_driver_id,'assigned_students',v_count));trip_id:=v_id;return next;end;$$;

create or replace function public.dreem_progress_transport_trip(p_trip_id uuid,p_event_type text,p_stop_id uuid,p_student_id uuid,p_note text,p_evidence jsonb,p_idempotency_key text)
returns table(trip_id uuid,trip_status text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_trip public.dreem_transport_trips%rowtype;v_driver_user uuid;v_next text;begin if v_actor is null then raise exception 'Authentication is required.';end if;select * into v_trip from public.dreem_transport_trips t where t.id=p_trip_id for update;if found then select d.user_id into v_driver_user from public.dreem_transport_drivers d where d.id=v_trip.driver_id;end if;if not found or not(private.dreem_has_role(v_trip.school_id,array['leadership','administrator','transport_manager']) or v_driver_user=v_actor) then raise exception 'Trip-operation authorization is required.';end if;if exists(select 1 from public.dreem_transport_trip_events e where e.school_id=v_trip.school_id and e.idempotency_key=p_idempotency_key) then trip_id:=v_trip.id;trip_status:=v_trip.status;return next;return;end if;if p_event_type not in('departed','stop_arrived','delay_reported','student_boarded','student_alighted','completed','cancelled','note') then raise exception 'Unsupported trip event.';end if;if v_trip.status in('completed','cancelled') then raise exception 'This trip is already terminal.';end if;if p_stop_id is not null and not exists(select 1 from public.dreem_transport_stops s where s.id=p_stop_id and s.route_id=v_trip.route_id) then raise exception 'Stop is outside this route.';end if;if p_student_id is not null and not exists(select 1 from public.dreem_transport_assignments a where a.student_id=p_student_id and a.route_id=v_trip.route_id and a.status='active') then raise exception 'Learner is not assigned to this route.';end if;v_next:=case p_event_type when 'departed' then 'in_progress' when 'delay_reported' then 'delayed' when 'completed' then 'completed' when 'cancelled' then 'cancelled' else case when v_trip.status='dispatched' then 'in_progress' else v_trip.status end end;insert into public.dreem_transport_trip_events(school_id,trip_id,event_type,stop_id,student_id,note,evidence,actor_user_id,idempotency_key) values(v_trip.school_id,v_trip.id,p_event_type,p_stop_id,p_student_id,nullif(trim(p_note),''),coalesce(p_evidence,'{}'::jsonb),v_actor,p_idempotency_key);update public.dreem_transport_trips set status=v_next,departed_at=case when p_event_type='departed' then now() else departed_at end,completed_at=case when p_event_type='completed' then now() else completed_at end,updated_at=now() where id=v_trip.id returning id,status into trip_id,trip_status;perform private.dreem_write_event(v_trip.school_id,'transport_trip',v_trip.id,concat('transport.',p_event_type),concat('transport.event:',p_idempotency_key),jsonb_build_object('stop_id',p_stop_id,'student_id',p_student_id,'status',v_next));return next;end;$$;

create or replace function public.dreem_invite_staff(p_email text,p_full_name text,p_role text,p_idempotency_key text) returns table(invitation_id uuid,invitation_status text) language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_school uuid;v_id uuid;begin if v_actor is null then raise exception 'Authentication is required.';end if;v_school:=private.dreem_active_school_for_role(array['leadership','support']);if v_school is null then raise exception 'You are not authorized to invite staff.';end if;if p_role not in('school_owner','principal','administrator','academic_head','bursar','accountant','teacher','tutor','transport_manager','driver','auditor') then raise exception 'Unsupported staff role.';end if;if nullif(trim(p_email),'') is null then raise exception 'Email is required.';end if;insert into public.dreem_staff_invitations(school_id,email,full_name,role,invited_by,token_hash) values(v_school,lower(trim(p_email)),trim(p_full_name),p_role,v_actor,encode(public.digest(concat(p_idempotency_key,':',lower(trim(p_email))),'sha256'),'hex')) on conflict(school_id,email,role) do update set full_name=excluded.full_name,status='pending',updated_at=now() returning id,status into v_id,invitation_status;perform private.dreem_write_event(v_school,'staff_invitation',v_id,'staff.invited',concat('staff.invited:',p_idempotency_key),jsonb_build_object('email',lower(trim(p_email)),'role',p_role));invitation_id:=v_id;return next;end;$$;

create trigger dreem_transport_consents_immutable before update or delete on public.dreem_transport_consents for each row execute function private.dreem_prevent_mutation();create trigger dreem_transport_events_immutable before update or delete on public.dreem_transport_trip_events for each row execute function private.dreem_prevent_mutation();
create trigger dreem_audit_transport_routes after insert or update or delete on public.dreem_transport_routes for each row execute function private.dreem_audit_row();create trigger dreem_audit_transport_vehicles after insert or update or delete on public.dreem_transport_vehicles for each row execute function private.dreem_audit_row();create trigger dreem_audit_transport_drivers after insert or update or delete on public.dreem_transport_drivers for each row execute function private.dreem_audit_row();create trigger dreem_audit_transport_assignments after insert or update or delete on public.dreem_transport_assignments for each row execute function private.dreem_audit_row();create trigger dreem_audit_transport_trips after insert or update or delete on public.dreem_transport_trips for each row execute function private.dreem_audit_row();
revoke all on function public.dreem_configure_transport_route(text,text,text,jsonb,text),public.dreem_register_transport_vehicle(text,text,text,integer,date,date,text),public.dreem_register_transport_driver(uuid,text,date,text,text),public.dreem_record_transport_consent(uuid,uuid,text,text,text,text,jsonb,text),public.dreem_assign_student_transport(uuid,uuid,uuid,uuid,date,date,text),public.dreem_dispatch_transport_trip(uuid,uuid,uuid,date,text,time,text),public.dreem_progress_transport_trip(uuid,text,uuid,uuid,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.dreem_configure_transport_route(text,text,text,jsonb,text),public.dreem_register_transport_vehicle(text,text,text,integer,date,date,text),public.dreem_register_transport_driver(uuid,text,date,text,text),public.dreem_record_transport_consent(uuid,uuid,text,text,text,text,jsonb,text),public.dreem_assign_student_transport(uuid,uuid,uuid,uuid,date,date,text),public.dreem_dispatch_transport_trip(uuid,uuid,uuid,date,text,time,text),public.dreem_progress_transport_trip(uuid,text,uuid,uuid,text,jsonb,text) to authenticated;
